const chapter3 = {
    kaku: {
        たのむ: { 読み方: ['頼む'], form: '五段動詞、他動詞', 意味: "to request; to rely on; please (colloquially)" },
        わすれる: { 読み方: ['忘れる'], form: '一段動詞、他動詞', 意味: "to foreget" },
        さんまい: { 読み方: ['三枚'], form: '名詞', 意味: "three flat objects (sheets of paper, pieces of clothes, etc.)" },
        うける: { 読み方: ['受ける'], form: '一段動詞、他動詞', 意味: "to receive; to take (an exam)" },
        もうしこむ: { 読み方: ['申し込む'], form: '五段動詞、他動詞', 意味: "to apply" },
        きって: { 読み方: ['切手'], form: '名詞', 意味: "postage stamp" },
        ぶしつ: { 読み方: ['部室'], form: '名詞', 意味: "clubroom" },
        いたい: { 読み方: ['痛い'], form: 'イ形容詞', 意味: "painful; sore; cringy (colloquially)" },
        わるい: { 読み方: ['悪い'], form: 'イ形容詞', 意味: "bad; sorry; (my) bad" },
        おもな: { 読み方: ['主な'], form: 'ナ形容詞', 意味: "main" },
        りよう: { 読み方: ['利用'], form: '名詞、スル動詞', 意味: "to make use of; use" },
        いちばん: { 読み方: ['一番'], form: '名詞、ノ形容詞、副詞', 意味: "best; number one" },
        べんり: { 読み方: ['便利'], form: 'ナ形容詞', 意味: "convenient" },
        はらう: { 読み方: ['払う'], form: '五段動詞、他動詞', 意味: "to pay (money, bill)" },
        ちがう: { 読み方: ['違う'], form: '五段動詞、自動詞', 意味: "to differ (from); to not match the correct answer" },
        おこなう: { 読み方: ['行う'], form: '五段動詞、他動詞', 意味: "to carry out; to conduct [usually used in written language]" },
        もくてき: { 読み方: ['目的'], form: '名詞', 意味: "purpose; goal" },
        いがい: { 読み方: ['以外'], form: '名詞、副詞', 意味: "other than; with the exception of" },
        たすける: { 読み方: ['助ける'], form: '一段動詞、他動詞', 意味: "to help; to save" },
        にゅうがく: { 読み方: ['入学'], form: '名詞、スル動詞', 意味: "entry to school or university" },
        ぜんぶ: { 読み方: ['全部'], form: '名詞、ノ形容詞、副詞', 意味: "all; entire; whole" },
        おわる: { 読み方: ['終わる'], form: '五段動詞、自動詞', 意味: "be finished; be over" },
        きこく: { 読み方: ['帰国'], form: '名詞、スル動詞', 意味: "return to one's country" },
        かならずしも: { 読み方: ['必ずしも～ない'], form: '副詞', 意味: "not necessarily" },
        おんがく: { 読み方: ['音楽'], form: '名詞', 意味: "music" },
        ともだち: { 読み方: ['友達'], form: '名詞', 意味: "friend" },
        かいわ: { 読み方: ['会話'], form: '名詞、スル動詞', 意味: "conversation" },
        もの: { 読み方: ['者'], form: '名詞', 意味: "person [＝人]" },
        とくに: { 読み方: ['特に'], form: '副詞', 意味: "particularly; in particular" },
    },

    yomerebaii: {

        研究室:{ 読み方: ['けんきゅうしつ'], form: '名詞', 意味: "professor's office" },
        期末試験:{ 読み方: ['きまつしけん'], form: '名詞', 意味: "final exam; semester-end exam" },
        推薦状:{ 読み方: ['すいせんじょう'], form: '名詞', 意味: "letter of recommendation" },
        奨学金:{ 読み方: ['しょうがくきん'], form: '名詞', 意味: "scholarship" },
        用紙:{ 読み方: ['ようし'], form: '名詞', 意味: "form; blank form; sheet(s) of paper" },
        紙:{ 読み方: ['かみ'], form: '名詞', 意味: "ppaer" },
        締め切り:{ 読み方: ['しめきり'], form: '名詞', 意味: "deadline" },
        貸す:{ 読み方: ['かす'], form: '五段動詞、他動詞', 意味: "to lend; to loan" },
        熱:{ 読み方: ['ねつ'], form: '名詞', 意味: "fever" },
        寄る:{ 読み方: ['よる'], form: '五段動詞、自動詞', 意味: "to stop by" },
        情報:{ 読み方: ['じょうほう'], form: '名詞', 意味: "information" },
        交換:{ 読み方: ['こうかん'], form: '名詞、スル動詞', 意味: "exchange; switching" },
        場合:{ 読み方: ['ばあい'], form: '副詞、名詞', 意味: "case" },
        授業料:{ 読み方: ['じゅぎょうりょう'], form: '名詞', 意味: "tuition fee; course fee" },
        数:{ 読み方: ['かず'], form: '名詞', 意味: "number" },
        普通:{ 読み方: ['ふつう'], form: 'ノ形容詞、ナ形容詞', 意味: "common; usual; normal" },
        選ぶ:{ 読み方: ['えらぶ'], form: '五段動詞、他動詞', 意味: "to choose; to select" },
        書類選考:{ 読み方: ['しょるいせんこう'], form: '名詞、スル動詞', 意味: "screening by application forms; narrowing down a field of applicants based on resumes" },
        面接:{ 読み方: ['めんせつ'], form: '名詞、スル動詞', 意味: "interview" },
        成績:{ 読み方: ['せいせき'], form: '名詞', 意味: "grade; academic record" },
        性格:{ 読み方: ['せいかく'], form: '名詞', 意味: "character; personality" },
        態度:{ 読み方: ['たいど'], form: '名詞', 意味: "attitude; manner; behaviour" },
        優先:{ 読み方: ['ゆうせん'], form: '名詞、スル動詞、ノ形容詞', 意味: "preference; priority" },
        単位:{ 読み方: ['たんい'], form: '名詞', 意味: "credit (in school)" },
        認める:{ 読み方: ['みとめる'], form: '一段動詞、他動詞', 意味: "to recognize; to approve" },
        交渉:{ 読み方: ['こうしょう'], form: '名詞、スル動詞', 意味: "negotiation" },
        別科:{ 読み方: ['べっか'], form: '名詞', 意味: "special course" },
        国際学部:{ 読み方: ['こくさいがくぶ'], form: '名詞', 意味: "international division" },
        歴史:{ 読み方: ['れきし'], form: '名詞', 意味: "history" },
        経済:{ 読み方: ['けいざい'], form: '名詞', 意味: "economy; economics" },
        政治:{ 読み方: ['せいじ'], form: '名詞', 意味: "politics; government" },
        宗教:{ 読み方: ['しゅうきょう'], form: '名詞', 意味: "religion" },
        活動:{ 読み方: ['かつどう'], form: '名詞、スル動詞', 意味: "activity; action" },
        家庭:{ 読み方: ['かてい'], form: '名詞', 意味: "family; home" },
        希望者:{ 読み方: ['きぼうしゃ'], form: '名詞', 意味: "applicant; person interested in doing something" },
        住宅事情:{ 読み方: ['じゅうたくじじょう'], form: '名詞', 意味: "housing conditions/situation" },
        
    },
}

export default chapter3;