const chapter10 = {
    kaku: {

    },

    yomerebaii: {
        新幹線: { 読み方: ['しんかんせん'], form: '名詞', 意味: "Bullet Train" },
        時刻表: { 読み方: ['じこくひょう'], form: '名詞', 意味: "(train) schedule; timetable" },
        名古屋: { 読み方: ['なごや'], form: '都市', 意味: "Nagoya (city)" },
        指定席: { 読み方: ['していせき'], form: '名詞', 意味: "reserved seat" },
        運賃: { 読み方: ['うんちん'], form: '名詞', 意味: "(passenger) fare" },
        預かる: { 読み方: ['あずかる'], form: '五段動詞、他動詞', 意味: "to keep (something) for (someone); to look after" },
        箱根: { 読み方: ['はこね'], form: '町', 意味: "Hakone Town" },
        静か: { 読み方: ['しずか'], form: 'ナ形容詞', 意味: "Quiet" },
        宿: { 読み方: ['やど'], form: '名詞', 意味: "inn; lodging" },
        眺め: { 読み方: ['ながめ'], form: '名詞', 意味: "view" },
        連絡先: { 読み方: ['れんらくさき'], form: '名詞', 意味: "place where one can be reached" },
        風呂: { 読み方: ['ふろ'], form: '名詞', 意味: "bath" },
        冗談: { 読み方: ['じょうだん'], form: '名詞', 意味: "joke" },
        浴衣: { 読み方: ['ゆかた'], form: '名詞', 意味: "informal cotton kimono" },
        着替える: { 読み方: ['きがえる'], form: '一段動詞', 意味: "to change one's clothes" },
        有効: { 読み方: ['ゆうこう'], form: 'ナ形容詞、名詞', 意味: "valid; effective" },
        自然: { 読み方: ['しぜん'], form: '名詞', 意味: "nature" },
        奈良: { 読み方: ['なら'], form: '県、都市', 意味: "Nara (city, prefecture)" },
        農業: { 読み方: ['のうぎょう'], form: '名詞', 意味: "agriculture" },
        羊: { 読み方: ['ひつじ'], form: '名詞', 意味: "sheep" },
        景色: { 読み方: ['けしき'], form: '名詞', 意味: "scenery" },
        大阪: { 読み方: ['大阪'], form: '県、都市', 意味: "Osaka (city, prefecture)" },
        横浜: { 読み方: ['よこはま'], form: '都市', 意味: "Yokohama (city)" },
        神戸: { 読み方: ['こうべ'], form: '都市', 意味: "Kobe (city)" },
        国際的: { 読み方: ['こくさいてき'], form: 'ナ形容詞', 意味: "international" },
        芸術: { 読み方: ['げいじゅつ'], form: '名詞', 意味: "(fine) arts; the arts" },
        醜い: { 読み方: ['みにくい'], form: 'イ形容詞', 意味: "ugly" },
        混雑: { 読み方: ['こんざつ'], form: '名詞、スル動詞', 意味: "congestion; crowding" },
        批判: { 読み方: ['ひはん'], form: '名詞、スル動詞', 意味: "criticism" },
        秩序: { 読み方: ['ちつじょ'], form: '名詞', 意味: "order; regularity" },
        特徴: { 読み方: ['とくちょう'], form: '名詞', 意味: "feature; trait; characteristics" },
        犯罪: { 読み方: ['はんざい'], form: '名詞', 意味: "crime" },
        魅力的: { 読み方: ['みりょくてき'], form: 'ナ形容詞', 意味: "charming; attractive" },
        被害: { 読み方: ['ひがい'], form: '名詞', 意味: "damage" },
        城: { 読み方: ['しろ、ジョウ'], form: '名詞、接尾語', 意味: "castle" },
        桜島: { 読み方: ['さくらじま'], form: '火山島', 意味: "Mt. Sakurajima" },
        温泉: { 読み方: ['おんせん'], form: '名詞', 意味: "hot spring" },
    },
}

export default chapter10;