const chapter2 = {
    kaku: {
        れい: { 読み方: ['例'], form: '名詞', 意味: "example" },
        あさ: { 読み方: ['朝'], form: '名詞', 意味: "morning" },
        ごご: { 読み方: ['午後'], form: '名詞', 意味: "p.m.; afternoon" },
        へん: { 読み方: ['変'], form: 'ナ形容詞', 意味: "strange; weird" },
        いみ: { 読み方: ['意味'], form: '名詞', 意味: "meaning" },
        さげる: { 読み方: ['下げる'], form: '一段動詞、他動詞', 意味: "to lower" },
        わかる: { 読み方: ['分かる'], form: '五段動詞、自動詞', 意味: "to understand; to comprehend" },
        めざましとけい: { 読み方: ['目覚まし時計'], form: '名詞', 意味: "alarm clock" },
        ねむい: { 読み方: ['眠い'], form: 'イ形容詞', 意味: "sleepy" },
        こえ: { 読み方: ['声'], form: '名詞', 意味: "voice" },
        にじはん: { 読み方: ['二時半'], form: '時', 意味: "2:30" },
        むずかしい: { 読み方: ['難しい'], form: 'イ形容詞', 意味: "difficult" },
        たいへん: { 読み方: ['大変'], form: 'ナ形容詞', 意味: "difficult; hard" },
        外: { 読み方: ['そと'], form: '名詞', 意味: "outside" },
        おおあめ: { 読み方: ['大雨'], form: '名詞', 意味: "heavy rain" },
        いそぐ: { 読み方: ['急ぐ'], form: '五段動詞、自動詞、他動詞', 意味: "to hurry" },
        さきに: { 読み方: ['先に'], form: '副詞', 意味: "ahead (of someone); ahead (of time)" },
        あとで: { 読み方: ['後で'], form: '副詞', 意味: "afterwards" },
        よしだ: { 読み方: ['吉田'], form: '名字', 意味: "good luck + ricefield" },
        じだい: { 読み方: ['時代'], form: '時相名刺', 意味: "time period; those days" },
        だす: { 読み方: ['出す'], form: '五段動詞、他動詞', 意味: "to take out; to put out" },
        ぼく: { 読み方: ['僕'], form: '代名詞', 意味: "I; me" },
        ばんごう: { 読み方: ['番号'], form: '名詞', 意味: "number; series of digits" },
        にちべい: { 読み方: ['日米'], form: '名詞、ノ形容詞', 意味: "日本とアメリカ" },
        こまる: { 読み方: ['（～に）困る'], form: '五段動詞、自動詞', 意味: "to have difficulty (with~); to be troubled" },
        たぶん: { 読み方: ['多分'], form: '副詞', 意味: "perhaps; probably" },
        かわり: { 読み方: ['代わり（に）'], form: '表現', 意味: "instead of; in exchange for" },
        あたる: { 読み方: ['（～に）当たる'], form: '五段動詞、自動詞', 意味: "to correspond (to~)" },
        あいて: { 読み方: ['相手'], form: '名詞', 意味: "addressee; the person you are talking to" },
        めうえ: { 読み方: ['目上'], form: '名詞', 意味: "person of higher status; one's senior/superior" },
        ゆうじん: { 読み方: ['友人'], form: '名詞', 意味: "friend (more formal than 友達)" },
        やくす: { 読み方: ['訳す'], form: '五段動詞、他動詞', 意味: "to translate" },
        せつめい: { 読み方: ['説明'], form: 'スル動詞、名詞', 意味: "explanation" },
        たとえば: { 読み方: ['例えば'], form: '副詞', 意味: "for example" },
        しょくじ: { 読み方: ['食事'], form: '名詞、スル動詞', 意味: "meal; dinner" },
        たいして: { 読み方: ['(それに)対して'], form: '表現', 意味: "in response (to that); towards; regarding" },
        かぞく: { 読み方: ['家族'], form: '名詞', 意味: "family" },
        すうじつまえ: { 読み方: ['数日前'], form: '名詞', 意味: "several days ago" },
        きまりもんく: { 読み方: ['決まり文句'], form: '名詞', 意味: "set phrase" },
        ようご: { 読み方: ['用語'], form: '名詞', 意味: "term(s); terminology" },
        ほうが: { 読み方: ['（～の）方が'], form: '表現', 意味: "~is more... than" },
        きゃく: { 読み方: ['客'], form: '名詞', 意味: "guest; visitor; customer" },
        こども: { 読み方: ['子供'], form: '名詞', 意味: "child" },
        おぼえる: { 読み方: ['覚える'], form: '一段動詞、他動詞', 意味: "to remember" },
        だいじ: { 読み方: ['大事（な）'], form: 'ナ形容詞', 意味: "important" },
    },

    yomerebaii: {

        言葉:{ 読み方: ['ことば'], form: '名詞', 意味: "word(s); expression(s)" },
        会釈:{ 読み方: ['えしゃく'], form: 'スル動詞、名詞', 意味: "to greet by bowing slightly" },
        頭:{ 読み方: ['あたま'], form: '名詞', 意味: "head" },
        鳴る:{ 読み方: ['なる'], form: '五段動詞、自動詞', 意味: "to sound; to ring" },
        寮:{ 読み方: ['りょう'], form: '名詞', 意味: "dormitory" },
        部屋:{ 読み方: ['へや'], form: '名詞', 意味: "room" },
        同室:{ 読み方: ['どうしつ'], form: '名詞', 意味: "same room; sharing a room" },
        寝る:{ 読み方: ['ねる'], form: '一段動詞、自動詞', 意味: "to sleep; to go to bed" },
        終わる:{ 読み方: ['おわる'], form: '五段動詞、自動詞', 意味: "be finished; be over" },
        授業:{ 読み方: ['じゅぎょう'], form: '名詞', 意味: "class" },
        遅れる:{ 読み方: ['おくれる'], form: '一段動詞、自動詞', 意味: "to be late" },
        一郎:{ 読み方: ['いちろう'], form: '男性の名前', 意味: "often given to the oldest son;\none + son" },
        同級生:{ 読み方: ['どうきゅうせい'], form: '名詞', 意味: "classmate" },
        質問:{ 読み方: ['しつもん'], form: '名詞、スル動詞', 意味: "question" },
        病気:{ 読み方: ['びょうき'], form: '名詞、ノ形容詞', 意味: "sickness; illness" },
        非常:{ 読み方: ['ひじょう（に）'], form: '', 意味: "emergency; (very; extremely)" },
        寒い:{ 読み方: ['さむい'], form: 'イ形容詞', 意味: "cold" },
        別れる:{ 読み方: ['（～と）わかれる'], form: '一段動詞、自動詞', 意味: "to part（from～）;\nto say farewell（to～）" },
        顔:{ 読み方: ['かお'], form: '名詞', 意味: "face" },
        一般的:{ 読み方: ['いっぱんてき'], form: 'ナ形容詞', 意味: "general" },
        
    },
}

export default chapter2;