const chapter7 = {
    kaku: {
        こばやし: { 読み方: ['小林'], form: '名字', 意味: "small + grove" },
        しあい: { 読み方: ['試合'], form: '名詞、スル動詞', 意味: "match" },
        おいわい: { 読み方: ['お祝い'], form: '名詞、スル動詞', 意味: "celebration" },
        かちょう: { 読み方: ['課長'], form: '名詞', 意味: "section chief" },
        おと: { 読み方: ['音'], form: '名詞', 意味: "sound" },
        ぶひん: { 読み方: ['部品'], form: '名詞', 意味: "parts" },
        くみたてる: { 読み方: ['組み立てる'], form: '一段動詞、他動詞', 意味: "to assemble; to put together" },
        ほしい: { 読み方: ['欲しい'], form: 'イ形容詞', 意味: "to want" },
        てにいれる: { 読み方: ['手に入れる'], form: '表現、一段動詞、他動詞', 意味: "to obtain" },
        わかい: { 読み方: ['若い'], form: 'イ形容詞', 意味: "young" },
        むかし: { 読み方: ['昔'], form: 'ノ形容詞、名詞', 意味: "the past; the old days" },
        ようじ: { 読み方: ['用事'], form: '名詞', 意味: "errands; things to do" },
        でぐち: { 読み方: ['出口'], form: '名詞', 意味: "exit" },
        ちゅうおう: { 読み方: ['中央'], form: '名詞、ノ形容詞', 意味: "central; center" },
        たのしみ: { 読み方: ['（～を）楽しみにしています'], form: '表現', 意味: "to be looking forward (to~)" },
        えいが: { 読み方: ['映画'], form: '名詞', 意味: "movie" },
        あした: { 読み方: ['明日'], form: '名詞、副詞', 意味: "tomorrow" },
        さむらい: { 読み方: ['侍'], form: '名詞', 意味: "samurai" },
        ならぶ: { 読み方: ['並ぶ'], form: '五段動詞、自動詞', 意味: "to stand in line" },
        さかん: { 読み方: ['盛ん'], form: 'ナ形容詞', 意味: "thriving; flourishing" },
        はじめる: { 読み方: ['（～を）始める'], form: '一段動詞、他動詞', 意味: "to start; to begin" },
        ほか: { 読み方: ['他'], form: '名詞、ノ形容詞', 意味: "other" },
        ほうもん: { 読み方: ['訪問'], form: '名詞、スル動詞、ノ形容詞', 意味: "call; visit" },
        あつめる: { 読み方: ['集める'], form: '一段動詞、他動詞', 意味: "to collect; to assemble; to gather" },
        たたかう: { 読み方: ['戦う'], form: '五段動詞、自動詞', 意味: "to fight (with)" },
        まける: { 読み方: ['負ける'], form: '一段動詞、自動詞', 意味: "to lose" },
        たいへいよう: { 読み方: ['太平洋'], form: '名詞', 意味: "Pacific Ocean" },
        せんそう: { 読み方: ['戦争'], form: '名詞、スル動詞', 意味: "war" },
        せんし: { 読み方: ['戦死'], form: '名詞、スル動詞', 意味: "death in battle" },
        きんねん: { 読み方: ['近年'], form: '名詞、副詞', 意味: "recent years" },
        ふえる: { 読み方: ['増える'], form: '一段動詞、自動詞', 意味: "to increase" },
        けん: { 読み方: ['県'], form: '名詞、接尾詞', 意味: "prefecture" },
        ほうえい: { 読み方: ['放映'], form: '名詞、スル動詞', 意味: "televising; broadcasting" },
        おうべい: { 読み方: ['欧米'], form: '名詞', 意味: "Europe and America; the West" },
        かんしん: { 読み方: ['関心を集める'], form: '表現', 意味: "to gain interest" },
        でんとうてき: { 読み方: ['伝統的'], form: 'ナ形容詞', 意味: "traditional" },
        さいきん: { 読み方: ['最近'], form: '名詞、ノ形容詞、副詞', 意味: "recently" },
        しゅっしん: { 読み方: ['主審'], form: '名詞、ノ形容詞', 意味: "one's home" },
    },

    yomerebaii: {
        誘う: { 読み方: ['さそう'], form: '五段動詞、他動詞', 意味: "to invite (someone to do something with the speaker)" },
        野球: { 読み方: ['やきゅう'], form: '名詞', 意味: "baseball" },
        一緒: { 読み方: ['いっしょ'], form: '副詞、名詞、ノ形容詞', 意味: "together; same" },
        喜んで: { 読み方: ['喜んで'], form: '副詞', 意味: "with pleasure" },
        歳: { 読み方: ['～さい'], form: '接尾詞', 意味: "~years-old" },
        残念: { 読み方: ['ざんねん'], form: 'ナ形容詞、名詞', 意味: "regrettable; dissapointing" },
        秋葉原: { 読み方: ['あきはばら'], form: '東京の地方', 意味: "district of Tokyo, Japan." },
        電気街: { 読み方: ['でんきまち'], form: '名詞', 意味: "electronic store district" },
        山手線: { 読み方: ['やまのてせん'], form: '名詞', 意味: "[name of a train line]" },
        京浜東北線: { 読み方: ['けいひんとうほくせん'], form: '名詞', 意味: "[name of a train line]" },
        快速: { 読み方: ['かいそく'], form: '名詞', 意味: "rapid train or bus" },
        改札口: { 読み方: ['かいさつぐち'], form: '名詞', 意味: "ticket barrier; ticket gate" },
        黒沢: { 読み方: ['くろさわ'], form: '名字', 意味: "black + brilliance" },
        監督: { 読み方: ['かんとく'], form: '名詞', 意味: "movie director" },
        徹夜: { 読み方: ['てつや'], form: '名詞、スル動詞、ノ形容詞', 意味: "staying up all night" },
        選手: { 読み方: ['せんしゅ'], form: '名詞', 意味: "player (sports); athlete" },
        投げる: { 読み方: ['なげる'], form: '一段動詞、他動詞', 意味: "to throw" },
        三振: { 読み方: ['さんしん'], form: '名詞、スル動詞', 意味: "strikeout" },
        活躍する: { 読み方: ['かつやくする'], form: '名詞、スル動詞', 意味: "to play an active part in" },
        地域: { 読み方: ['ちいき'], form: '名詞', 意味: "area; region" },
        優勝: { 読み方: ['ゆうしょう'], form: '名詞、スル動詞', 意味: "overall victory; championship" },
        野球場: { 読み方: ['やきゅうじょう'], form: '名詞', 意味: "baseball stadium" },
        応援: { 読み方: ['おうえん'], form: '名詞、スル動詞', 意味: "cheering; rooting (for); support" },
        出場: { 読み方: ['しゅつじょう'], form: '名詞、スル動詞', 意味: "participation (in an event); to compete in" },
        名誉: { 読み方: ['めいよ'], form: 'ナ形容詞、名詞', 意味: "honor; honorable" },
        大相撲: { 読み方: ['おおずもう'], form: '名詞', 意味: "the professional sumo" },
        力士: { 読み方: ['りきし'], form: '名詞', 意味: "sumo wrestler" },
    },
}

export default chapter7;