const chapter8 = {
    kaku: {
        さがす: { 読み方: ['探す'], form: '五段動詞、他動詞', 意味: "to search for; to look for" },
        きょうし: { 読み方: ['教師'], form: '名詞', 意味: "teacher" },
        かかりのもの: { 読み方: ['係の者'], form: '名詞', 意味: "person who handles a particular business matter [者 is generally a humble expression for 人]" },
        しゅにん: { 読み方: ['主任'], form: '名詞', 意味: "a person in charge" },
        なんせい: { 読み方: ['南西'], form: '名詞', 意味: "southwest" },
        けいけん: { 読み方: ['経験'], form: '名詞', 意味: "experience" },
        ぜんぜん: { 読み方: ['全然'], form: '副詞', 意味: "(not) at all; totally" },
        こじん: { 読み方: ['個人'], form: '名詞、ノ形容詞', 意味: "personal; private" },
        たりる: { 読み方: ['足りる'], form: '一段動詞、自動詞', 意味: "to be sufficient; to be enough" },
        とくぎ: { 読み方: ['特技'], form: '名詞', 意味: "special talent; skill" },
        さっそく: { 読み方: ['早速'], form: '副詞', 意味: "to lose no time in ~ing; immediately; without delay" },
        かんどう: { 読み方: ['感動'], form: '名詞、スル動詞', 意味: "being deeply moved emotionally" },
        はくじん: { 読み方: ['白人'], form: '名詞', 意味: "Caucasian" },
        ゆるす: { 読み方: ['許す'], form: '五段動詞、他動詞', 意味: "to allow; to forgive" },
        むかえる: { 読み方: ['迎える'], form: '一段動詞、他動詞', 意味: "to welcome; to go out to meet; to greet" },
        けっしん: { 読み方: ['（～と）決心'], form: '名詞、スル動詞', 意味: "determination; to be determed to~" },
        にほんきんかい: { 読み方: ['日本近海'], form: '名詞', 意味: "Japanese waters; off the coast of Japan" },
        ほうほう: { 読み方: ['方法'], form: '名詞', 意味: "method" },
        さいわい: { 読み方: ['幸い'], form: 'イ形容詞', 意味: "fortunately; luckily" },
        むかう: { 読み方: ['（～へ）向かう'], form: '五段動詞、自動詞', 意味: "to head toward~" },
        ほっかいどう: { 読み方: ['北海道'], form: '県', 意味: "[日本の一番北の大きい島]" },
        けってい: { 読み方: ['（～に）決定する'], form: '名詞、スル動詞', 意味: "to decide[=～に決める]" },
        かれ: { 読み方: ['彼'], form: '代名詞', 意味: "he; him" },
        あらわれる: { 読み方: ['現れる'], form: '一段動詞、自動詞', 意味: "to appear" },
        つうやく: { 読み方: ['通訳'], form: '名詞、スル動詞', 意味: "interpreter; interpretation" },
        ふべん: { 読み方: ['不便'], form: '名詞、ナ形容詞', 意味: "inconvenience" },
        まなぶ: { 読み方: ['学ぶ'], form: '五段動詞', 意味: "to learn; to study" },
        かえす: { 読み方: ['返す'], form: '五段動詞、他動詞', 意味: "to return (something)" },
        びょうし: { 読み方: ['病死'], form: '名詞、スル動詞', 意味: "death from disease" },
        てんさい: { 読み方: ['天才'], form: '名詞', 意味: "genius" },
        えど: { 読み方: ['江戸'], form: '名詞', 意味: "Edo" },
    },

    yomerebaii: {
        対象: { 読み方: ['たいしょう'], form: '名詞、ノ形容詞', 意味: "target; object (of worship, study, etc.)" },
        詳しい: { 読み方: ['くわしい'], form: 'イ形容詞', 意味: "detailed" },
        主婦: { 読み方: ['しゅふ'], form: '名詞', 意味: "housewife" },
        親類: { 読み方: ['しんるい'], form: '名詞', 意味: "relative(s)" },
        翻訳: { 読み方: ['ほんやく'], form: '名詞、スル動詞', 意味: "translation" },
        掲示板: { 読み方: ['けいじばん'], form: '名詞', 意味: "bulletin board" },
        編集: { 読み方: ['へんしゅう'], form: '名詞、スル動詞', 意味: "editing" },
        雇う: { 読み方: ['やとう'], form: '五段動詞、他動詞', 意味: "to hire" },
        森山: { 読み方: ['もりやま'], form: '苗字', 意味: "forest + mountain" },
        大陸: { 読み方: ['大陸'], form: '名詞', 意味: "continent" },
        漂流者: { 読み方: ['ひょうりゅうしゃ'], form: '名詞', 意味: "person adrift on the sea; castaway (on an island)" },
        流れ着く: { 読み方: ['（～に）ながれつく'], form: '五段動詞', 意味: "to drift ashore" },
        祖先: { 読み方: ['そせん'], form: '名詞', 意味: "ancestor(s)" },
        憧れ: { 読み方: ['あこがれ'], form: '名詞、ノ形容詞', 意味: "longing; yearning" },
        雑誌: { 読み方: ['ざっし'], form: '名詞', 意味: "magazine" },
        抱く: { 読み方: ['いだく'], form: '五段動詞、他動詞', 意味: "to hold [written expression]" },
        鎖国: { 読み方: ['さこく'], form: '名詞、スル動詞', 意味: "national isolation" },
        温かい: { 読み方: ['あたたかい'], form: 'イ形容詞', 意味: "warm (for objects' temperature)" },
        船員: { 読み方: ['せんいん'], form: '名詞', 意味: "sailor" },
        陸地: { 読み方: ['りくち'], form: '名詞', 意味: "land" },
        幕府: { 読み方: ['ばくふ'], form: '名詞', 意味: "the Shogunate" },
        驚く: { 読み方: ['おどろく'], form: '五段動詞、自動詞', 意味: "to be surprised" },
        長崎: { 読み方: ['ながさき'], form: '都市、県', 意味: "Nagasaki (city, prefecture)" },
        難破: { 読み方: ['なんぱ'], form: '名詞、スル動詞', 意味: "shipwreck" },
        翌: { 読み方: ['よく'], form: '接頭辞', 意味: "the next (day/year/etc.) [＝次の]" },
        姪: { 読み方: ['めい'], form: '名詞', 意味: "niece" },
        開国: { 読み方: ['かいこく'], form: '名詞、スル動詞', 意味: "to open up the country (to foreigners) [＝国を開くこと]" },
        湾: { 読み方: ['わん'], form: '名詞', 意味: "bay" },
        戻る: { 読み方: ['もどる'], form: '五段動詞、自動詞', 意味: "to return" },
        条約: { 読み方: ['じょうやく'], form: '名詞', 意味: "treaty" },
        立派: { 読み方: ['りっぱ'], form: 'ナ形容詞', 意味: "splendid" },
    },
}

export default chapter8;