const chapter5 = {
    kaku: {
        しつもん: { 読み方: ['質問'], form: '名詞、スル動詞', 意味: "question; inquiry" },
        べっか: { 読み方: ['別科'], form: '名詞', 意味: "special course; another course" },
        うかがう: { 読み方: ['伺う'], form: '五段動詞、他動詞、謙譲語', 意味: "[humble form of 聞く (to ask)]" },
        あたらしい: { 読み方: ['新しい'], form: 'ィ形容詞', 意味: "new" },
        ごうしつ: { 読み方: ['～号室'], form: '名詞', 意味: "room number ~" },
        けんきゅうしつ: { 読み方: ['研究室'], form: '名詞', 意味: "professor's office; laboratory" },
        うつる: { 読み方: ['（～に）移る'], form: '五段動詞、自動詞', 意味: "to move (to~); to transfer (department)" },
        いっぽ: { 読み方: ['一歩'], form: '名詞、副詞', 意味: "a step; one step" },
        もういっぽ: { 読み方: ['もう一歩'], form: '表現', 意味: "to need just a little more improvement [lit., just one more step]" },
        せいせき: { 読み方: ['成績'], form: '名詞', 意味: "grades; results" },
        よしゅう: { 読み方: ['予習'], form: '名詞、スル動詞', 意味: "preparation for a lession (class)" },
        しゅくだい: { 読み方: ['宿題'], form: '名詞', 意味: "homework" },
        げんだいし: { 読み方: ['現代詩'], form: '名詞', 意味: "contemporary history" },
        ぶいん: { 読み方: ['部員'], form: '名詞', 意味: "staff; member (club, society, etc.)" },
        しま: { 読み方: ['島'], form: '名詞', 意味: "island" },
        にゅうがくしけん: { 読み方: ['入学試験'], form: '名詞', 意味: "entrance examination" },
        いっしょうけんめい: { 読み方: ['一生懸命'], form: 'ナ形容詞、副詞、名詞', 意味: "very hard; with utmost effort; with all one's might" },
        せいと: { 読み方: ['生徒'], form: '名詞', 意味: "student; pupil" },
        そつぎょう: { 読み方: ['卒業'], form: '名詞、スル動詞', 意味: "graduation; movinig on (from); outgrowing (somethingG)" },
        つぎのとし: { 読み方: ['次の年'], form: '名詞', 意味: "the following year" },
        たいせつ: { 読み方: ['大切'], form: 'ナ形容詞', 意味: "important" },
        りゆう: { 読み方: ['理由'], form: '名詞', 意味: "reason; motive" },
        かず: { 読み方: ['数'], form: '名詞', 意味: "number; amount" },
        すくない: { 読み方: ['少ない'], form: 'ィ形容詞', 意味: "few; a little; scarce" },
        つよい: { 読み方: ['強い'], form: 'ィ形容詞', 意味: "strong" },
        いっぱんてき: { 読み方: ['一般的'], form: 'ナ形容詞', 意味: "general; common; typical" },
        らく: { 読み方: ['楽'], form: 'ナ形容詞', 意味: "easy; comfortable; leading an easy life" },
        いいてん: { 読み方: ['いい点'], form: '名詞', 意味: "good mark; score; grade; point" },
        じゅうよう: { 読み方: ['重要'], form: 'ナ形容詞、名詞', 意味: "important; essential" },
        だいいち: { 読み方: ['～第一'], form: 'ノ形容詞、名詞', 意味: "~first" },
        つきあい: { 読み方: ['付き合い'], form: '名詞', 意味: "socialization; friendship; association" },
    },

    yomerebaii: {
        事務員: { 読み方: ['じむいん'], form: '名詞', 意味: "office clerk; office staff" },
        建物: { 読み方: ['たてもの'], form: '名詞', 意味: "building" },
        玄関: { 読み方: ['げんかん'], form: '名詞', 意味: "entrance (to a house or a building)" },
        貼り紙: { 読み方: ['はりがみ'], form: '名詞', 意味: "paper posted (on a board, a well, etc.)" },
        発表: { 読み方: ['はっぴょう'], form: 'スル動詞、名詞', 意味: "to announce; announcement; expressing (one's opinion)" },
        場所: { 読み方: ['ばしょ'], form: '名詞', 意味: "place" },
        佐藤: { 読み方: ['さとう'], form: '苗字', 意味: "assist + wisteria" },
        相談: { 読み方: ['そうだん'], form: 'スル動詞、名詞', 意味: "to consult (someone) about (something); asking (somebody) for advice; consultation" },
        調子: { 読み方: ['ちょうし'], form: '名詞', 意味: "condition; state of health" },
        心配: { 読み方: ['しんぱい'], form: '名詞、スル動詞、ナ形容詞', 意味: "worry; concern" },
        様子: { 読み方: ['ようすを見る'], form: '名詞', 意味: "state of affairs; appearance; see how it goes" },
        勧誘: { 読み方: ['かんゆう'], form: '名詞、スル動詞', 意味: "inviting someone to join (a club)" },
        無人島: { 読み方: ['むじんとう'], form: '名詞', 意味: "uninhabited island" },
        居酒屋: { 読み方: ['いざかや'], form: '名詞', 意味: "Japanese style pub; Japanese bar that also serves various dishes and snacks" },
        将来: { 読み方: ['しょうらい'], form: '名詞', 意味: "future (usually near)" },
        未来: { 読み方: ['みらい'], form: '名詞、ノ形容詞', 意味: "future (usually distant)" },
        一流: { 読み方: ['いちりゅう'], form: 'ノ形容詞、名詞', 意味: "first-class; first-rate" },
        就職: { 読み方: ['しゅうしょく'], form: '名詞、スル動詞', 意味: "finding employment; getting a job" },
        増える: { 読み方: ['ふえる'], form: '一段動詞、自動詞', 意味: "to increase" },
        塾: { 読み方: ['じゅく'], form: '名詞', 意味: "after-school school; cram school" },
        予備校: { 読み方: ['よびこう'], form: '名詞', 意味: "prepatory school (for college entrance exams)" },
        落ちる: { 読み方: ['おちる'], form: '一段動詞、自動詞', 意味: "to fall; (試験に落ちる　to fail an exam)" },
        浪人: { 読み方: ['ろうにん'], form: '名詞', 意味: "unemployed samurai; a high school graduate student who is spending a year studying for a college entrance exam" },
        傾向: { 読み方: ['けいこう'], form: '名詞、スル動詞', 意味: "tendency; trend" },
        最近: { 読み方: ['さいきん'], form: '名詞、ノ形容詞、副詞', 意味: "recently" },
        確かに: { 読み方: ['たしかに'], form: '副詞', 意味: "surely; certainly" },
        調査: { 読み方: ['ちょうさ'], form: '名詞、スル動詞', 意味: "investigation; examination; survey" },
        好く: { 読み方: ['すく'], form: '五段動詞、他動詞', 意味: "to like; to be fond of" },
        少子化: { 読み方: ['しょうしか'], form: '名詞、スル動詞', 意味: "declining birth rates" },
        関して: { 読み方: ['～にかんして'], form: '表現', 意味: "concerning; in relation to; as far as ... is concerned" },
        講義: { 読み方: ['こうぎ'], form: '名詞、スル動詞', 意味: "lecture" },
        年々: { 読み方: ['ねんねん'], form: '名詞、副詞', 意味: "year by year; every year" },
        減る: { 読み方: ['へる'], form: '五段動詞、自動詞', 意味: "to decrease (in number or size)" },
    },
}

export default chapter5;