const chapter1 = {
    kaku: {

        はじめて: { 読み方: ['初めて'], form: '副詞、の形容詞', 意味: "for the first time" },
        いしやま: { 読み方: ['石山'], form: '名字', 意味: "stone mountain" },
        しつれい: { 読み方: ['失礼'], form: 'スル動詞、ナ形容詞', 意味: "discourtesy; impoliteness" },
        もうす: { 読み方: ['申す'], form: '五段動詞、謙譲語', 意味: "humble form of 言う" },
        おねがいします: { 読み方: ['お願いします'], form: '表現', 意味: "please (Humble kenjougo)" },
        おしえる: { 読み方: ['教える'], form: '一段動詞、他動詞', 意味: "to teach; to inform" },
        まえ: { 読み方: ['前'], form: '名詞、ノ形容詞', 意味: "before; in front (of)" },
        りゅうがく: { 読み方: ['留学'], form: '名詞、スル動詞', 意味: "studying abroad" },
        ことし: { 読み方: ['今年'], form: '名詞、副詞', 意味: "this year" },
        みた: { 読み方: ['三田'], form: '名字', 意味: "three rice field" },
        おおい: { 読み方: ['多い'], form: 'イ形容詞', 意味: "many" },
        だいがくいん: { 読み方: ['大学院'], form: '名詞', 意味: "graduate school" },
        くん: { 読み方: ['君'], form: '接尾詞', 意味: "boy" },
        でんきこうがく: { 読み方: ['電気工学'], form: '名詞', 意味: "electrical engineering" },
        せんこう: { 読み方: ['専攻'], form: '名詞、スル動詞', 意味: "major subject; special study" },
        がくぶ: { 読み方: ['学部'], form: '名詞', 意味: "undergraduate" },
        じょうず: { 読み方: ['上手'], form: 'ナ形容詞', 意味: "skillful" },
        きみ: { 読み方: ['君'], form: '代名詞', 意味: "you" },
        こんど: { 読み方: ['今度'], form: '名詞、副詞', 意味: "one of these days; next time; this time" },
        とき: { 読み方: ['時'], form: '名詞', 意味: "time" },
        じつは: { 読み方: ['実は'], form: '表現', 意味: "actually; in fact; by the way; to tell you the truth" },
        ちゅうがく: { 読み方: ['中学'], form: '名詞', 意味: "middle school" },
        ぶんか: { 読み方: ['文化'], form: '名詞', 意味: "culture" },
        じょせい: { 読み方: ['女性'], form: '名詞', 意味: "woman; female" },
        かえる: { 読み方: ['帰る'], form: '五段動詞、自動詞', 意味: "to return; to come home" },
        とる: { 読み方: ['取る'], form: '五段動詞、他動詞', 意味: "to take" },
        うまれる: { 読み方: ['～で）生まれる'], form: '一段動詞、自動詞', 意味: "to be born (in/at~)" },
        わたし: { 読み方: ['私'], form: '代名詞', 意味: "I; me" },
        しごと: { 読み方: ['仕事'], form: '名詞', 意味: "work; job" },
        とまる: { 読み方: ['泊まる'], form: '五段動詞、自動詞', 意味: "to stay (over night)" },
        きにいる: { 読み方: ['（～が）気に入る'], form: '表現、五段動詞', 意味: "to like ~; to be fond (of~)" },
        あいだに: { 読み方: ['間に'], form: '副詞', 意味: "while; during (the time when)" },
        ところ: { 読み方: ['所'], form: '名詞', 意味: "place" },
        いえ: { 読み方: ['家'], form: '名詞', 意味: "house" },
        うち: { 読み方: ['家'], form: '名詞', 意味: "one's home" },
        でんわ: { 読み方: ['電話'], form: '名詞', 意味: "phone" },
        にっき: { 読み方: ['日記'], form: '名詞', 意味: "diary" },
        つく: { 読み方: ['（～に）着く'], form: '五段動詞、自動詞', 意味: "to arrive (at)" },
        おなじ: { 読み方: ['同じ'], form: '名詞', 意味: "same; equal; identical" },
        じぶん: { 読み方: ['自分'], form: '代名詞', 意味: "myself; oneself" },
        ちかい: { 読み方: ['近い'], form: 'イ形容詞', 意味: "near; close" },
        あるく: { 読み方: ['歩く'], form: '五段動詞、自動詞', 意味: "to walk" },
        だんせい: { 読み方: ['男性'], form: '名詞', 意味: "man; male" },
        きょねん: { 読み方: ['去年'], form: '名詞、副詞', 意味: "last year" },
        しかた: { 読み方: ['仕方'], form: '名詞', 意味: "way of doing something; method" },
        うつくしい: { 読み方: ['美しい'], form: 'イ形容詞', 意味: "beautiful" },
        ぶんぽう: { 読み方: ['文法'], form: '名詞', 意味: "grammar" },
        かんがえかた: { 読み方: ['考え方'], form: '名詞', 意味: "way of thinking" },

    },

    yomerebaii: {

        紹介:{ 読み方: ['しょうかい'], form: '名詞、スル動詞、ノ形容詞', 意味: "introduction" },
        宿題:{ 読み方: ['しゅくだい'], form: '名詞', 意味: "homework" },
        池田:{ 読み方: ['いけだ'], form: '名字', 意味: "pond + rice field" },
        友達:{ 読み方: ['ともだち'], form: '名詞', 意味: "friend" },
        趣味:{ 読み方: ['しゅみ'], form: '名詞', 意味: "hobby; pastime" },
        隣:{ 読み方: ['となり'], form: 'ノ形容詞、名詞', 意味: "next to; next door" },
        家族:{ 読み方: ['かぞく'], form: '名詞', 意味: "family; members of a family" },
        遊ぶ:{ 読み方: ['あそぶ'], form: '五段動詞、自動詞', 意味: "to play; to hang out" },
        知識:{ 読み方: ['ちしき'], form: '名詞', 意味: "knowledge; information" },
        豊富:{ 読み方: ['ほうふ'], form: 'ナ形容詞、名詞', 意味: "abundant; plentiful" },
        飛行機:{ 読み方: ['ひこうき'], form: '名詞', 意味: "airplane" },
        座る:{ 読み方: ['（～に）すわる'], form: '五段動詞、自動詞', 意味: "to sit（in/on～）" },
        卒業:{ 読み方: ['（～を）そつぎょう'], form: '名詞、スル動詞', 意味: "graduation; moving on (from)" },
        勤める:{ 読み方: ['（～に）つとめる'], form: '一段動詞、他動詞', 意味: "to work （for～）; to be employed （at～）" },
        休暇:{ 読み方: ['きゅうか'], form: '名詞', 意味: "vacation; absence (from work)" },
        京都:{ 読み方: ['きょうと'], form: '都市', 意味: "Kyoto (city, prefecture)\n京都市\n京都府" },
        育つ:{ 読み方: ['（～で）そだつ'], form: '五段動詞、自動詞', 意味: "to grow up（in～）" },
        一晩:{ 読み方: ['ひとばん'], form: '名詞、副詞', 意味: "one night; overnight" },
        両親:{ 読み方: ['りょうしん'], form: '名詞', 意味: "parents; both parents" },
        名刺:{ 読み方: ['めいし'], form: '名詞', 意味: "business card" },
        番号:{ 読み方: ['ばんごう'], form: '名刺', 意味: "number" },
        十数時間:{ 読み方: ['じゅうすうじかん'], form: '', 意味: "ten plus a few hours" },
        空港:{ 読み方: ['くうこう'], form: '名詞', 意味: "airport" },
        迎える:{ 読み方: ['むかえる'], form: '一段動詞、他動詞', 意味: "to welcome; to go out to meet; to greet" },
        呼ぶ:{ 読み方: ['（～を…で）よぶ'], form: '五段動詞、他動詞', 意味: "to call ～ by…" },
        時差ぼけ:{ 読み方: ['時差ボケ'], form: '名詞', 意味: "jet lag" },
        眠る:{ 読み方: ['ねむる'], form: '五段動詞、自動詞', 意味: "to sleep" },
        連れて:{ 読み方: ['つれて行く、つれてくる'], form: '', 意味: "to take someone to, to bring someone along" },
        結局:{ 読み方: ['けっきょく'], form: '副詞', 意味: "finally; in the end" },
        適当:{ 読み方: ['てきとう'], form: 'ナ形容詞', 意味: "appropriate; suitable" },
        引っ越す:{ 読み方: ['ひっこす'], form: '五段動詞、自動詞', 意味: "to move to a new place of residence" },
        若い:{ 読み方: ['わかい'], form: 'イ形容詞', 意味: "young" },
        お互い:{ 読み方: ['おたがい'], form: '名詞、ノ形容詞、副詞', 意味: "each other; one another" },
        娘:{ 読み方: ['むすめ'], form: '名詞', 意味: "daughter" },
        違う:{ 読み方: ['ちがう'], form: '五段動詞、自動詞', 意味: "to differ; to be different" },
        興味:{ 読み方: ['きょうみ'], form: '名詞', 意味: "interest (in something); curiosity (about something)" },

    },
}

export default chapter1;