const chapter6 = {
    kaku: {
        ちゅうもん: { 読み方: ['注文'], form: '名詞、スル動詞', 意味: "to order (something)" },
        つとめる: { 読み方: ['（～に）勤める'], form: '一段動詞、他動詞', 意味: "to work (for); to be employed (at)" },
        みせ: { 読み方: ['店'], form: '名詞', 意味: "shop; store" },
        ごはん: { 読み方: ['ご飯'], form: '名詞', 意味: "cooked rice" },
        おやこ: { 読み方: ['親子'], form: '名詞', 意味: "parent and child" },
        じつぶつ: { 読み方: ['実物'], form: '名詞、野形容詞', 意味: "actual thing; real thing" },
        てんいん: { 読み方: ['店員'], form: '名詞', 意味: "store clerk; shop-employee" },
        とり: { 読み方: ['鳥'], form: '名詞', 意味: "bird" },
        おもしろい: { 読み方: ['面白い'], form: 'イ形容詞', 意味: "interesting; amusing; entertaining" },
        ちゅうしょく: { 読み方: ['昼食'], form: '名詞', 意味: "lunch" },
        いまい: { 読み方: ['今井'], form: '名字', 意味: "now + well/town" },
        さま: { 読み方: ['様'], form: '接尾語', 意味: "[polite form of さん]" },
        おちゃ: { 読み方: ['お茶'], form: '名詞', 意味: "(green) tea" },
        せき: { 読み方: ['席'], form: '名詞', 意味: "seat" },
        うる: { 読み方: ['売る'], form: '五段動詞、他動詞', 意味: "to sell" },
        かぎる: { 読み方: ['～とは限らない'], form: '', 意味: "not necessarily ~ [限る = to limit]" },
        しゅうかん: { 読み方: ['習慣'], form: '名詞', 意味: "habit; (social) custom; practice" },
        りょこう: { 読み方: ['旅行'], form: '名詞、スル動詞', 意味: "travel; trip" },
        かんじる: { 読み方: ['～と感じる'], form: '一段動詞', 意味: "to feel that ~" },
        くうこう: { 読み方: ['空港'], form: '名詞', 意味: "airport" },
        わたす: { 読み方: ['渡す'], form: '五段動詞、他動詞', 意味: "to hand (something) to; to " },
        よびとめる: { 読み方: ['呼び止める'], form: '一段動詞、他動詞', 意味: "to call (someone) to stop; to hail (e.g. a taxi)" },
        りょかん: { 読み方: ['旅館'], form: '名詞', 意味: "Japanese-style inn" },
        しゅくはくりょう: { 読み方: ['宿泊料'], form: '名詞', 意味: "hotel charges" },
        こうきゅう: { 読み方: ['高級'], form: 'ナ形容詞、野形容詞、名詞', 意味: "high class; first-rate" },
        りょうりや: { 読み方: ['料理屋'], form: '名詞', 意味: "high class Japanese style restaurant" },
        ひつよう: { 読み方: ['必要'], form: 'ナ形容詞', 意味: "necessary" },
        しんぱい: { 読み方: ['心配'], form: '名詞、スル動詞、ナ形容詞', 意味: "to worry; concern" },
        なれる: { 読み方: ['慣れる'], form: '一段動詞、自動詞', 意味: "to get used to; to grow accustomed to; to become familar with" },
        ぶっか: { 読み方: ['物価'], form: '名詞', 意味: "cost-of-living; (commodity) prices" },
        くらべる: { 読み方: ['（～と）比べる'], form: '', 意味: "compared with" },
    },

    yomerebaii: {
        引用: { 読み方: ['いんよう'], form: '名詞、スル動詞、ノ形容詞', 意味: "to quote; quotation" },
        同僚: { 読み方: ['どうりょう'], form: '名詞', 意味: "colleague; co-worker" },
        高橋: { 読み方: ['たかはし'], form: '名字', 意味: "tall + bridge" },
        丼物: { 読み方: ['どんぶりもの'], form: '名詞', 意味: "[name of dish; bowl of rice topped with things]" },
        卵: { 読み方: ['たまご'], form: '名詞', 意味: "egg" },
        腰: { 読み方: ['こし'], form: '名詞', 意味: "lower back; waist; [腰をかける = 椅子に座る]" },
        握る: { 読み方: ['にぎる'], form: '五段動詞、他動詞', 意味: "to make sushi by hand" },
        並: { 読み方: ['なみ'], form: 'ノ形容詞、名詞', 意味: "(sushi serving of) medium quality/price" },
        召し上がる: { 読み方: ['召し上がる'], form: '五段動詞、他動詞、尊敬語', 意味: "[honorific form of 食べる・飲む]" },
        参る: { 読み方: ['まいる'], form: '五段動詞、自動詞、謙譲語', 意味: "[humble form of 行く・来る]" },
        請求書: { 読み方: ['せいきゅうしょ'], form: '名詞', 意味: "bill; invoice" },
        健一: { 読み方: ['けんいち'], form: '男の名前', 意味: "health + one" },
        辺り: { 読み方: ['あたり'], form: '名詞、接尾詞', 意味: "vicinity; nearby" },
        腹: { 読み方: ['はら'], form: '名詞', 意味: "stomach" },
        面倒: { 読み方: ['めんどう'], form: '名詞、ナ形容詞', 意味: "troublesome" },
        降りる: { 読み方: ['（～を）おりる'], form: '一段動詞、自動詞', 意味: "to get off~; to get out of (a vehicle)" },
        運転手: { 読み方: ['うんてんしゅ'], form: '名詞', 意味: "driver [by occupation]" },
        荷物: { 読み方: ['にもつ'], form: '名詞', 意味: "luggage" },
        運ぶ: { 読み方: ['はこぶ'], form: '五段動詞、他動詞', 意味: "to carry" },
        片付ける: { 読み方: ['かたづける'], form: '一段動詞、他動詞', 意味: "to clean; to tidy up" },
        食堂: { 読み方: ['しょくどう'], form: '名詞', 意味: "dining room" },
        簡単: { 読み方: ['かんたん'], form: 'ナ形容詞', 意味: "simple; easy" },
        含まれる: { 読み方: ['（～に）ふくまれる'], form: '受身形', 意味: "to be included (in~) [passive form of 含む]" },
        計算: { 読み方: ['けいさん'], form: '名詞、スル動詞', 意味: "calculation" },
        床屋: { 読み方: ['とこや'], form: '名詞', 意味: "barbershop" },
        美容院: { 読み方: ['びよういん'], form: '名詞', 意味: "beauty salon" },
        宣伝: { 読み方: ['せんでん'], form: '名詞、スル動詞', 意味: "advertisement" },
    },
}

export default chapter6;