const chapter4 = {
    kaku: {
        しゃしん: { 読み方: ['写真'], form: '名詞', 意味: "picture; photograph" },
        アメリカし: { 読み方: ['アメリカ史'], form: '名詞', 意味: "American history" },
        べつに: { 読み方: ['別に～ない'], form: '副詞', 意味: "(not) particularly; (not) especially" },
        おにいちゃん: { 読み方: ['お兄ちゃん'], form: '名詞', 意味: "(someone else's) older brother" },
        いもうと: { 読み方: ['妹'], form: '名詞', 意味: "little sister" },
        あに: { 読み方: ['兄'], form: '名詞', 意味: "(one's own) older brother" },
        にている: { 読み方: ['（～に）似ている'], form: '一段動詞、自動詞', 意味: "to resembele (~); to be similar" },
        しゅう: { 読み方: ['州'], form: '名詞、接尾語', 意味: "state" },
        じんこう: { 読み方: ['人口'], form: '名詞', 意味: "population" },
        まちがえる: { 読み方: ['間違える'], form: '一段動詞、他動詞', 意味: "to make a mistake" },
        ゆうめい: { 読み方: ['有名'], form: 'ナ形容詞', 意味: "famous" },
        みずうみ: { 読み方: ['湖'], form: '名詞', 意味: "lake" },
        はる: { 読み方: ['春'], form: '名詞', 意味: "spring" },
        あき: { 読み方: ['秋'], form: '名詞', 意味: "fall" },
        えき: { 読み方: ['駅'], form: '名詞', 意味: "train station" },
        とおい: { 読み方: ['遠い'], form: 'ィ形容詞', 意味: "far" },
        じてんしゃ: { 読み方: ['自転車'], form: '名詞', 意味: "bicycle" },
        かりる: { 読み方: ['借りる'], form: '一段動詞、他動詞', 意味: "to borrow; to rent" },
        つれる: { 読み方: ['連れる'], form: '一段動詞、他動詞', 意味: "to take (someone) with; to bring along" },
        ふゆ: { 読み方: ['冬'], form: '名詞', 意味: "winter" },
        ゆうしょく: { 読み方: ['夕食'], form: '名詞', 意味: "dinner [lit., evening meal]" },
        ひさしぶり: { 読み方: ['久しぶり'], form: 'ナ形容詞、ノ形容詞、名詞', 意味: "for the first time in a long time; a long time (since the last time)" },
        ほんとうに: { 読み方: ['本当に'], form: '副詞', 意味: "really; truly" },
        すえ: { 読み方: ['末'], form: '名詞', 意味: "end" },
        なつ: { 読み方: ['夏'], form: '名詞', 意味: "summer" },
        あつい: { 読み方: ['暑い'], form: 'ィ形容詞', 意味: "hot [with reference to weather]" },
        ながい: { 読み方: ['長い'], form: 'ィ形容詞', 意味: "long" },
        はやい: { 読み方: ['速い'], form: 'ィ形容詞', 意味: "fast; quick" },
        こんがっき: { 読み方: ['今学期'], form: '名詞', 意味: "this semester" },
        せいかつ: { 読み方: ['生活'], form: '名詞', 意味: "living; life (one's daily existence)" },
        やくにたつ: { 読み方: ['役に立つ'], form: '表現、五段動詞', 意味: "to be useful; to be helpful" },
        でんしゃ: { 読み方: ['電車'], form: '名詞', 意味: "train" },
        のる: { 読み方: ['（～に）乗る'], form: '五段動詞、自動詞', 意味: "to ride (in/on~)" },
        からだ: { 読み方: ['体'], form: '名詞', 意味: "body; health" },
        かわる: { 読み方: ['変わる'], form: '五段動詞、自動詞', 意味: "to change" },
        ぶっきょう: { 読み方: ['仏教'], form: '名詞', 意味: "Buddhism" },
        しんぶんきじ: { 読み方: ['新聞記事'], form: '名詞', 意味: "newspaper article" },
        かんじ: { 読み方: ['漢字'], form: '名詞', 意味: "kanji; Chinese character" },
        いっかい: { 読み方: ['一回'], form: '名詞、副詞', 意味: "once; one time; per occasion" },
        こんばん: { 読み方: ['今晩'], form: '名詞', 意味: "this evening" },
    },

    yomerebaii: {

        許可:{ 読み方: ['きょか'], form: '名詞', 意味: "permission" },
        財布:{ 読み方: ['さいふ'], form: '名詞', 意味: "wallet" },
        背:{ 読み方: ['せ'], form: '名詞', 意味: "one's height" },
        弁護士:{ 読み方: ['べんごし'], form: '名詞', 意味: "lawyer" },
        珍しい:{ 読み方: ['めずらしい'], form: 'イ形容詞', 意味: "rare; unusual" },
        全然:{ 読み方: ['ぜんぜん（～ない）'], form: '副詞', 意味: "(not) at all" },
        州都:{ 読み方: ['しゅうと'], form: '名詞', 意味: "state capital" },
        知事:{ 読み方: ['ちじ'], form: '名詞', 意味: "governor" },
        皆さん:{ 読み方: ['みなさん'], form: '名詞', 意味: "all of you; everyone" },
        求める:{ 読み方: ['もとめる'], form: '一段動詞、他動詞', 意味: "to request; to ask for" },
        偶然:{ 読み方: ['ぐうぜん'], form: 'ナ形容詞、ノ形容詞、副詞', 意味: "chance; coincidence; by chance" },
        暖かい:{ 読み方: ['あたｔかい'], form: 'イ形容詞', 意味: "pleasantly warm [with reference to weather]" },
        紅葉:{ 読み方: ['こうよう'], form: '名詞、スル動詞', 意味: "fall colors (of leaves)" },
        面白い:{ 読み方: ['おもしろい'], form: 'イ形容詞', 意味: "interesting, amusing" },
        経験:{ 読み方: ['けいけん'], form: '名詞、する動詞', 意味: "experience" },
        済む:{ 読み方: ['（～ないで）すむ'], form: '五段動詞、自動詞', 意味: "to get by without ~ing" },
        携帯:{ 読み方: ['けいたい'], form: '名詞', 意味: "cellular (phone)" },
        熱心:{ 読み方: ['ねっしん（に）'], form: 'ナ形容詞', 意味: "eager(ly); ardent(ly; enthusiastic(ly)" },
        打つ:{ 読み方: ['うつ'], form: '五段動詞、他動詞', 意味: "to type (messages)" },
        料理:{ 読み方: ['りょうり'], form: '名詞、スル動詞', 意味: "cooking; cuisine" },
        物:{ 読み方: ['もの'], form: '名詞', 意味: "thing" },
        体重:{ 読み方: ['たいじゅう'], form: '名詞', 意味: "body weight" },
        足りる:{ 読み方: ['たりる'], form: '一段動詞、自動詞', 意味: "to be sufficient; to be enough" },
        伝える:{ 読み方: ['つたえる'], form: '一段動詞、他動詞', 意味: "to convey; to report; to communicate" },

    },
}

export default chapter4;