const unit2_2 = {
    tango: {
        標準: { 読み方: ['ひょうじゅん'], form: '名詞', 意味: "standard; norm" },
        かなり: { 読み方: [''], form: '副詞', 意味: "considerably; fairly; quite" },
        高度: { 読み方: ['こうど'], form: 'ナ形容詞', 意味: "high degree; high-grade; advanced; sophisticated" },
        要する: { 読み方: ['ようする'], form: 'スル動詞、他動詞', 意味: "to need; to demand; to require" },
        暴力的: { 読み方: ['ぼうりょくてき'], form: 'ナ形容詞', 意味: "violent" },
        酔っ払う: { 読み方: ['よっぱらう'], form: '五段動詞、自動詞', 意味: "to get drunk" },
        理性: { 読み方: ['りせい'], form: '名詞', 意味: "(a sense of) reasoning; reason" },
        意志: { 読み方: ['いし'], form: '名詞', 意味: "will; intention; intent; determination" },
        弱まる: { 読み方: ['よわまる'], form: '五段動詞、自動詞', 意味: "to abate; to weaken; to be emaciated" },
        ぶつかる: { 読み方: [''], form: '五段動詞、自動詞', 意味: "to strike against; to collide with; to bump into" },
        駅員: { 読み方: ['えきいん'], form: '名詞', 意味: "(train) station attendant; station employee/staff" },
        なぐりかかる: { 読み方: [''], form: '五段動詞、自動詞', 意味: "to throw a punch at; to swing at" },
        寛大: { 読み方: ['かんだい'], form: 'ナ形容詞、名詞', 意味: "tolerant; generous; lenient" },
        無視: { 読み方: ['むし'], form: '名詞、スル動詞', 意味: "ignoring; disregarding" },
        意外: { 読み方: ['いがい'], form: 'ナ形容詞', 意味: "unexpected; surprising" },
        周囲: { 読み方: ['しゅうい'], form: '名詞', 意味: "surroundings" },
        家庭: { 読み方: ['かてい'], form: '名詞', 意味: "home; family; household" },
        好き勝手: { 読み方: ['すきかって'], form: 'ナ形容詞', 意味: "doing whatever one pleases" },
        着替える: { 読み方: ['きがえる'], form: '一段動詞', 意味: "to change one's clothes" },
        済ませる: { 読み方: ['すませる'], form: '一段動詞、他動詞', 意味: "to finish; get it done（＝済む）" },
        耐える: { 読み方: ['たえる'], form: '一段動詞、自動詞、他動詞', 意味: "to bear; to stand; to endure; to put up with" },
        キレる: { 読み方: [''], form: '一段動詞、自動詞', 意味: "to get angry; lose one's temper" },
        続出: { 読み方: ['ぞくしゅつ'], form: '名詞、スル動詞', 意味: "appearing one after another" },
        実行: { 読み方: ['じっこう'], form: '名詞、スル動詞', 意味: "execution (e.g. of a plan); carrying out" },
        ある種: { 読み方: ['あるしゅ'], form: '名詞、ノ形容詞', 意味: "certain kind of~; some sort of" },
        言い切る: { 読み方: ['いいきる'], form: '五段動詞、他動詞', 意味: "to say positively; declare; assert" },
        使用: { 読み方: ['しよう'], form: '名詞、スル動詞', 意味: "use; application; utilization" },
        ごく: { 読み方: [''], form: '副詞', 意味: "quite; very" },
        小声: { 読み方: ['こごえ'], form: '名詞、ノ形容詞', 意味: "low voice; whisper" },
        個室: { 読み方: ['こしつ'], form: '名詞', 意味: "private room; single room" },
        保つ: { 読み方: ['たもつ'], form: '五段動詞、他動詞', 意味: "to keep; to preserve; to maintain" },
        光景: { 読み方: ['こうけい'], form: '名詞', 意味: "scene; spectacle; sight; view" },
        いっさい: { 読み方: [''], form: '名詞、ノ形容詞', 意味: "all; whole; entirely" },
        逸脱: { 読み方: ['いつだつ'], form: '名詞、スル動詞', 意味: "deviation; departure" },
        静けさ: { 読み方: ['しずけさ'], form: '名詞', 意味: "stillness; silence; calm; serenity" },
    },

    kaku: {
        こんご: { 読み方: ['今後'], form: '名詞、副詞', 意味: "from now on; hereafter" },
        いしき: { 読み方: ['意識'], form: '名詞、スル動詞', 意味: "consciousness; becoming aware (of); awareness" },
        しかたない: { 読み方: ['仕方ない'], form: 'イ形容詞', 意味: "there's no (other) way; cannot be helped" },
        いっぽう: { 読み方: ['一方'], form: '接続詞', 意味: "on the other hand" },
        いがい: { 読み方: ['意外'], form: 'ナ形容詞', 意味: "unexpected; surprising" },
        こうど: { 読み方: ['高度'], form: 'ナ形容詞', 意味: "high-degree; high-grade; advanced; sophisticated" },
        ようする: { 読み方: ['要する'], form: 'スル動詞、他動詞', 意味: "to need; to demand; to require" },
        つかれる: { 読み方: ['疲れる'], form: '一段動詞、自動詞', 意味: "to get tired; to tire; to get fatigued" },
        りせい: { 読み方: ['理性'], form: '名詞', 意味: "reasoning; (sense of) reason" },
        えきいん: { 読み方: ['駅員'], form: '名詞', 意味: "(train) station staff/employee" },
        かてい: { 読み方: ['家庭'], form: '名詞', 意味: "home; family; household" },
        きがえる: { 読み方: ['着替える'], form: '一段動詞', 意味: "to change one's clothes" },
        じっこう: { 読み方: ['実行'], form: '名詞、スル動詞', 意味: "execution (e.g. of a plan); carrying out" },
        しよう: { 読み方: ['使用'], form: '名詞、スル動詞', 意味: "use; application; utilization" },
        こごえ: { 読み方: ['小声'], form: '名詞、ノ形容詞', 意味: "low voice; whisper" },
        こしつ: { 読み方: ['個室'], form: '名詞', 意味: "private room; single room" },
        あんぜん: { 読み方: ['安全'], form: 'ナ形容詞', 意味: "safety;security" },
    },

    yomerebaii: {
        標準: { 読み方: ['ひょうじゅん'], form: '名詞', 意味: "standard; norm" },
        暴力的: { 読み方: ['ぼうりょくてき'], form: 'ナ形容詞', 意味: "violent" },
        載る: { 読み方: ['のる'], form: '五段動詞、自動詞', 意味: "to be placed on; to appear (in print)" },
        酔っ払う: { 読み方: ['よっぱらう'], form: '五段動詞、自動詞', 意味: "to get drunk" },
        意志: { 読み方: ['いし'], form: '名詞', 意味: "will; intention; intent; determination" },
        弱まる: { 読み方: ['よわまる'], form: '五段動詞、自動詞', 意味: "to abate; to weaken; to be emaciated" },
        寛大: { 読み方: ['かんだい'], form: 'ナ形容詞、名詞', 意味: "tolerant; generous; lenient" },
        無視: { 読み方: ['むし'], form: '名詞、スル動詞', 意味: "ignoring; disregarding" },
        周囲: { 読み方: ['しゅうい'], form: '名詞', 意味: "surroundings" },
        踊る: { 読み方: ['おどる'], form: '五段動詞、自動詞', 意味: "to dance" },
        耐える: { 読み方: ['たえる'], form: '一段動詞、自動詞、他動詞', 意味: "to bear; to stand; to endure; to put up with" },
        続出: { 読み方: ['ぞくしゅつ'], form: '名詞、スル動詞', 意味: "appearing one after another" },
        携帯電話: { 読み方: ['けいたいでんわ'], form: '名詞', 意味: "cellular phone" },
        保つ: { 読み方: ['たもつ'], form: '五段動詞、他動詞', 意味: "to keep; to preserve; to maintain" },
        光景: { 読み方: ['こうけい'], form: '名詞', 意味: "scene; spectacle; sight; view" },
    },
}

export default unit2_2;