const unit4_2_sankou = {
    tango: {
        取引先: { 読み方: ['とりひきさき'], form: '名詞', 意味: "business partner; client" },
        重役: { 読み方: ['じゅうやく'], form: '名詞', 意味: "executive; important post; role with heavy responsibilities; top management" },
        出入り業者: { 読み方: ['でいりぎょうしゃ'], form: '名詞', 意味: "supplier" },
        営業責任者: { 読み方: ['えいぎょうせきにんしゃ'], form: '名詞', 意味: "sales manager" },
        通夜: { 読み方: ['つや'], form: '名詞', 意味: "a wake (the night before the funeral)" },
        略図: { 読み方: ['りゃくず'], form: '名詞', 意味: "rough map; rough sketch" },
        用が足りる: { 読み方: ['ようがたりる'], form: '表現、一段動詞', 意味: "will do; to do the job" },
        バツが悪い: { 読み方: ['バツ（が／の）わるい'], form: '表現、イ形容詞', 意味: "awkward; uncomfortable; emarassing" },
        覚える: { 読み方: ['[feelingをおぼえる'], form: '一段動詞、他動詞', 意味: "to feel" },
        降車口: { 読み方: ['こうしゃぐち'], form: '名詞', 意味: "exit (of a train or a bus)" },
        壁面: { 読み方: ['へきめん'], form: '名詞', 意味: "wall; surface of a wall" },
        ことさら: { 読み方: [''], form: '副詞、ナ形容詞', 意味: "especially; particularly" },
        眼をやる: { 読み方: ['め（／目）をやる'], form: '表現、五段動詞', 意味: "to glance; to look towards" },
        品がいい: { 読み方: ['ひんが(/のいい）'], form: '表現、イ形容詞', 意味: "elegant; graceful" },
        唐突: { 読み方: ['とうとつ'], form: 'ナ形容詞', 意味: "sudden; abrupt" },
        弁解: { 読み方: ['べんかい'], form: '名詞、スル動詞、他動詞', 意味: "explain oneself; explanation (e.g. for one's actions); justification" },
        もてあます: { 読み方: [''], form: '五段動詞、他動詞', 意味: "to have more than enough; to be too much for one" },
        売りに出る: { 読み方: ['うりにでる'], form: '表現、一段動詞', 意味: "to be sold" },
        借家: { 読み方: ['しゃくや'], form: '名詞', 意味: "rented house" },
        ひそか: { 読み方: [''], form: 'ナ形容詞', 意味: "secret; private" },
        ひそかに: { 読み方: [''], form: '副詞', 意味: "in one's heart; secretly" },
        やりとり: { 読み方: [''], form: '名詞、スル動詞、他動詞', 意味: "interaction; conversation" },
        流れる: { 読み方: ['ながれる'], form: '一段動詞、自動詞', 意味: "to flow" },
        胸が痛む: { 読み方: ['むねがいたむ'], form: '表現、五段動詞', 意味: "to break one's heart" },
        押し付ける: { 読み方: ['おしつける'], form: '一段動詞、他動詞', 意味: "to force; to force (against); to impose (one's will); to foist on (task, responsibility)" },
        成り立つ: { 読み方: ['なりたつ'], form: '五段動詞、自動詞', 意味: "to work out; could do; to be viable (of a business, lifestyle, etc.)" },
        狸寝入り: { 読み方: ['たぬきねいり'], form: '名詞、スル動詞、自動詞', 意味: "to pretend to be sleeping" },
    },
}

export default unit4_2_sankou;