const unit1_1 = {
    tango: {
        初めて: { 読み方: ['はじめて'], form: '副詞、の形容詞', 意味: "for the first time" },
        に対して: { 読み方: ['にたいして'], form: '表現', 意味: "towards~; against~" },
        行動する: { 読み方: ['こうどうする'], form: 'スル動詞', 意味: "to take action; behavior" },
        選ぶ: { 読み方: ['えらぶ'], form: '五段動詞、他動詞', 意味: "to choose; to select" },
        ウインクする: { 読み方: [''], form: 'スル動詞', 意味: "To wink" },
        握手する: { 読み方: ['あくしゅ（を）する'], form: 'スル動詞', 意味: "to handshake" },
        軽い: { 読み方: ['かるい'], form: 'ィ形容詞', 意味: "light" },
        頬: { 読み方: ['ほお／ほほ'], form: '名詞', 意味: "cheek" },
        おじぎする: { 読み方: [''], form: 'スル動詞', 意味: "to bow" },
        ハグする: { 読み方: [''], form: 'スル動詞', 意味: "to hug" },
        両手: { 読み方: ['りょうて'], form: '名詞', 意味: "both hands" },
        合わせる: { 読み方: ['あわせる'], form: '一段動詞い、他動詞', 意味: "to put together" },
        拝む: { 読み方: ['おがむ'], form: '五段動詞、他動詞', 意味: "to pray" },
        抵抗する: { 読み方: ['ていこう'], form: '名詞、スル動詞', 意味: "resistance; reluctance" },
        感じる: { 読み方: ['かんじる'], form: '一段動詞', 意味: "to feel" },
        必ず: { 読み方: ['かならず'], form: '副詞', 意味: "without fail; certainly" },
        伝える: { 読み方: ['つたえる'], form: '一段動詞、他動詞', 意味: "to convey; to report" },
        相手: { 読み方: ['あいて'], form: '名詞', 意味: "companion; partner" },
        尋ねる: { 読み方: ['たずねる'], form: '一段動詞、他動詞', 意味: "to ask; to enquire" },
        年齢: { 読み方: ['ねんれい'], form: '名詞', 意味: "age" },
        結婚する: { 読み方: ['けっこん'], form: '名詞、スル動詞', 意味: "marriage" },
        住所: { 読み方: ['じゅうしょ'], form: '名詞', 意味: "address" },
        職業: { 読み方: ['しょくぎょう'], form: '名詞', 意味: "occupation" },
        等: { 読み方: ['など／とう'], form: '接尾詞、助詞', 意味: "et cetera; the likes of; or something" },
        個人的: { 読み方: ['こじんてき'], form: 'ナ形容詞', 意味: "personal; private; individual" },
        情報: { 読み方: ['じょうほう'], form: '名詞', 意味: "information" },
        得る: { 読み方: ['える'], form: '一段動詞、他動詞', 意味: "to get; to earn; to acquire" },
        その他: { 読み方: ['そのた／そのほか'], form: '表現', 意味: "the rest; the others" },
        出身地: { 読み方: ['しゅっしんち'], form: '名詞', 意味: "birthplace" },
        出身校: { 読み方: ['しゅっしんこう'], form: '名詞', 意味: "alma mater" },
        年収: { 読み方: ['ねんしゅう'], form: '名詞', 意味: "annual income" },
        初対面: { 読み方: ['しょたいめん'], form: '名詞', 意味: "first meeting" },
        給料: { 読み方: ['きゅうりょう'], form: '名詞', 意味: "salary; earnings" },
        戸惑う: { 読み方: ['とまどう'], form: '五段動詞、自動詞', 意味: "to be bewildered; to be perplexed; to be confused" },
        よほど: { 読み方: [''], form: '副詞', 意味: "very; greatly; to a large extent" },
        親しい: { 読み方: ['したしい'], form: 'ィ形容詞', 意味: "close; intimate" },
        失礼な: { 読み方: ['しつれい'], form: 'ナ形容詞', 意味: "impolite; rude" },
        出会う: { 読み方: ['であう'], form: '五段動詞、自動詞', 意味: "to meet (by chance); to come across" },
        自身: { 読み方: ['じしん'], form: '名詞', 意味: "oneself" },
        傷つく: { 読み方: ['きずつく'], form: '五段動詞、自動詞', 意味: "to get injured; to get hurt feelings" },
        傷つける: { 読み方: ['きずつける'], form: '一段動詞、他動詞', 意味: "to injure; to hurt someone's feelings" },
        次: { 読み方: ['つぎ'], form: '名詞', 意味: "next" },
        言葉: { 読み方: ['ことば'], form: '名詞', 意味: "words; language" },
        性格: { 読み方: ['せいかく'], form: '名詞', 意味: "personality" },
        表す: { 読み方: ['あらわす'], form: '五段動詞、他動詞', 意味: "to show; to display; to express; to represent" },
        おとなしい: { 読み方: [''], form: 'ィ形容詞', 意味: "quiet; docile" },
        世話好き: { 読み方: ['せわずき'], form: 'ナ形容詞、名詞', 意味: "person who likes looking after others" },
        寂しがり屋: { 読み方: ['さびしがりや'], form: '名詞', 意味: "person who tends to get lonely; someone who easily succumbs to loneliness" },
        おせっかいな: { 読み方: [''], form: 'ナ形容詞', 意味: "meddling" },
        粘り強い: { 読み方: ['ねばりつよい'], form: 'ィ形容詞', 意味: "persistent; perservering; tenacious" },
        さっぱりした: { 読み方: [''], form: 'スル動詞', 意味: "feeling refreshed; feeling relieved; neat; tidy" },
        飽きっぽい: { 読み方: ['あきっぽい'], form: 'ィ形容詞', 意味: "easily bored; quick to lose interest" },
        内気な: { 読み方: ['うちき'], form: 'ナ形容詞', 意味: "shy; bashful; timid; reserved" },
        楽天的な: { 読み方: ['らくてんてき'], form: 'ナ形容詞', 意味: "optimistic" },
        照れ屋: { 読み方: ['てれや'], form: '名詞', 意味: "very shy person; bashful; easy to blush" },
        せっかちな: { 読み方: [''], form: 'せっかち', 意味: "hasty" },
        社交的: { 読み方: ['しゃこうてき'], form: 'ナ形容詞', 意味: "sociable" },
        のんびりした: { 読み方: [''], form: '副詞、スル動詞', 意味: "at leisure; in a carefree manner" },
        おおらか: { 読み方: [''], form: 'ナ形容詞', 意味: "big hearted" },
        積極的な: { 読み方: ['せっきょくてき'], form: 'ナ形容詞', 意味: "proactive; positive" },
        素直な: { 読み方: ['すなお'], form: 'ナ形容詞', 意味: "honest; upfront (about one's feelings)" },
        人見知りする: { 読み方: ['ひとみしり'], form: '名詞、スル動詞', 意味: "shyness; fear of strangers" },
        怒りっぽい: { 読み方: ['おこりっぽい'], form: 'ィ形容詞', 意味: "hot-headed; easily angered" },
        悲観的な: { 読み方: ['ひかんてき'], form: 'ナ形容詞', 意味: "pessimistic" },
        けちな: { 読み方: [''], form: 'ナ形容詞', 意味: "stingy" },
        頑固な: { 読み方: ['がんこ'], form: 'ナ形容詞', 意味: "stubborn; obstinate" },
        恥ずかしがり屋: { 読み方: ['恥ずかしがり屋'], form: '名詞', 意味: "shy; easily embarassed" },
    },

    kaku: {

        はじめて: { 読み方: ['初めて'], form: '副詞、の形容詞', 意味: "for the first time" },
        いしやま: { 読み方: ['石山'], form: '名字', 意味: "stone mountain" },
        しつれい: { 読み方: ['失礼'], form: 'スル動詞、ナ形容詞', 意味: "discourtesy; impoliteness" },
        もうす: { 読み方: ['申す'], form: '五段動詞、謙譲語', 意味: "humble form of 言う" },
        おねがいします: { 読み方: ['お願いします'], form: '表現', 意味: "please (Humble kenjougo)" },
        おしえる: { 読み方: ['教える'], form: '一段動詞、他動詞', 意味: "to teach; to inform" },
        まえ: { 読み方: ['前'], form: '名詞、ノ形容詞', 意味: "before; in front (of)" },
        りゅうがく: { 読み方: ['留学'], form: '名詞、スル動詞', 意味: "studying abroad" },
        ことし: { 読み方: ['今年'], form: '名詞、副詞', 意味: "this year" },
        みた: { 読み方: ['三田'], form: '名字', 意味: "three rice field" },
        おおい: { 読み方: ['多い'], form: 'イ形容詞', 意味: "many" },
        だいがくいん: { 読み方: ['大学院'], form: '名詞', 意味: "graduate school" },
        くん: { 読み方: ['君'], form: '接尾詞', 意味: "boy" },
        でんきこうがく: { 読み方: ['電気工学'], form: '名詞', 意味: "electrical engineering" },
        せんこう: { 読み方: ['専攻'], form: '名詞、スル動詞', 意味: "major subject; special study" },
        がくぶ: { 読み方: ['学部'], form: '名詞', 意味: "undergraduate" },
        じょうず: { 読み方: ['上手'], form: 'ナ形容詞', 意味: "skillful" },
        きみ: { 読み方: ['君'], form: '代名詞', 意味: "you" },
        こんど: { 読み方: ['今度'], form: '名詞、副詞', 意味: "one of these days; next time; this time" },
        とき: { 読み方: ['時'], form: '名詞', 意味: "time" },
        じつは: { 読み方: ['実は'], form: '表現', 意味: "actually; in fact; by the way; to tell you the truth" },
        ちゅうがく: { 読み方: ['中学'], form: '名詞', 意味: "middle school" },
        ぶんか: { 読み方: ['文化'], form: '名詞', 意味: "culture" },
        じょせい: { 読み方: ['女性'], form: '名詞', 意味: "woman; female" },
        かえる: { 読み方: ['帰る'], form: '五段動詞、自動詞', 意味: "to return; to come home" },
        とる: { 読み方: ['取る'], form: '五段動詞、他動詞', 意味: "to take" },
        うまれる: { 読み方: ['～で）生まれる'], form: '一段動詞、自動詞', 意味: "to be born (in/at~)" },
        わたし: { 読み方: ['私'], form: '代名詞', 意味: "I; me" },
        しごと: { 読み方: ['仕事'], form: '名詞', 意味: "work; job" },
        とまる: { 読み方: ['泊まる'], form: '五段動詞、自動詞', 意味: "to stay (over night)" },
        きにいる: { 読み方: ['（～が）気に入る'], form: '表現、五段動詞', 意味: "to like ~; to be fond (of~)" },
        あいだに: { 読み方: ['間に'], form: '副詞', 意味: "while; during (the time when)" },
        ところ: { 読み方: ['所'], form: '名詞', 意味: "place" },
        いえ: { 読み方: ['家'], form: '名詞', 意味: "house" },
        うち: { 読み方: ['家'], form: '名詞', 意味: "one's home" },
        でんわ: { 読み方: ['電話'], form: '名詞', 意味: "phone" },
        にっき: { 読み方: ['日記'], form: '名詞', 意味: "diary" },
        つく: { 読み方: ['（～に）着く'], form: '五段動詞、自動詞', 意味: "to arrive (at)" },
        おなじ: { 読み方: ['同じ'], form: '名詞', 意味: "same; equal; identical" },
        じぶん: { 読み方: ['自分'], form: '代名詞', 意味: "myself; oneself" },
        ちかい: { 読み方: ['近い'], form: 'イ形容詞', 意味: "near; close" },
        あるく: { 読み方: ['歩く'], form: '五段動詞、自動詞', 意味: "to walk" },
        だんせい: { 読み方: ['男性'], form: '名詞', 意味: "man; male" },
        きょねん: { 読み方: ['去年'], form: '名詞、副詞', 意味: "last year" },
        しかた: { 読み方: ['仕方'], form: '名詞', 意味: "way of doing something; method" },
        うつくしい: { 読み方: ['美しい'], form: 'イ形容詞', 意味: "beautiful" },
        ぶんぽう: { 読み方: ['文法'], form: '名詞', 意味: "grammar" },
        かんがえかた: { 読み方: ['考え方'], form: '名詞', 意味: "way of thinking" },

    },

    yomerebaii: {

        紹介:{ 読み方: ['しょうかい'], form: '名詞、スル動詞、ノ形容詞', 意味: "introduction" },
        宿題:{ 読み方: ['しゅくだい'], form: '名詞', 意味: "homework" },
        池田:{ 読み方: ['いけだ'], form: '名字', 意味: "pond + rice field" },
        友達:{ 読み方: ['ともだち'], form: '名詞', 意味: "friend" },
        趣味:{ 読み方: ['しゅみ'], form: '名詞', 意味: "hobby; pastime" },
        隣:{ 読み方: ['となり'], form: 'ノ形容詞、名詞', 意味: "next to; next door" },
        家族:{ 読み方: ['かぞく'], form: '名詞', 意味: "family; members of a family" },
        遊ぶ:{ 読み方: ['あそぶ'], form: '五段動詞、自動詞', 意味: "to play; to hang out" },
        知識:{ 読み方: ['ちしき'], form: '名詞', 意味: "knowledge; information" },
        豊富:{ 読み方: ['ほうふ'], form: 'ナ形容詞、名詞', 意味: "abundant; plentiful" },
        飛行機:{ 読み方: ['ひこうき'], form: '名詞', 意味: "airplane" },
        座る:{ 読み方: ['（～に）すわる'], form: '五段動詞、自動詞', 意味: "to sit（in/on～）" },
        卒業:{ 読み方: ['（～を）そつぎょう'], form: '名詞、スル動詞', 意味: "graduation; moving on (from)" },
        勤める:{ 読み方: ['（～に）つとめる'], form: '一段動詞、他動詞', 意味: "to work （for～）; to be employed （at～）" },
        休暇:{ 読み方: ['きゅうか'], form: '名詞', 意味: "vacation; absence (from work)" },
        京都:{ 読み方: ['きょうと'], form: '都市', 意味: "Kyoto (city, prefecture)\n京都市\n京都府" },
        育つ:{ 読み方: ['（～で）そだつ'], form: '五段動詞、自動詞', 意味: "to grow up（in～）" },
        一晩:{ 読み方: ['ひとばん'], form: '名詞、副詞', 意味: "one night; overnight" },
        両親:{ 読み方: ['りょうしん'], form: '名詞', 意味: "parents; both parents" },
        名刺:{ 読み方: ['めいし'], form: '名詞', 意味: "business card" },
        番号:{ 読み方: ['ばんごう'], form: '名刺', 意味: "number" },
        十数時間:{ 読み方: ['じゅうすうじかん'], form: '', 意味: "ten plus a few hours" },
        空港:{ 読み方: ['くうこう'], form: '名詞', 意味: "airport" },
        迎える:{ 読み方: ['むかえる'], form: '一段動詞、他動詞', 意味: "to welcome; to go out to meet; to greet" },
        呼ぶ:{ 読み方: ['（～を…で）よぶ'], form: '五段動詞、他動詞', 意味: "to call ～ by…" },
        時差ぼけ:{ 読み方: ['時差ボケ'], form: '名詞', 意味: "jet lag" },
        眠る:{ 読み方: ['ねむる'], form: '五段動詞、自動詞', 意味: "to sleep" },
        連れて:{ 読み方: ['つれて行く、つれてくる'], form: '', 意味: "to take someone to, to bring someone along" },
        結局:{ 読み方: ['けっきょく'], form: '副詞', 意味: "finally; in the end" },
        適当:{ 読み方: ['てきとう'], form: 'ナ形容詞', 意味: "appropriate; suitable" },
        引っ越す:{ 読み方: ['ひっこす'], form: '五段動詞、自動詞', 意味: "to move to a new place of residence" },
        若い:{ 読み方: ['わかい'], form: 'イ形容詞', 意味: "young" },
        お互い:{ 読み方: ['おたがい'], form: '名詞、ノ形容詞、副詞', 意味: "each other; one another" },
        娘:{ 読み方: ['むすめ'], form: '名詞', 意味: "daughter" },
        違う:{ 読み方: ['ちがう'], form: '五段動詞、自動詞', 意味: "to differ; to be different" },
        興味:{ 読み方: ['きょうみ'], form: '名詞', 意味: "interest (in something); curiosity (about something)" },

    },
}

export default unit1_1;