const unit2_1 = {
    tango: {
        法則: { 読み方: ['ほうそく'], form: '名詞', 意味: "rule; law" },
        仲間: { 読み方: ['なかま'], form: '名詞', 意味: "companion; friend" },
        以外: { 読み方: ['いがい'], form: '名詞、福祉', 意味: "except; other than; besides" },
        風景: { 読み方: ['ふうけい'], form: '名詞', 意味: "scenery" },
        社会学者: { 読み方: ['しゃかいがくしゃ'], form: '名詞', 意味: "sociologist" },
        公共: { 読み方: ['こうきょう'], form: '名詞', 意味: "public (facilities); communal" },
        電柱: { 読み方: ['でんちゅう'], form: '名詞', 意味: "utility pole; telephone pole" },
        映る: { 読み方: ['うつる'], form: '五段動詞、自動詞', 意味: "to be reflected; to be displayed (on a screen); to be projected" },
        きわめて: { 読み方: [''], form: '副詞', 意味: "extremeley" },
        信頼性: { 読み方: ['しんらいせい'], form: '名詞', 意味: "credibility; reliability" },
        通じる: { 読み方: ['つうじる'], form: '一段動詞、自動詞', 意味: "to apply; to lead; to get across" },
        満員電車: { 読み方: ['まんいんでんしゃ'], form: '名詞', 意味: "full-train" },
        家具: { 読み方: ['かぐ'], form: '名詞', 意味: "furniture" },
        植木鉢: { 読み方: ['うえきばち'], form: '名詞', 意味: "potted plant" },
        車両: { 読み方: ['しゃりょう'], form: '名詞', 意味: "wheeled vehicle" },
        感覚: { 読み方: ['かんかく'], form: '名詞、スル動詞', 意味: "sense; feeling; sensation" },
        平気: { 読み方: ['へいき'], form: 'ナ形容詞', 意味: "ok; all right" },
        化粧: { 読み方: ['けしょう'], form: '名詞、スル動詞', 意味: "make-up" },
        弁当: { 読み方: ['べんとう'], form: '名詞', 意味: "boxed lunch" },
        机: { 読み方: ['つくえ'], form: '名詞', 意味: "desk" },
        傍若無人: { 読み方: ['ぼうじゃくぶじん'], form: '名詞、ナ形容詞、ノ形容詞', 意味: "insolence; outrageous; arrogant" },
        謎: { 読み方: ['なぞ'], form: '名詞', 意味: "mystery" },
        解く: { 読み方: ['とく'], form: '五段動詞、他動詞', 意味: "to solve" },
        解ける: { 読み方: ['とける'], form: '一段動詞、自動詞', 意味: "to be solved" },
        勝手: { 読み方: ['かって'], form: 'ナ形容詞、名詞', 意味: "selfishness; one's own convenience" },
        全体: { 読み方: ['ぜんたい'], form: '名詞、副詞', 意味: "whole; entire; general" },
        全員: { 読み方: ['ぜんいん'], form: '名詞、副詞', 意味: "all members; everybody" },
        共有: { 読み方: ['きょうゆう'], form: '名詞、スル動詞', 意味: "sharing (e.g. a viewpoint), sharing (files)" },
        摩擦: { 読み方: ['まさつ'], form: '名詞、スル動詞', 意味: "friction; conflict" },
        迷惑: { 読み方: ['めいわく'], form: '名詞、ナ形容詞', 意味: "trouble; bother; annoyance; nuisance; inconvenience" },
        被害: { 読み方: ['ひがい'], form: '名詞', 意味: "damage; injury; harm" },
        及ぶ: { 読み方: ['およぶ'], form: '五段動詞、自動詞', 意味: "to reach" },
        限り: { 読み方: ['～かぎり'], form: '動詞＋限り', 意味: "as long as~" },
        みっともない: { 読み方: [''], form: 'イ形容詞', 意味: "disgraceful; embarassing; ugly" },
        不愉快: { 読み方: ['ふゆかい'], form: 'ナ形容詞', 意味: "unpleasant" },
    },

    kaku: {
        なかま: { 読み方: ['仲間'], form: '名詞', 意味: "companion; friend; comrade" },
        ふうけい: { 読み方: ['風景'], form: '名詞', 意味: "scenery" },
        しゃこうがくしゃ: { 読み方: ['社交学者'], form: '名詞', 意味: "sociologist" },
        こうきょう: { 読み方: ['公共'], form: '名詞', 意味: "public (facilities, service, etc.)" },
        よこ: { 読み方: ['横'], form: '名詞', 意味: "horizontal; side-to-side (as opposed to front-to-back)" },
        うつる: { 読み方: ['映る'], form: '五段動詞、自動詞', 意味: "to be reflected; to be projected; to be displayed" },
        しんらいせい: { 読み方: ['信頼性'], form: '名詞', 意味: "credibility; reliability" },
        ほうそく: { 読み方: ['法則'], form: '名詞', 意味: "rule; law" },
        つうじる: { 読み方: ['通じる'], form: '一段動詞、自動詞', 意味: "to apply; to lead; to get across" },
        まんいん: { 読み方: ['満員'], form: '名詞', 意味: "full house; no vacancy" },
        かぐ: { 読み方: ['家具'], form: '名詞', 意味: "furniture" },
        しゃりょう: { 読み方: ['車両'], form: '名詞', 意味: "railroad car; wheeled vehicle" },
        かんかく: { 読み方: ['感覚'], form: '名詞、スル動詞', 意味: "sense; sensation; feeling; intuition" },
        へいき: { 読み方: ['平気'], form: 'ナ形容詞', 意味: "all right; fine; okay" },
        つくえ: { 読み方: ['机'], form: '名詞', 意味: "desk" },
        なぞ: { 読み方: ['謎'], form: '名詞', 意味: "mystery" },
        とく: { 読み方: ['解く'], form: '五段動詞、他動詞', 意味: "to solve; to work out; to answer" },
        かって: { 読み方: ['勝手'], form: '名詞、ナ形容詞', 意味: "one's own convenience; one's way; selfishness" },
        ぜんいん: { 読み方: ['全員'], form: '名詞、副詞', 意味: "all members; whole crew; everyone" },
        きょうゆう: { 読み方: ['共有'], form: '名詞、スル動詞', 意味: "join ownership; sharing (e.g. a viewpoint; files)" },
        ちょくせつ: { 読み方: ['直接'], form: 'ナ形容詞、名詞', 意味: "direct; immediate; firsthand" },
        かぎり: { 読み方: ['限り'], form: '動詞＋～限り', 意味: "as long as~" },
    },

    yomerebaii: {
        電柱: { 読み方: ['でんちゅう'], form: '名詞', 意味: "utility pole; telephone pole" },
        植木鉢: { 読み方: ['うえきばち'], form: '名詞', 意味: "potted plant" },
        化粧: { 読み方: ['けしょう'], form: '名詞、スル動詞', 意味: "make-up" },
        弁当: { 読み方: ['べんとう'], form: '名詞', 意味: "boxed-lunch" },
        迷惑: { 読み方: ['めいわく'], form: '名詞、ナ形容詞', 意味: "trouble; bother; annoyance; inconvenience" },
        被害: { 読み方: ['ひがい'], form: '名詞', 意味: "damage; injury; harm" },
        及ぶ: { 読み方: ['およぶ'], form: '五段動詞、自動詞', 意味: "to reach" },
        不愉快: { 読み方: ['ふゆかい'], form: 'ナ形容詞', 意味: "unpleasant" },
    },
}

export default unit2_1;