const unit3_2 = {
    tango: {
        自販機: { 読み方: ['じはんき'], form: '名詞', 意味: "vending machine" },
        自動販売機: { 読み方: ['じどうはんばいき'], form: '名詞', 意味: "vending machine" },
        快適: { 読み方: ['かいてき'], form: 'ナ形容詞、名詞', 意味: "pleasant; comfortable" },
        引き換え: { 読み方: ['ひきかえ'], form: '名詞', 意味: "exchange; conversion" },
        悪化: { 読み方: ['あっか'], form: '名詞、スル動詞', 意味: "(suffer) deterioration; growing worse" },
        招く: { 読み方: ['まねく'], form: '五段動詞、他動詞', 意味: "to invite; to ask; to beckon" },
        防ぐ: { 読み方: ['ふせぐ'], form: '五段動詞、他動詞', 意味: "to defend against; to protect against; to prevent" },
        営業: { 読み方: ['えいぎょう'], form: '名詞、スル動詞', 意味: "business; trade; operations" },
        いまや: { 読み方: [''], form: '副詞', 意味: "now (in contrast to the past)" },
        手軽: { 読み方: ['てがる'], form: 'ナ形容詞', 意味: "easy; simple; light; cheap" },
        実現: { 読み方: ['じつげん'], form: '名詞、スル動詞', 意味: "implementation (e.g. of a system); realization" },
        手放す: { 読み方: ['てばなす'], form: '五段動詞、他動詞', 意味: "to let go of; to part with (e.g. a posession)" },
        注目: { 読み方: ['ちゅうもく'], form: '名詞、スル動詞', 意味: "notice; attention" },
        値する: { 読み方: ['～あたいする'], form: 'スル動詞（含まれチエル）、自動詞', 意味: "to be worthy of; to deserve" },
        失う: { 読み方: ['うしなう'], form: '五段動詞、他動詞', 意味: "to lose; to miss (a change, opportunity)" },
        対策: { 読み方: ['～たいさく'], form: '名詞', 意味: "counterplan; countermeasure; measures against~" },
        とどまる: { 読み方: [''], form: '五段動詞、自動詞', 意味: "to remain; to stay (in one place); to be limited to" },
        浅い: { 読み方: ['あさい'], form: 'イ形容詞', 意味: "shallow" },
        派: { 読み方: ['~は'], form: '名詞、接尾詞', 意味: "group; proponent of~" },
        別: { 読み方: ['～べつ'], form: '名詞、接尾詞', 意味: "by~ (e.g. 年齢別、色別);" },
        従う: { 読み方: ['したがう'], form: '五段動詞、自動詞', 意味: "to follow" },
        禁止: { 読み方: ['きんし'], form: '名詞、スル動詞', 意味: "prohibition; ban" },
        程度: { 読み方: ['ていど'], form: '名詞、副詞、接尾詞', 意味: "degree; amount" },
        尋ねる: { 読み方: ['たずねる'], form: '一段動詞、他動詞', 意味: "to ask; to enquire" },
        占める: { 読み方: ['しめる'], form: '一段動詞、他動詞', 意味: "to occupy; to hold" },
        今後: { 読み方: ['こんご'], form: '名詞、副詞', 意味: "from now on; hereafter" },
        次第: { 読み方: ['～しだい'], form: '名詞、接尾詞', 意味: "depending on~" },
        期待: { 読み方: ['きたい'], form: '名詞、スル動詞', 意味: "expectation; anticipation; hope" },
        活動家: { 読み方: ['かつどうか'], form: '名詞', 意味: "activist" },
        もったいない: { 読み方: [''], form: 'イ形容詞', 意味: "wasteful; a waste" },
        長年: { 読み方: ['ながねん'], form: '名詞、副詞', 意味: "many years; for years" },
        合言葉: { 読み方: ['あいことば'], form: '名詞', 意味: "catchphrase; slogan; password" },
        たった: { 読み方: ['たった～'], form: '副詞', 意味: "just~; only~" },
        破壊: { 読み方: ['はかい'], form: '名詞、スル動詞', 意味: "destruction [v. to destroy]" },
        資源: { 読み方: ['しげん'], form: '名詞', 意味: "resources" },
        無駄遣い: { 読み方: ['むだづかい'], form: '名詞、スル動詞', 意味: "waste (of money, time, etc.); wasteful spending" },
        再利用: { 読み方: ['さいりよう'], form: '名詞、スル動詞', 意味: "reuse; recycling" },
        実用的: { 読み方: ['じつようてき'], form: 'ナ形容詞', 意味: "practical; useful" },
        政府: { 読み方: ['せいふ'], form: '名詞', 意味: "government" },
        企業: { 読み方: ['きぎょう'], form: '名詞', 意味: "business; corporation" },
        面: { 読み方: ['めん'], form: '名詞', 意味: "aspect; face; side" },
        変化: { 読み方: ['へんか'], form: '名詞、スル動詞', 意味: "change; transformation; variety" },
        不可欠: { 読み方: ['ふかけつ'], form: 'ナ形容詞', 意味: "vital; essential; necessary" },
        市場: { 読み方: ['しじょう'], form: '名詞', 意味: "(town) market; (street) market" },
        価格: { 読み方: ['かかく'], form: '名詞', 意味: "price; value; cost" },
        植える: { 読み方: ['うえる'], form: '一段動詞、他動詞', 意味: "to plant; to grow; to raise" },
        燃料: { 読み方: ['ねんりょう'], form: '名詞', 意味: "fuel" },
        食糧: { 読み方: ['しょくりょう'], form: '名詞', 意味: "(staple) food; food (esp staple food such as rice or wheat)" },
        生活費: { 読み方: ['せいかつひ'], form: '名詞', 意味: "living expenses" },
        市民: { 読み方: ['しみん'], form: '名詞', 意味: "citizen" },
        望む: { 読み方: ['のぞむ'], form: '五段動詞、他動詞', 意味: "to desire; to wish for" },
    },

    kaku: {
        しんや: { 読み方: ['深夜'], form: '名詞、副詞', 意味: "late at night" },
        わり: { 読み方: ['割'], form: '接尾詞', 意味: "rate; ratio; proportion; profit; 10%" },
        おんすい: { 読み方: ['温水'], form: '名詞', 意味: "warm　water" },
        あっか: { 読み方: ['悪化'], form: '名詞、スル動詞', 意味: "growing worse; (suffer) deterioration" },
        まねく: { 読み方: ['招く'], form: '五段動詞、他動詞', 意味: "to invite; to ask; to beckcon" },
        ふせぐ: { 読み方: ['防ぐ'], form: '五段動詞、他動詞', 意味: "to defend against; to protect against; to prevent" },
        うけいれる: { 読み方: ['受け入れる'], form: '一段動詞、他動詞', 意味: "to accept; to receive; to agree" },
        えいぎょう: { 読み方: ['営業'], form: '名詞、スル動詞', 意味: "business; trade; operations" },
        たいはん: { 読み方: ['大半'], form: '名詞', 意味: "majority; more than half; most (of)" },
        てがる: { 読み方: ['手軽'], form: 'ナ形容詞', 意味: "easy; simple; cheap" },
        じつげん: { 読み方: ['実現'], form: '名詞、スル動詞', 意味: "implementation (e.g. of a system); realization" },
        ちゅうもく: { 読み方: ['注目'], form: '名詞、スル動詞', 意味: "notice; attention" },
        うしなう: { 読み方: ['失う'], form: '五段動詞、他動詞', 意味: "to lose; to miss (a change, opportunity)" },
        たいさく: { 読み方: ['～対策'], form: '名詞', 意味: "counterplan; countermeasure; measures against~" },
        ちいき: { 読み方: ['地域'], form: '名詞', 意味: "area; region" },
        あさい: { 読み方: ['浅い'], form: 'イ形容詞', 意味: "shallow" },
        せだい: { 読み方: ['世代'], form: '名詞', 意味: "generatin; the world; the age" },
        きたい: { 読み方: ['期待'], form: '名詞、スル動詞', 意味: "expectation; anticipation; hope" },
        かつどうか: { 読み方: ['活動家'], form: '名詞', 意味: "activist" },
        さいりよう: { 読み方: ['再利用'], form: '名詞、スル動詞', 意味: "reuse; recycling" },
        へんか: { 読み方: ['変化'], form: '名詞、スル動詞', 意味: "change; variation; transform" },
        せいかつひ: { 読み方: ['生活費'], form: '名詞', 意味: "living expenses" },
        しみん: { 読み方: ['市民'], form: '名詞', 意味: "citizen" },
    },

    yomerebaii: {
        我慢: { 読み方: ['がまん'], form: '名詞、スル動詞', 意味: "endurance; patience; perseverance; bearing (with something); self-control" },
        快適: { 読み方: ['かいてき'], form: 'ナ形容詞、名詞', 意味: "pleasant; agreeable; comfortable" },
        想定: { 読み方: ['そうてい'], form: '名詞、スル動詞', 意味: "hypothesis; assumption" },
        手放す: { 読み方: ['てばなす'], form: '五段動詞、他動詞', 意味: "to let go of; to release; to part with (e.g. a posession)" },
        値する: { 読み方: ['あたいする'], form: 'スル動詞（含まれている）、自動詞', 意味: "to be worth; to deserve" },
        普及: { 読み方: ['ふきゅう'], form: '名詞、スル動詞', 意味: "diffusion; spread; popularization; familiarization" },
        派: { 読み方: ['～は'], form: '名詞、接尾詞', 意味: "clique; group" },
        従う: { 読み方: ['したがう'], form: '五段動詞、自動詞', 意味: "to follow; to go alongside" },
        脱: { 読み方: ['だつ～'], form: '接頭辞', 意味: "de~ (indicating reversal, removal, etc.)" },
        程度: { 読み方: ['ていど'], form: '名詞', 意味: "degree; amount" },
        占める: { 読み方: ['しめる'], form: '一段動詞、他動詞', 意味: "to account for; to occupy" },
        輸送: { 読み方: ['ゆそう'], form: '名詞、スル動詞', 意味: "transport; transportation" },
        鐡道: { 読み方: ['てつどう'], form: '名詞', 意味: "railway; railroad" },
        次第: { 読み方: ['~しだい'], form: '名詞、接尾辞', 意味: "depending on~" },
        資源: { 読み方: ['しげん'], form: '名詞', 意味: "resources" },
        無駄: { 読み方: ['むだ'], form: '名詞、ナ形容詞', 意味: "futility; waste; uselessness; pointlessness" },
        無駄遣い: { 読み方: ['むだづかい'], form: '名詞、スル動詞', 意味: "waste (of money, time, etc.)" },
        政府: { 読み方: ['せいふ'], form: '名詞', 意味: "government" },
        面: { 読み方: ['めん'], form: '名詞', 意味: "face; aspect; side" },
        不可欠: { 読み方: ['ふかけつ'], form: 'ナ形容詞、名詞', 意味: "indespensable; essential" },
        燃料: { 読み方: ['ねんりょう'], form: '名詞', 意味: "fuel" },
    },
    
}

export default unit3_2;