const unit3_1 = {
    tango: {
        地球温暖化: { 読み方: ['ちきゅうおんだんか'], form: '名詞', 意味: "global warming" },
        対策: { 読み方: ['～たいさく'], form: '名詞', 意味: "counterplan; countermeasure; measures against~" },
        排出: { 読み方: ['はいしゅつ'], form: '名詞、スル動詞', 意味: "emission (e.g. of CO2, etc.)" },
        二酸化炭素: { 読み方: ['にさんかたんそ'], form: '名詞', 意味: "carbon dioxide" },
        水道: { 読み方: ['すいどう'], form: '名詞', 意味: "water supply" },
        暖房: { 読み方: ['だんぼう'], form: '名詞、スル動詞', 意味: "(indoor) heating" },
        冷房: { 読み方: ['れいぼう'], form: '名詞、スル動詞', 意味: "air conditioning; air cooling" },
        利用: { 読み方: ['りよう'], form: '名詞、スル動詞', 意味: "use; utilization" },
        お風呂: { 読み方: ['おふろ'], form: '名詞', 意味: "bath" },
        洗濯: { 読み方: ['せんたく'], form: '名詞、スル動詞', 意味: "washsing; laundry" },
        入浴: { 読み方: ['にゅうよく'], form: '名詞', 意味: "bathing; to bathe; to enter a bath" },
        炊飯器: { 読み方: ['すいはんき'], form: '名詞', 意味: "rice cooker" },
        保温: { 読み方: ['ほおん'], form: '名詞、スル動詞', 意味: "heat-retention; heat insulation" },
        冷蔵庫: { 読み方: ['れいぞうこ'], form: '名詞', 意味: "refrigerator; fridge" },
        詰め込む: { 読み方: ['つめこむ'], form: '五段動詞、他動詞', 意味: "to cram; to stuff; to pack" },
        壁: { 読み方: ['かべ'], form: '名詞', 意味: "wall" },
        適切: { 読み方: ['てきせつ'], form: 'ナ形容詞', 意味: "appropriate; suitable" },
        消す: { 読み方: ['けす'], form: '五段動詞、他動詞', 意味: "to erase; to turn off (power); to switch off" },
        節約: { 読み方: ['せつやく'], form: '名詞、スル動詞', 意味: "economising; saving" },
        削減: { 読み方: ['さくげん'], form: '名詞、スル動詞', 意味: "cut; reduction" },
        環境: { 読み方: ['かんきょう'], form: '名詞', 意味: "environment; circumstance" },
        活動: { 読み方: ['かつどう'], form: '名詞、スル動詞', 意味: "activity (of a person, organization, animal, volcano, etc.)" },
        購入: { 読み方: ['こうにゅう'], form: '名詞、スル動詞', 意味: "purchase; buy" },
        買い物袋: { 読み方: ['かいものぶくろ'], form: '名詞', 意味: "shopping bag" },
        洗剤: { 読み方: ['せんざい'], form: '名詞', 意味: "detergent; cleanser; cleaning agent" },
        中身: { 読み方: ['なかみ'], form: '名詞', 意味: "contents; interior; filling" },
        電球: { 読み方: ['でんきゅう'], form: '名詞', 意味: "light bulb" },
        切れる: { 読み方: ['きれる'], form: '一段動詞、自動詞', 意味: "to wear out; to be burned out" },
        取り替える: { 読み方: ['とりかえる'], form: '一段動詞、他動詞', 意味: "to exchange; to replace" },
        繰り返し: { 読み方: ['くりかえし'], form: '名詞、副詞', 意味: "repetition; repeatedly" },
        瓶: { 読み方: ['びん、ビン'], form: '名詞', 意味: "bottle; jar" },
        製品: { 読み方: ['せいひん'], form: '名詞', 意味: "product; manufactured goods" },
        家電製品: { 読み方: ['かでんせいひん'], form: '名詞', 意味: "consumer electronics; home appliances" },
        心がける: { 読み方: ['こころがける'], form: '一段動詞、他動詞', 意味: "to keep in mind; to bear in mind; to endeavor; to try (to~)" },
        取り組み: { 読み方: ['とりくみ'], form: '名詞', 意味: "effort; approach; initiative" },
        積み重ねる: { 読み方: ['つみかさねる'], form: '一段動詞、他動詞', 意味: "to pile up; to accumulate" },
        一般廃棄物: { 読み方: ['いっぱんはいきぶつ'], form: '名詞', 意味: "domestic waste" },
        給湯: { 読み方: ['きゅうとう'], form: '名詞、スル動詞', 意味: "hot-water supply" },
        厨房: { 読み方: ['ちゅうぼう'], form: '名詞', 意味: "kitchen" },
        動力: { 読み方: ['どうりょく'], form: '名詞', 意味: "motor; power" },
        自家用乗用車: { 読み方: ['じかようじょうようしゃ'], form: '名詞', 意味: "private (passenger) car" },
        残り湯: { 読み方: ['のこりゆ'], form: '名詞', 意味: "leftover bath water" },
        使いまわす: { 読み方: ['つかいまわす'], form: '五段動詞', 意味: "to recycle; to use the same thing for more than one purpose" },
        間隔: { 読み方: ['かんかく'], form: '名詞', 意味: "interval; sapce between two objects" },
        温水洗浄便座: { 読み方: ['おんすいせんじょうべんざ'], form: '名詞', 意味: "bidet toilet seat" },
        炎: { 読み方: ['ほのお'], form: '名詞', 意味: "glame; fire" },
        はみ出す: { 読み方: ['はみだす'], form: '五段動詞、自動詞', 意味: "to stick out; (flame) come out/up (the side of a pot)" },
        なべ底: { 読み方: ['なべぞこ'], form: '名詞', 意味: "the (inner) bottom of a pan" },
        調節: { 読み方: ['ちょうせつ'], form: '名詞、スル動詞', 意味: "adjustment; regulation" },
        設置: { 読み方: ['せっち'], form: '名詞、スル動詞', 意味: "installation (of a machine or equipment)" },
        主電源: { 読み方: ['しゅでんげん'], form: '名詞', 意味: "main power supply" },
        こまめ: { 読み方: [''], form: 'ナ形容詞', 意味: "frequent (e.g. checking); diligent; earnest" },
        こまめに: { 読み方: [''], form: '副詞', 意味: "frequently" },
        待機電力: { 読み方: ['たいきでんりょく'], form: '名詞', 意味: "standby power" },
        設定温度: { 読み方: ['せっていおんど'], form: '名詞', 意味: "preset temperature" },
        宣言: { 読み方: ['せんげん'], form: '名詞、スル動詞', 意味: "declaration" },
        推進: { 読み方: ['すいしん'], form: '名詞、スル動詞', 意味: "promotion; propulsion" },
        環境省: { 読み方: ['かんきょうしょう'], form: '名詞', 意味: "Ministry of the Environment" },
        防止: { 読み方: ['ぼうし'], form: '名詞、スル動詞', 意味: "prevention" },
        原則: { 読み方: ['げんそく'], form: '名詞', 意味: "general rule; principle" },
        包装: { 読み方: ['ほうそう'], form: '名詞、スル動詞', 意味: "package; wrapping" },
        詰め替える: { 読み方: ['つめかえる'], form: '一段動詞、他動詞', 意味: "to repack; to refill" },
        電球型蛍光ランプ: { 読み方: ['でんきゅうがたけいこうランプ'], form: '名詞', 意味: "compact fluorescent lamp (CFL)" },
        エネルギー効率: { 読み方: ['エネルギーこうりつ'], form: '名詞', 意味: "energy efficiency" },
        燃費: { 読み方: ['ねんぴ'], form: '名詞', 意味: "fuel consumption; gas mileage" },
        鉄道: { 読み方: ['てつどう'], form: '名詞', 意味: "railroad; rail" },
        配慮: { 読み方: ['はいりょ'], form: '名詞、スル動詞', 意味: "attention; consideration" },
        参考: { 読み方: ['さんこう'], form: '名詞', 意味: "reference" },
    },

    kaku: {
        ちきゅう: { 読み方: ['地球'], form: '名詞', 意味: "Earth; the globe" },
        おんだんか: { 読み方: ['温暖化'], form: '名詞、スル動詞', 意味: "warming" },
        りよう: { 読み方: ['利用'], form: '名詞、スル動詞', 意味: "use; utilization" },
        ふろ: { 読み方: ['風呂'], form: '名詞', 意味: "bath" },
        にゅうよく: { 読み方: ['入浴'], form: '名詞、スル動詞', 意味: "bathing; to take a bath; to enter a bath" },
        ほおん: { 読み方: ['保温'], form: '名詞、スル動詞', 意味: "retaining heat; heat insulation" },
        つめこむ: { 読み方: ['詰め込む'], form: '五段動詞、他動詞', 意味: "to cram; to stuff; to pack" },
        てきせつ: { 読み方: ['適切'], form: 'ナ形容詞', 意味: "appropriate; suitable" },
        せつやく: { 読み方: ['節約'], form: '名詞、スル動詞', 意味: "economising; saving" },
        かんきょう: { 読み方: ['環境'], form: '名詞', 意味: "environment" },
        ぼうし: { 読み方: ['防止'], form: '名詞、スル動詞', 意味: "prevention" },
        かつどう: { 読み方: ['活動'], form: '名詞、スル動詞', 意味: "activity" },
        ちょうせつ: { 読み方: ['調節'], form: '名詞、スル動詞', 意味: "regulation; adjustment; control" },
        せっち: { 読み方: ['設置'], form: '名詞、スル動詞', 意味: "installation" },
        でんきゅう: { 読み方: ['電球'], form: '名詞', 意味: "light bulb" },
        かでんせいひん: { 読み方: ['家電製品'], form: '名詞', 意味: "consumer electronics; home appliances" },
    },

    yomerebaii: {
        排出量: { 読み方: ['はいしゅつりょう'], form: '名詞', 意味: "amount of emission" },
        二酸化炭素: { 読み方: ['にさんかたんそ'], form: '名詞', 意味: "carbon dioxide" },
        冷房: { 読み方: ['れいぼう'], form: '名詞、スル動詞', 意味: "air conditioning; air cooling" },
        暖房: { 読み方: ['だんぼう'], form: '名詞、スル動詞', 意味: "(indoor) heating" },
        洗濯: { 読み方: ['せんたく'], form: '名詞、スル動詞', 意味: "laundry" },
        冷蔵庫: { 読み方: ['れいぞうこ'], form: '名詞', 意味: "refrigerator" },
        削減: { 読み方: ['さくげん'], form: '名詞、スル動詞', 意味: "reduction" },
        間隔: { 読み方: ['かんかく'], form: '名詞', 意味: "space; interval" },
        炎: { 読み方: ['ほのお'], form: '名詞', 意味: "fire; flame" },
        設定温度: { 読み方: ['せっていおんど'], form: '名詞', 意味: "preset temperature" },
        推進: { 読み方: ['すいしん'], form: '名詞、スル動詞', 意味: "promotion; propulsion" },
        購入: { 読み方: ['こうにゅう'], form: '名詞、スル動詞', 意味: "purchase; buy" },
        洗剤: { 読み方: ['せんざい'], form: '名詞', 意味: "detergent" },
        燃費: { 読み方: ['ねんぴ'], form: '名詞', 意味: "fuel consumption; gas mileage" },
        鉄道: { 読み方: ['てつどう'], form: '名詞', 意味: "rail; railroad" },
        参考: { 読み方: ['さんこう'], form: '名詞', 意味: "reference" },
    },
}

export default unit3_1;