const unit1_2 = {
    tango: {
        姿: { 読み方: ['すがた'], form: '名詞', 意味: "figure; form; shape; appearance" },
        友人: { 読み方: ['ゆうじん'], form: '名詞', 意味: "friend" },
        付き合う: { 読み方: ['つきあう'], form: '五段動詞、自動詞', 意味: "to associate with; to keep company with" },
        はっとする: { 読み方: [''], form: 'スル動詞', 意味: "to suddenly realize/remember; to be startled" },
        部分: { 読み方: ['ぶぶん'], form: '名詞', 意味: "portion; part" },
        しゃべる: { 読み方: [''], form: '五段動詞、自動詞', 意味: "to talk; to chatter" },
        趣味: { 読み方: ['しゅみ'], form: '名詞', 意味: "hobby" },
        オープンにする: { 読み方: [''], form: '', 意味: "to be open" },
        態度: { 読み方: ['たいど'], form: '名詞', 意味: "attitude; manner" },
        パーソナリティー: { 読み方: [''], form: '名詞', 意味: "personality" },
        自分自身: { 読み方: ['じぶんじしん'], form: '名詞', 意味: "oneself" },
        他人: { 読み方: ['たにん'], form: '名詞', 意味: "others; other people" },
        打ち明ける: { 読み方: ['うちあける'], form: '一段動詞、他動詞', 意味: "to confide; to disclose; to speak frankly" },
        自己開示: { 読み方: ['じこかいじ'], form: '名詞、スル動詞', 意味: "self disclosure; information of oneself that is public and easily shared" },
        米国人: { 読み方: ['べいこくじん'], form: '名詞', 意味: "American people" },
        留学生: { 読み方: ['りゅうがくせい'], form: '名詞', 意味: "exchange student" },
        ディスカッションする: { 読み方: [''], form: '名詞、スル動詞', 意味: "discussion" },
        恋人: { 読み方: ['こいびと'], form: '名詞', 意味: "lover; boyfriend; girlfriend" },
        問い掛け: { 読み方: ['といかけ'], form: '名詞', 意味: "query; question" },
        即座に: { 読み方: ['そくざ'], form: '副詞', 意味: "immediately; instantly" },
        手を挙げる: { 読み方: ['てをあげる'], form: '一段動詞、他動詞', 意味: "to raise one's hand" },
        恥ずかしい: { 読み方: ['はずかしい'], form: 'イ形容詞', 意味: "embarassing" },
        向く: { 読み方: ['むく'], form: '五段動詞、他動詞、自動詞', 意味: "to turn towards; to look (up, down, etc.)" },
        曖昧な: { 読み方: ['あいまい'], form: 'ナ形容詞', 意味: "vague" },
        笑う: { 読み方: ['わらう'], form: '五段動詞、自動詞', 意味: "to laugh; to smile" },
        たまる: { 読み方: [''], form: '五段動詞、自動詞', 意味: "to pile up; accumulate" },
        ストレスがたまる: { 読み方: [''], form: '五段動詞、自動詞', 意味: "to get stressed out" },
        場: { 読み方: ['ば'], form: '名詞', 意味: "place; field; scene" },
        異なる: { 読み方: ['ことなる'], form: '五段動詞、自動詞', 意味: "to differ" },
        窓: { 読み方: ['まど'], form: '名詞', 意味: "window" },
        によって: { 読み方: [''], form: '表現', 意味: "according to; by (means of); due to; because of" },
        提案する: { 読み方: ['ていあん'], form: '名詞、スル動詞', 意味: "proposal; suggestion" },
        組み合わせる: { 読み方: ['くみあわせる'], form: '一段動詞、他動詞', 意味: "to combine" },
        図: { 読み方: ['ず'], form: '名詞', 意味: "drawing; picture; diagram" },
        似る: { 読み方: ['（～に）にる'], form: '一段動詞、自動詞', 意味: "to resemble; be similar" },
        縦軸: { 読み方: ['たてじく'], form: '名詞', 意味: "vertical axis" },
        横軸: { 読み方: ['よこじく'], form: '名詞', 意味: "horizontal axis" },
        区切る: { 読み方: ['くぎる'], form: '五段動詞、他動詞', 意味: "to divide (an area)" },
        もしも: { 読み方: [''], form: '副詞', 意味: "if" },
        場合: { 読み方: ['ばあい'], form: '名詞', 意味: "case; situation" },
        例えば: { 読み方: ['たとえば'], form: '副詞', 意味: "for example" },
        比べる: { 読み方: ['（～に）くらべる'], form: '一段動詞、他動詞', 意味: "to compare" },
        違い: { 読み方: ['ちがい'], form: '名詞', 意味: "difference" },
        お互い: { 読み方: ['おたがい'], form: '名詞、副詞', 意味: "each other" },
        ギャップ: { 読み方: [''], form: '名詞', 意味: "gap" },
        生み出す: { 読み方: ['うみだす'], form: '五段動詞、他動詞', 意味: "to create, produce, generate" },
        なおさら: { 読み方: [''], form: '副詞', 意味: "all the more" },
        印象: { 読み方: ['いんしょう'], form: '名詞、スル動詞', 意味: "impression" },
        与える: { 読み方: ['あたえる'], form: '一段動詞、他動詞', 意味: "to give (esp. to someone of lower status" },
        発想する: { 読み方: ['はっそう'], form: '名詞、スル動詞', 意味: "idea; to conceive of" },
        分かち合う: { 読み方: ['わかちあう'], form: '五段動詞、他動詞', 意味: "to share （＝分け合う）" },
        公的な: { 読み方: ['こうてき'], form: 'ナ形容詞', 意味: "public" },
        私的な: { 読み方: ['してき'], form: 'ナ形容詞', 意味: "private" },
        もどかしい: { 読み方: [''], form: 'イ形容詞', 意味: "frustrating" },
        こうした: { 読み方: [''], form: '表現', 意味: "these~" },
        人間: { 読み方: ['にんげん'], form: '名詞', 意味: "human" },
        状況: { 読み方: ['じょうきょう'], form: '名詞', 意味: "situation; circumstances" },
        変化する: { 読み方: ['へんか'], form: '名詞、スル動詞', 意味: "change; variation; transform" },
        それぞれ: { 読み方: [''], form: '名詞、福祉', 意味: "each" },
        心に留める: { 読み方: ['こころにとめる'], form: '表現、一段動詞', 意味: "to bear/keep in mind" },
        必要な: { 読み方: ['ひつよう'], form: 'ナ形容詞', 意味: "necessary" },
    },


    kaku: {
        まど: { 読み方: ['窓'], form: '名詞', 意味: "window" },
        くみあわせる: { 読み方: ['組み合わせる'], form: '一段動詞、他動詞', 意味: "to join together; to combine" },
        にる: { 読み方: ['似る'], form: '一段動詞、自動詞', 意味: "to resemble; to be similar" },
        くぎる: { 読み方: ['区切る'], form: '五段動詞、他動詞', 意味: "to divide (an area)" },
        たとえば: { 読み方: ['例えば'], form: '副詞', 意味: "for example" },
        ばあい: { 読み方: ['場合'], form: '名詞', 意味: "case; situation" },
        おたがい: { 読み方: ['お互い'], form: '名詞、副詞', 意味: "each other; one another" },
        あたえる: { 読み方: ['与える'], form: '一段動詞、他動詞', 意味: "to give (esp. to someone of lower status)" },
        こうてき: { 読み方: ['公的'], form: 'ナ形容詞', 意味: "public" },
        してき: { 読み方: ['私的'], form: 'ナ形容詞', 意味: "private" },
        にんげん: { 読み方: ['人間'], form: '名詞', 意味: "human being" },
        ばめん: { 読み方: ['場面'], form: '名詞', 意味: "scene; setting; place (where something happens)" },
        ひつよう: { 読み方: ['必要'], form: 'ナ形容詞', 意味: "necessary" },
        //: { 読み方: [''], form: '', 意味: "" },
    },

    yomerebaii: {
        提案: { 読み方: ['ていあん'], form: '名詞、スル動詞', 意味: "to propose; suggestion" },
        縦軸: { 読み方: ['たてじく'], form: '名詞', 意味: "vertical axis" },
        横軸: { 読み方: ['よこじく'], form: '名詞', 意味: "horizontal axis" },
        印象: { 読み方: ['いんしょう'], form: '名詞、スル動詞', 意味: "impression" },
        発想: { 読み方: ['はっそう'], form: '名詞、スル動詞', 意味: "idea; conception" },
        状況: { 読み方: ['じょうきょう'], form: '名詞', 意味: "situation; circumstances" },
        分かち合う: { 読み方: ['わかちあう'], form: '五段動詞、他動詞', 意味: "to share" },
        留める: { 読み方: ['(心に）とめる'], form: '一段動詞、他動詞', 意味: "to bear in mind" },
        //: { 読み方: [''], form: '', 意味: "" },
        
    },
}

export default unit1_2;