const unit4_1 = {
    tango: {
        天井裏: { 読み方: ['てんじょううら'], form: '名詞', 意味: "above the ceiling; attic (＝屋根裏)" },
        小人: { 読み方: ['こびと'], form: '名詞', 意味: "small person" },
        元旦: { 読み方: ['がんたん'], form: '名詞', 意味: "New Year's Day; New Year's morning" },
        いったい: { 読み方: [''], form: '副詞', 意味: "(what) the heck; ... on earth; ... in the world" },
        不機嫌: { 読み方: ['ふきげん'], form: 'ナ形容詞', 意味: "bad mood; cranky; grumpy" },
        振る: { 読み方: ['ふる'], form: '五段動詞、他動詞', 意味: "to shake; to swing; to wave; to turn down (somebody)" },
        懐中電灯: { 読み方: ['かいちゅうでんとう'], form: '名詞', 意味: "flashlight" },
        のぞく: { 読み方: [''], form: '五段動詞、他動詞', 意味: "to peek; to peep" },
        押し入れ: { 読み方: ['おしいれ'], form: '名詞', 意味: "(Japanese) closet" },
        段: { 読み方: ['だん'], form: '名詞', 意味: "shelf; tier; step" },
        板: { 読み方: ['いた'], form: '名詞', 意味: "board; plank" },
        どかす: { 読み方: [''], form: '五段動詞、他動詞', 意味: "to remove; to move out of the way" },
        明かり: { 読み方: ['あかり'], form: '名詞', 意味: "light; illumination; glow; gleam; lamp" },
        ぐるりと: { 読み方: [''], form: '副詞', 意味: "around; surrounding; turning around; going around" },
        照らす: { 読み方: ['てらす'], form: '五段動詞、他動詞', 意味: "to shine on; to illuminate" },
        怒鳴る: { 読み方: ['どなる'], form: '五段動詞、自動詞', 意味: "to shout (in anger); to yell" },
        ちゃんと: { 読み方: [''], form: '副詞', 意味: "neatly; regularly; properly; without failt; diligently" },
        姿: { 読み方: ['すがた'], form: '名詞', 意味: "figure; form; shape; appearance" },
        ぐっすり: { 読み方: [''], form: '副詞', 意味: "fast (asleep); soundly (sleeping); deeply (sleep)" },
        しつこく: { 読み方: [''], form: '副詞', 意味: "persistently" },
        じっと: { 読み方: [''], form: '副詞', 意味: "hard (look); with a fixed gaze" },
        気味が悪い: { 読み方: ['きみがわるい'], form: '表現、イ形容詞', 意味: "creepy (feeling); uneasy (feeling); scary" },
        認める: { 読み方: ['みとめる'], form: '一段動詞、他動詞', 意味: "to recognize; to notice; to approve" },
        身長: { 読み方: ['しんちょう'], form: '名詞', 意味: "height (of body); stature" },
        ばかり: { 読み方: ['～ばかり'], form: '助詞', 意味: "about~; approximately~;" },
        そっくり: { 読み方: [''], form: 'ナ形容詞', 意味: "exactly like; just like; spitting image of" },
        尻尾: { 読み方: ['しっぽ'], form: '名詞', 意味: "tail (animal)" },
        ぞっと: { 読み方: [''], form: '副詞、スル動詞', 意味: "shuddering; shivering; trembling; to get chills" },
        馬鹿やろう: { 読み方: ['ばかやろう'], form: '名詞', 意味: "goddamn idiot; moron（＝馬鹿野郎）" },
        氷: { 読み方: ['こおり'], form: '名詞', 意味: "ice" },
        かたまり: { 読み方: [''], form: '名詞', 意味: "block; mass" },
        硬い: { 読み方: ['かたい'], form: 'イ形容詞', 意味: "hard; tough; obstinate" },
        元に戻す: { 読み方: ['もとにもどす'], form: '表現、五段動詞', 意味: "to put ~ back into place; to go back to the start; to reset; to return to the point (of a discussion)" },
        喉が渇く: { 読み方: ['のどがかわく'], form: '表現、五段動詞', 意味: "to be thirsty" },
        ひどく: { 読み方: [''], form: '副詞', 意味: "severely; badly; extremely; very much" },
        だいたい: { 読み方: [''], form: '副詞', 意味: "in the first place; first and foremost（＝そもそも）" },
        ホルモン剤: { 読み方: ['ほるもんざい'], form: '名詞', 意味: "hormonal drug" },
        ろくでもない: { 読み方: [''], form: '表現、イ形容詞', 意味: "not good at all; lousy; good-for-nothing; worthless" },
        顔つき: { 読み方: ['かおつき'], form: '名詞', 意味: "(outward) looks; face; expression; features" },
        ぶち: { 読み方: [''], form: '名詞', 意味: "dapple; spot" },
        ひるむ: { 読み方: [''], form: '五段動詞、自動詞', 意味: "to falter; to flinch (from); to recoil; to be intimidated; to hesitate" },
        凍てつく: { 読み方: ['いてつく'], form: '五段動詞、自動詞', 意味: "to freeze（＝凍り付く・凍る）" },
    },

    kaku: {
        うら: { 読み方: ['裏'], form: '名詞', 意味: "opposite side; other side; reverse side" },
        つま: { 読み方: ['妻'], form: '名詞', 意味: "wife" },
        ふる: { 読み方: ['振る'], form: '五段動詞、他動詞', 意味: "to shake; to wave; to swing; to turn down (someone); to reject" },
        だん: { 読み方: ['段'], form: '名詞', 意味: "step; stair; (flight of) steps" },
        いた: { 読み方: ['板'], form: '名詞', 意味: "board; plank" },
        まい: { 読み方: ['枚'], form: '助数詞', 意味: "counter for flat objects (e.g. sheets of paper)" },
        てらす: { 読み方: ['照らす'], form: '五段動詞、他動詞', 意味: "to shine on; to illuminate" },
        ねむる: { 読み方: ['眠る'], form: '五段動詞、自動詞', 意味: "to sleep" },
        きみがわるい: { 読み方: ['君味が悪い'], form: '表現、イ形容詞', 意味: "creepy (feeling); uneasy (feeling); scary" },
        しんちょう: { 読み方: ['身長'], form: '名詞', 意味: "(one's) height; stature" },
        やね: { 読み方: ['屋根'], form: '名詞', 意味: "roof" },
        こおり: { 読み方: ['氷'], form: '名詞', 意味: "ice" },
        もどる: { 読み方: ['戻る'], form: '五段動詞、自動詞', 意味: "to return; to turn back; to rebound; to spring back" },
        もどす: { 読み方: ['戻す'], form: '五段動詞、他動詞', 意味: "to put back; to return; to give back; to restore (to a previous state)" },
    },

    yomerebaii: {
        正月: { 読み方: ['しょうがつ'], form: '名詞', 意味: "New Year (esp. first three days); first month of the year; Japanese New Year" },
        元旦: { 読み方: ['がんたん'], form: '名詞', 意味: "New Year's Day; New Year's morning" },
        不機嫌: { 読み方: ['ふきげん'], form: 'ナ形容詞', 意味: "bad mood; cranky; grumpy" },
        押し入れ: { 読み方: ['おしいれ'], form: '名詞', 意味: "(Japanese) closet" },
        怒鳴る: { 読み方: ['どなる'], form: '五段動詞、自動詞', 意味: "to shout (in anger); to yell" },
        姿: { 読み方: ['すがた'], form: '名詞', 意味: "shape; form" },
        認める: { 読み方: ['みとめる'], form: '一段動詞、他動詞', 意味: "to recognize; to notice; to approve; to accept" },
        硬い: { 読み方: ['かたい'], form: 'ィ形容詞', 意味: "hard; solid; obstinate" },
    },
}

export default unit4_1;