const unit4_2 = {
    tango: {
        夕方: { 読み方: ['ゆうがた'], form: '名詞、副詞', 意味: "evening; dusk" },
        時刻: { 読み方: ['じこく'], form: '名詞', 意味: "time; favourable time; opportunity; chance" },
        不幸: { 読み方: ['ふこう'], form: '名詞、ナ形容詞', 意味: "misfortunate; unhappiness; death (usu. of a relative)" },
        ターミナル駅: { 読み方: ['ターミナルえき'], form: '名詞', 意味: "terminal station" },
        多少: { 読み方: ['たしょう'], form: '副詞', 意味: "a little; some; somewhat; slightly; to some degree" },
        余裕: { 読み方: ['よゆう'], form: '名詞', 意味: "surplus; margin; flexibility; leeway; have a time (space) to spare" },
        停留所: { 読み方: ['ていりゅうじょ'], form: '名詞', 意味: "(a bus) stop" },
        制服: { 読み方: ['せいふく'], form: '名詞', 意味: "uniform" },
        姿: { 読み方: ['~すがた'], form: '名詞、接尾辞', 意味: "dressing in~, in [clothes]" },
        乗り込む: { 読み方: ['のりこむ'], form: '五段動詞、自動詞', 意味: "to board; to get on; to embark on" },
        悩む: { 読み方: ['なやむ'], form: '五段動詞', 意味: "to be worried; to be troubled" },
        席を立つ: { 読み方: ['せきをたつ'], form: '表現', 意味: "to leave one's seat" },
        素直に: { 読み方: ['すなおに'], form: '副詞', 意味: "agreeably" },
        近辺: { 読み方: ['きんぺん'], form: '名詞', 意味: "vicinity; the area around~" },
        罪悪感: { 読み方: ['ざいあくかん'], form: '名詞', 意味: "feeling of guilt" },
        貼る: { 読み方: ['はる'], form: '五段動詞、他動詞', 意味: "to stick; to paste" },
        広告: { 読み方: ['こうこく'], form: '名詞', 意味: "advertisement" },
        眺める: { 読み方: ['ながめる'], form: '一段動詞、他動詞', 意味: "to look at; to gaze at; to watch; to stare at; to admire (e.g. the scenery)" },
        不意: { 読み方: ['ふい'], form: 'ナ形容詞', 意味: "sudden; abrupt" },
        声がする: { 読み方: ['こえがする'], form: '表現', 意味: "to speak; to hear a voice" },
        穏やか: { 読み方: ['おだやか'], form: 'ナ形容詞', 意味: "calm; peaceful" },
        響く: { 読み方: ['ひびく'], form: '五段動詞、自動詞', 意味: "to echo; to resound; to be heard far away; to have an effect" },
        人掛け: { 読み方: ['～にんがけ'], form: '名詞、接尾辞', 意味: "[# of people]-seat" },
        老女: { 読み方: ['ろうじょ'], form: '名詞', 意味: "elderly woman" },
        握る: { 読み方: ['にぎる'], form: '五段動詞、他動詞', 意味: "to clasp; to grasp; to form (with one's hands); to press into shape" },
        戸惑う: { 読み方: ['とまどう'], form: '五段動詞、自動詞', 意味: "to be bewildered; to be perplexed; to be confused" },
        曖昧: { 読み方: ['あいまい'], form: 'ナ形容詞', 意味: "vague; ambiguous; unclear" },
        頷く: { 読み方: ['うなずく'], form: '五段動詞、自動詞', 意味: "to nod; to bow one's head in assent" },
        食料品売り場: { 読み方: ['しょくりょうひんうりば'], form: '名詞', 意味: "selling area for foodstuff/groceries" },
        単位: { 読み方: ['たんい'], form: '名詞', 意味: "unit; denomination" },
        もしかしたら: { 読み方: [''], form: '表現、副詞', 意味: "by any chance; by some chance; perhaps" },
        ビニール袋: { 読み方: ['ビニールぶくろ'], form: '名詞', 意味: "plastic bag" },
        際: { 読み方: ['～さい'], form: '副詞、名詞', 意味: "on the occasion of; when~（＝～時）" },
        あまりにも: { 読み方: [''], form: '副詞', 意味: "too~; too much; excessive" },
        視線: { 読み方: ['しせん'], form: '名詞', 意味: "look; glance; one's line of sight" },
        地方都市: { 読み方: ['ちほうとし'], form: '名詞', 意味: "provincial city; suburban city; regional towns and cities" },
        気楽: { 読み方: ['きらく'], form: 'ナ形容詞', 意味: "carefree; comfortable; at ease; easygoing" },
        日々: { 読み方: ['日々'], form: '名詞、副詞', 意味: "every day; daily; day after day; days (e.g. good old days)" },
        ためらう: { 読み方: [''], form: '五段動詞、自動詞', 意味: "to hesitate; to waver" },
        なんとか: { 読み方: [''], form: '副詞', 意味: "somehow; one way or another" },
        耳にする: { 読み方: ['みみにする'], form: '表現、スル動詞', 意味: "to hear; to catch (the sound)" },
        願う: { 読み方: ['ねがう'], form: '五段動詞、他動詞', 意味: "to desire; to wish; to hope; to pray; to request" },
        食べ切る: { 読み方: ['たべきる'], form: '五段動詞、他動詞', 意味: "to finish eating; eat everything" },
        判断: { 読み方: ['はんだん'], form: '名詞、スル動詞、他動詞', 意味: "to judge" },
        振り返る: { 読み方: ['ふりかえる'], form: '五段動詞、自動詞', 意味: "to turn one's head; to look over one's shoulder; to turn around; to think back (on); to reminisce" },
        見つめる: { 読み方: ['みつめる'], form: '一段動詞、他動詞', 意味: "to stare at; to gaze at; to look hard at" },
        かしら: { 読み方: ['～かしら'], form: '助詞', 意味: "wonder if~; I wonder; do you think?" },
        ホッとする: { 読み方: [''], form: 'スル動詞', 意味: "with a feeling of relief" },
        空気: { 読み方: ['くうき'], form: '名詞', 意味: "air; atmosphere; mood" },
        声を掛ける: { 読み方: ['（～に）こえをかける'], form: '表現、一段動詞', 意味: "to speak (to someone)" },
        ひとりごと: { 読み方: [''], form: '名詞', 意味: "monologue; speaking to oneself" },
        つぶやく: { 読み方: [''], form: '五段動詞', 意味: "to murmur" },
        瞬間: { 読み方: ['しゅんかん'], form: '名詞', 意味: "moment; second; instant" },
        あるいは: { 読み方: [''], form: '接続し', 意味: "or" },
        安定: { 読み方: ['あんてい'], form: '名詞、スル動詞、自動詞', 意味: "stability; consistency; composure; to be(come) stable" },
    },

    kaku: {
        
    },

    yomerebaii: {

    },
}

export default unit4_2;