const unit3_2_sankou = {
    tango: {
        架空: { 読み方: ['かくう'], form: 'ノ形容詞、ナ形容詞、名詞', 意味: "imaginary; fictional" },
        想定: { 読み方: ['そうてい'], form: '名詞、スル動詞', 意味: "suppostion; hypothesis" },
        店舗: { 読み方: ['てんぽ'], form: '名詞', 意味: "shop; store; [counter for shops]" },
        大半: { 読み方: ['たいはん'], form: '名詞、副詞', 意味: "mostly; more than half, most (of), predominately" },
        代表格: { 読み方: ['だいひょうかく'], form: '名詞', 意味: "prime example; representative" },
        浸透: { 読み方: ['しんとう'], form: '名詞、スル動詞', 意味: "penetration; prevalence; permeation" },
        抑止: { 読み方: ['よくし'], form: '名詞、スル動詞', 意味: "inhibition; deterrence; stave off" },
        諸説: { 読み方: ['しょせつ'], form: '名詞', 意味: "various theories" },
        以南: { 読み方: ['～いなん'], form: '名詞、接尾辞', 意味: "south of; and south" },
        台: { 読み方: ['～だい'], form: '名詞、接尾辞', 意味: "~level (e.g., 4%台、１万円台)" },
        かんわない: { 読み方: ['（～に）かなわない'], form: 'イ形容詞', 意味: "no match for~; can't stand against~" },
        脱: { 読み方: ['だつ～'], form: '接頭辞', 意味: "de-; post-" },
        中心街: { 読み方: ['ちゅうしんがい'], form: '名詞', 意味: "downtown" },
        乗り入れ: { 読み方: ['のりいれ'], form: '名詞', 意味: "driving into; entry" },
        輸送: { 読み方: ['ゆそう'], form: '名詞、スル動詞', 意味: "transport" },
        直感: { 読み方: ['ちょっかん'], form: '名詞、スル動詞', 意味: "instinct; intuition; [v. to feel~]" },
        惹かれる: { 読み方: ['ひかれる'], form: '一段動詞、自動詞', 意味: "to be charmed by; to be attracted to" },
        掲げる: { 読み方: ['かかげる'], form: '一段動詞、他動詞', 意味: "to hold up high; to put up (a notice, sign); to hang out (e.g. a banner)" },
        追い込む: { 読み方: ['おいこむ'], form: '五段動詞、他動詞', 意味: "to lead/push/bring (something) (to~); to corner" },
        深刻: { 読み方: ['しんこく'], form: 'ナ形容詞', 意味: "serious; severe" },
        脅威: { 読み方: ['きょうい'], form: '名詞、スル動詞', 意味: "threat; menace" },
        先見性: { 読み方: ['せんけんせい'], form: '名詞', 意味: "foresight" },
        長ける: { 読み方: ['（～に）たける'], form: '一段動詞、自動詞', 意味: "to excel (at~); to be proficient (at~)" },
        あてはまる: { 読み方: [''], form: '五段動詞、自動詞', 意味: "to apply" },
        運搬用: { 読み方: ['うんぱんよう'], form: '', 意味: "for transportation" },
        需要: { 読み方: ['じゅよう'], form: '名詞', 意味: "demand" },
        新た: { 読み方: ['あらた'], form: 'ナ形容詞', 意味: "new" },
        正当: { 読み方: ['せいとう'], form: 'ナ形容詞', 意味: "justifiable; legitimate; right; valid" },
        恩恵: { 読み方: ['おんけい'], form: '名詞', 意味: "benefit" },
        植林: { 読み方: ['しょくりん'], form: '名詞、スル動詞', 意味: "afforestation" },
        生活の糧: { 読み方: ['せいかつのかて'], form: '表現', 意味: "source of one's livelihood; one's bread and butter" },
        浸食: { 読み方: ['しんしょく'], form: '名詞、スル動詞', 意味: "erosion" },
        時として: { 読み方: ['ときとして'], form: '副詞', 意味: "sometimes; in some cases" },
        足し: { 読み方: ['（～の）たし'], form: '名詞', 意味: "supplement; top up; making up (a deficiency)" },
        復旧: { 読み方: ['ふっきゅう'], form: '名詞、スル動詞', 意味: "restoration; recovery" },
        どうにかする: { 読み方: [''], form: '副詞、スル動詞', 意味: "to do something (with~)" },
        保護: { 読み方: ['ほご'], form: '名詞、スル動詞', 意味: "protection; safeguard" },
    },
}

export default unit3_2_sankou;