const kanji = {
    tango: {
        // ***** 第一章 *****
        // *** 第一課 ***
        一家: { 読み方: ['いっか'], form: '名詞', 意味: "a family; a household; a home; one's family; whole family" },
        ありがたい: { 読み方: [''], form: 'い形容詞', 意味: "grateful; thankful" },
        向き合う: { 読み方: ['むきあう'], form: '五段動詞、自動詞', 意味: "to face; to confront (an issue)" },
        つくづく: { 読み方: [''], form: 'と副詞', 意味: "deeply; greatly; severely; intently; utterly; completely" },
        養う: { 読み方: ['やしなう'], form: '五段動詞、他動詞', 意味: "to provide for; to support" },
        役目: { 読み方: ['やくめ'], form: '名詞', 意味: "duty; role; function" },
        甘える: { 読み方: ['あまえる'], form: '一段動詞、自動詞', 意味: "to be spoiled; to be dependent; to behaved like a spoiled child; to take advantage of" },
        世間知らず: { 読み方: ['せけんしらず'], form: '名詞、な形容詞', 意味: "ignorant of the ways of the world; inexperienced" },
        しつけ: { 読み方: [''], form: '名詞', 意味: "discipline" },
        言いつける: { 読み方: ['いいつける'], form: '一段動詞、他動詞', 意味: "to tell on (someone); to report; to tell (to do)" },
        自立: { 読み方: ['じりつ'], form: '名詞、する動詞、自動詞', 意味: "independence; self-reliance" },
        言い出す: { 読み方: ['いいだす'], form: '五段動詞、他動詞', 意味: "to begin to say; to start talking; to bring up" },
        意志: { 読み方: ['いし'], form: '名詞', 意味: "intention; will; volition" },
        尊重: { 読み方: ['そんちょう'], form: '名詞、する動詞、他動詞', 意味: "respect; esteem; regard" },
        説得: { 読み方: ['せっとく'], form: '名詞、する動詞、他動詞', 意味: "convince; persuasion" },
        納得: { 読み方: ['なっとく'], form: '名詞、する動詞', 意味: "consent; agreement; acceptance; acknowledgement" },
        逆らう: { 読み方: ['さからう'], form: '五段動詞、自動詞', 意味: "to go against; to oppose; to disobey" },
        反省: { 読み方: ['はんせい'], form: '名詞、する動詞、他動詞', 意味: "reflection; reconsideration; contemplation; regret" },
        放っておく: { 読み方: ['ほうっておく'], form: '表現、五段動詞', 意味: "to leave alone; to leave as is" },
        介護: { 読み方: ['かいご'], form: '名詞、する動詞、他動詞', 意味: "nursing; caregiving" },
        世代: { 読み方: ['せだい'], form: '名詞', 意味: "generation" },
        継ぐ: { 読み方: ['つぐ'], form: '五段動詞、他動詞', 意味: "to inherit; to succeed (a person, to a position, etc.); to take over; to add (e.g. charcoal to the fire)" },
        妊娠: { 読み方: ['にんしん'], form: '名詞、する動詞、自動詞', 意味: "pregnancy" },
        出産: { 読み方: ['しゅっさん'], form: '名詞、する動詞', 意味: "childbirth; (giving) birth" },
        産む: { 読み方: ['うむ'], form: '五段動詞、他動詞', 意味: "to give birth; to lay (eggs)" },
        // ***** 第一章 *****
        // *** 第二課 ***
        友人: { 読み方: ['ゆうじん'], form: '名詞', 意味: "friend" },
        仲: { 読み方: ['なか'], form: '名詞', 意味: "relationship" },
        縁: { 読み方: ['えん'], form: '名詞', 意味: "fate; destiny (esp. as a mysterious force that binds two people together" },
        ニックネーム: { 読み方: [''], form: '名詞', 意味: "nickname" },
        大半: { 読み方: ['たいはん'], form: '名詞', 意味: "majority; most (of)" },
        恵まれる: { 読み方: ['めぐまれる'], form: '一段動詞、自動詞', 意味: "to be blessed with" },
        頼る: { 読み方: ['たよる'], form: '五段動詞', 意味: "to depend on; to rely on; to count on" },
        頼もしい: { 読み方: ['たのもしい'], form: 'い形容詞', 意味: "dependable; reliable" },
        見習う: { 読み方: ['みならう'], form: '五段動詞、他動詞', 意味: "to emulate; to follow (someone's) example; to imitate; to learn (by observation)" },
        打ち明ける: { 読み方: ['うちあける'], form: '一段動詞、他動詞', 意味: "to confess; to confide; to reveal; to disclose; to open (one's heart)" },
        励ます: { 読み方: ['はげます'], form: '五段動詞、他動詞', 意味: "to encourage; to cheer (someone) up" },
        あえて: { 読み方: [''], form: '副詞', 意味: "daringly (doing something); purposely (of something needless, unexpected or seemingly counterproductive, etc.)" },
        なぐさめる: { 読み方: [''], form: '一段動詞、他動詞', 意味: "to comfort; to console" },
        察する: { 読み方: ['さっする'], form: 'する動詞、他動詞', 意味: "to infer; to guess; to sense; to presume" },
        思いやり: { 読み方: ['おもいやり'], form: '名詞', 意味: "thoughtfulness; consideration; sympathy; compassion" },
        何気ない: { 読み方: ['なにげない'], form: 'い形容詞', 意味: "casual; nonchalant" },
        からかう: { 読み方: [''], form: '五段動詞、他動詞', 意味: "to tease; to make fun of" },
        幹事: { 読み方: ['かんじ'], form: '名詞、する動詞', 意味: "organizer; person in charge of making arrangements" },
        呼び出す: { 読み方: ['よびだす'], form: '五段動詞、他動詞', 意味: "to send for; to summon" },
        盛り上がる: { 読み方: ['もりあがる'], form: '五段動詞、自動詞', 意味: "to liven up; to get excited; to rouse; to swell" },
        あきれる: { 読み方: [''], form: '一段動詞、自動詞', 意味: "to be appalled; to be astounded; to be fed up; to be disguested" },
        ふざける: { 読み方: [''], form: '一段動詞、自動詞', 意味: "to fool around; to screw around" },
        久しい: { 読み方: ['ひさしい'], form: 'い形容詞', 意味: "long (time that has passed); old (story)" },
        // ***** 第一章 *****
        //*** 第三課 ***
        初対面: { 読み方: ['しょたいめん'], form: '名詞', 意味: "first meeting" },
        自己紹介: { 読み方: ['じこしょうかい'], form: '名詞、する動詞、自動詞', 意味: "self-introduction" },
        おじぎ: { 読み方: [''], form: '名詞、する動詞、自動詞', 意味: "bow" },
        近所付き合い: { 読み方: ['きんじょづきあい'], form: '名詞、する動詞', 意味: "interaction with neighbors" },
        大家: { 読み方: ['おおや'], form: '名詞', 意味: "landlord; landlady" },
        飼い主: { 読み方: ['かいぬし'], form: '名詞', 意味: "(pet) owner" },
        交わす: { 読み方: ['かわす'], form: '五段動詞、他動詞', 意味: "to exchange (messages, greetings, arguments, etc.)" },
        呼び止める: { 読み方: ['よびとめる'], form: '一段動詞、他動詞', 意味: "to (call and) stop; to call (someone) to stop" },
        振り返る: { 読み方: ['ふりかえる'], form: '五段動詞', 意味: "to look over one's shoulder; to look back; to think back (on); to reminisce; to reflect (on)" },
        再会: { 読み方: ['さいかい'], form: '名詞、する動詞、自動詞', 意味: "reunion" },
        覚え: { 読み方: ['おぼえ'], form: '名詞', 意味: "recollection; memory" },
        心当たり: { 読み方: ['こころあたり'], form: '名詞', 意味: "known ofe; something that comes to mind; having in mind" },
        結びつく: { 読み方: ['むすびつく'], form: '五段動詞、自動詞', 意味: "to link; to be put together" },
        とっさ: { 読み方: ['とっさ（に）'], form: '名詞、副詞', 意味: "moment; instant; instantly; at once; in a split second" },
        てっきり: { 読み方: [''], form: '副詞', 意味: "assumed; surely (used of beliefs that turned out to be false)" },
        思い込む: { 読み方: ['おもいこむ'], form: '五段動詞、自動詞', 意味: "to be under the impression (that); to be convinced (that)" },
        コミュニケーション: { 読み方: [''], form: '名詞', 意味: "communication" },
        ネットワーク: { 読み方: [''], form: '名詞', 意味: "network" },
        直接: { 読み方: ['ちょくせつ'], form: 'な形容詞、名詞、副詞', 意味: "direct; immediate; personal" },
        接する: { 読み方: ['せっする'], form: 'する動詞、自動詞', 意味: "coming in contact with; to touch; to be adjacent" },
        招く: { 読み方: ['まねく'], form: '五段動詞、他動詞', 意味: "to invite; be the cause of an unfavorable result" },
        気配り: { 読み方: ['きくばり'], form: '名詞、する動詞、自動詞', 意味: "consideration for others' feelings; care; attentiveness" },
        込める: { 読み方: ['こめる'], form: '一段動詞、他動詞', 意味: "infuse; insert; put in" },
        同期: { 読み方: ['どうき'], form: '名詞', 意味: "same year (of graduation, entering a company, etc.); colleague" },
        ぐち: { 読み方: [''], form: '名詞', 意味: "complaint; grumble" },
        大いに: { 読み方: ['おおいに'], form: '副詞', 意味: "very; a great deal; to one's heart's content" },
        // ***** 第一章 *****
        //*** 第四課 ***
        カップル: { 読み方: [''], form: '名詞', 意味: "couple; intimate relationship" },
        愛: { 読み方: ['あい'], form: '名詞', 意味: "love; affection; care" },
        同士: { 読み方: ['どうし'], form: '名詞', 意味: "each other; fellow; companion" },
        お互い: { 読み方: ['おたがい（に）'], form: '名詞、副詞', 意味: "each other; mutually; one another" },
        釣り合う: { 読み方: ['つりあう'], form: '五段動詞、自動詞', 意味: "suitable; to suit; to go well together; to be a good match" },
        むしろ: { 読み方: [''], form: '副詞', 意味: "rather; better; instead; if anything" },
        言わば: { 読み方: ['いわば'], form: '副詞', 意味: "so to speak; ; as it were; as like~" },
        視線: { 読み方: ['しせん'], form: '名詞', 意味: "line of sight; one's gaze; one's eyes (looking)" },
        見つめる: { 読み方: ['みつめる'], form: '一段動詞、他動詞', 意味: "to stare (at); to gaze (at); to look hard (at)" },
        そらす: { 読み方: [''], form: '五段動詞、他動詞', 意味: "to turn away (one's eyes, face, etc.); to avert; look away" },
        ちらっと: { 読み方: [''], form: '副詞', 意味: "at a glance; peek; by accident" },
        もしかすると: { 読み方: [''], form: '副詞', 意味: "maybe; perhaps; possibly; by some chance" },
        探る: { 読み方: ['さぐる'], form: '五段動詞、他動詞', 意味: "to feel around for; to search for; to look for; to investigate; to probe into" },
        示す: { 読み方: ['しめす'], form: '五段動詞、他動詞', 意味: "to show; to demonstrate; to tell; to point out; to indicate" },
        口実: { 読み方: ['こうじつ'], form: '名詞', 意味: "excuse" },
        うつむく: { 読み方: [''], form: '五段動詞、自動詞', 意味: "to look down; to cast one's eyes downward; to hand one's head" },
        こそこそ: { 読み方: [''], form: '副詞、する動詞', 意味: "sneakily; secretly; stealthily" },
        ささやく: { 読み方: [''], form: '五段動詞、自動詞', 意味: "to whisper; to murmur" },
        禁物: { 読み方: ['きんもつ'], form: '名詞', 意味: "taboo; thing that should be (carefully) avoided; no-no; thing to definitely not do" },
        許す: { 読み方: ['ゆるす'], form: '五段動詞、他動詞', 意味: "to forgive; to allow" },
        合コン: { 読み方: ['合コン'], form: '名詞、する動詞', 意味: "mixer; joint party" },
        アプローチ: { 読み方: [''], form: '名詞、する動詞、自動詞', 意味: "approach (to a problem, issue, etc.)" },
        運命: { 読み方: ['うんめい'], form: '名詞', 意味: "destiny; fate" },
        決意: { 読み方: ['けつい'], form: '名詞、する動詞、他動詞', 意味: "determination; decision; resolution" },
        プロポーズ: { 読み方: [''], form: '名詞、する動詞、自動詞', 意味: "(marriage) proposal" },
        誓う: { 読み方: ['ちかう'], form: '五段動詞、他動詞', 意味: "to swear; to vow; to pledge; to promise" },
        花嫁: { 読み方: ['はなよめ'], form: '名詞', 意味: "bride" },
        // ***** 第一章 *****
        //*** 第五課 ***

        // ***** 第二章 *****
        //*** 第一課 ***
        // : { 読み方: [''], form: '', 意味: "" },
    }
}

export default kanji;