const kanji = {
    kaku: {
        // Chapter 1
        はじめて: { 読み方: ['初めて'], form: '副詞、の形容詞', 意味: "for the first time" },
        いしやま: { 読み方: ['石山'], form: '名字', 意味: "stone mountain" },
        しつれい: { 読み方: ['失礼'], form: 'スル動詞、ナ形容詞', 意味: "discourtesy; impoliteness" },
        もうす: { 読み方: ['申す'], form: '五段動詞、謙譲語', 意味: "humble form of 言う" },
        おねがいします: { 読み方: ['お願いします'], form: '表現', 意味: "please (Humble kenjougo)" },
        おしえる: { 読み方: ['教える'], form: '一段動詞、他動詞', 意味: "to teach; to inform" },
        まえ: { 読み方: ['前'], form: '名詞、ノ形容詞', 意味: "before; in front (of)" },
        りゅうがく: { 読み方: ['留学'], form: '名詞、スル動詞', 意味: "studying abroad" },
        ことし: { 読み方: ['今年'], form: '名詞、副詞', 意味: "this year" },
        みた: { 読み方: ['三田'], form: '名字', 意味: "three rice field" },
        おおい: { 読み方: ['多い'], form: 'イ形容詞', 意味: "many" },
        だいがくいん: { 読み方: ['大学院'], form: '名詞', 意味: "graduate school" },
        くん: { 読み方: ['君'], form: '接尾詞', 意味: "boy" },
        でんきこうがく: { 読み方: ['電気工学'], form: '名詞', 意味: "electrical engineering" },
        せんこう: { 読み方: ['専攻'], form: '名詞、スル動詞', 意味: "major subject; special study" },
        がくぶ: { 読み方: ['学部'], form: '名詞', 意味: "undergraduate" },
        じょうず: { 読み方: ['上手'], form: 'ナ形容詞', 意味: "skillful" },
        きみ: { 読み方: ['君'], form: '代名詞', 意味: "you" },
        こんど: { 読み方: ['今度'], form: '名詞、副詞', 意味: "one of these days; next time; this time" },
        とき: { 読み方: ['時'], form: '名詞', 意味: "time" },
        じつは: { 読み方: ['実は'], form: '表現', 意味: "actually; in fact; by the way; to tell you the truth" },
        ちゅうがく: { 読み方: ['中学'], form: '名詞', 意味: "middle school" },
        ぶんか: { 読み方: ['文化'], form: '名詞', 意味: "culture" },
        じょせい: { 読み方: ['女性'], form: '名詞', 意味: "woman; female" },
        かえる: { 読み方: ['帰る'], form: '五段動詞、自動詞', 意味: "to return; to come home" },
        とる: { 読み方: ['取る'], form: '五段動詞、他動詞', 意味: "to take" },
        うまれる: { 読み方: ['～で）生まれる'], form: '一段動詞、自動詞', 意味: "to be born (in/at~)" },
        わたし: { 読み方: ['私'], form: '代名詞', 意味: "I; me" },
        しごと: { 読み方: ['仕事'], form: '名詞', 意味: "work; job" },
        とまる: { 読み方: ['泊まる'], form: '五段動詞、自動詞', 意味: "to stay (over night)" },
        きにいる: { 読み方: ['（～が）気に入る'], form: '表現、五段動詞', 意味: "to like ~; to be fond (of~)" },
        あいだに: { 読み方: ['間に'], form: '副詞', 意味: "while; during (the time when)" },
        ところ: { 読み方: ['所'], form: '名詞', 意味: "place" },
        いえ: { 読み方: ['家'], form: '名詞', 意味: "house" },
        うち: { 読み方: ['家'], form: '名詞', 意味: "one's home" },
        でんわ: { 読み方: ['電話'], form: '名詞', 意味: "phone" },
        にっき: { 読み方: ['日記'], form: '名詞', 意味: "diary" },
        つく: { 読み方: ['（～に）着く'], form: '五段動詞、自動詞', 意味: "to arrive (at)" },
        おなじ: { 読み方: ['同じ'], form: '名詞', 意味: "same; equal; identical" },
        じぶん: { 読み方: ['自分'], form: '代名詞', 意味: "myself; oneself" },
        ちかい: { 読み方: ['近い'], form: 'イ形容詞', 意味: "near; close" },
        あるく: { 読み方: ['歩く'], form: '五段動詞、自動詞', 意味: "to walk" },
        だんせい: { 読み方: ['男性'], form: '名詞', 意味: "man; male" },
        きょねん: { 読み方: ['去年'], form: '名詞、副詞', 意味: "last year" },
        しかた: { 読み方: ['仕方'], form: '名詞', 意味: "way of doing something; method" },
        うつくしい: { 読み方: ['美しい'], form: 'イ形容詞', 意味: "beautiful" },
        ぶんぽう: { 読み方: ['文法'], form: '名詞', 意味: "grammar" },
        かんがえかた: { 読み方: ['考え方'], form: '名詞', 意味: "way of thinking" },
        // Chapter 2
        れい: { 読み方: ['例'], form: '名詞', 意味: "example" },
        あさ: { 読み方: ['朝'], form: '名詞', 意味: "morning" },
        ごご: { 読み方: ['午後'], form: '名詞', 意味: "p.m.; afternoon" },
        へん: { 読み方: ['変'], form: 'ナ形容詞', 意味: "strange; weird" },
        いみ: { 読み方: ['意味'], form: '名詞', 意味: "meaning" },
        さげる: { 読み方: ['下げる'], form: '一段動詞、他動詞', 意味: "to lower" },
        わかる: { 読み方: ['分かる'], form: '五段動詞、自動詞', 意味: "to understand; to comprehend" },
        めざましとけい: { 読み方: ['目覚まし時計'], form: '名詞', 意味: "alarm clock" },
        ねむい: { 読み方: ['眠い'], form: 'イ形容詞', 意味: "sleepy" },
        こえ: { 読み方: ['声'], form: '名詞', 意味: "voice" },
        にじはん: { 読み方: ['二時半'], form: '時', 意味: "2:30" },
        むずかしい: { 読み方: ['難しい'], form: 'イ形容詞', 意味: "difficult" },
        たいへん: { 読み方: ['大変'], form: 'ナ形容詞', 意味: "difficult; hard" },
        外: { 読み方: ['そと'], form: '名詞', 意味: "outside" },
        おおあめ: { 読み方: ['大雨'], form: '名詞', 意味: "heavy rain" },
        いそぐ: { 読み方: ['急ぐ'], form: '五段動詞、自動詞、他動詞', 意味: "to hurry" },
        さきに: { 読み方: ['先に'], form: '副詞', 意味: "ahead (of someone); ahead (of time)" },
        あとで: { 読み方: ['後で'], form: '副詞', 意味: "afterwards" },
        よしだ: { 読み方: ['吉田'], form: '名字', 意味: "good luck + ricefield" },
        じだい: { 読み方: ['時代'], form: '時相名刺', 意味: "time period; those days" },
        だす: { 読み方: ['出す'], form: '五段動詞、他動詞', 意味: "to take out; to put out" },
        ぼく: { 読み方: ['僕'], form: '代名詞', 意味: "I; me" },
        ばんごう: { 読み方: ['番号'], form: '名詞', 意味: "number; series of digits" },
        にちべい: { 読み方: ['日米'], form: '名詞、ノ形容詞', 意味: "日本とアメリカ" },
        こまる: { 読み方: ['（～に）困る'], form: '五段動詞、自動詞', 意味: "to have difficulty (with~); to be troubled" },
        たぶん: { 読み方: ['多分'], form: '副詞', 意味: "perhaps; probably" },
        かわり: { 読み方: ['代わり（に）'], form: '表現', 意味: "instead of; in exchange for" },
        あたる: { 読み方: ['（～に）当たる'], form: '五段動詞、自動詞', 意味: "to correspond (to~)" },
        あいて: { 読み方: ['相手'], form: '名詞', 意味: "addressee; the person you are talking to" },
        めうえ: { 読み方: ['目上'], form: '名詞', 意味: "person of higher status; one's senior/superior" },
        ゆうじん: { 読み方: ['友人'], form: '名詞', 意味: "friend (more formal than 友達)" },
        やくす: { 読み方: ['訳す'], form: '五段動詞、他動詞', 意味: "to translate" },
        せつめい: { 読み方: ['説明'], form: 'スル動詞、名詞', 意味: "explanation" },
        たとえば: { 読み方: ['例えば'], form: '副詞', 意味: "for example" },
        しょくじ: { 読み方: ['食事'], form: '名詞、スル動詞', 意味: "meal; dinner" },
        たいして: { 読み方: ['(それに)対して'], form: '表現', 意味: "in response (to that); towards; regarding" },
        かぞく: { 読み方: ['家族'], form: '名詞', 意味: "family" },
        すうじつまえ: { 読み方: ['数日前'], form: '名詞', 意味: "several days ago" },
        きまりもんく: { 読み方: ['決まり文句'], form: '名詞', 意味: "set phrase" },
        ようご: { 読み方: ['用語'], form: '名詞', 意味: "term(s); terminology" },
        ほうが: { 読み方: ['（～の）方が'], form: '表現', 意味: "~is more... than" },
        きゃく: { 読み方: ['客'], form: '名詞', 意味: "guest; visitor; customer" },
        こども: { 読み方: ['子供'], form: '名詞', 意味: "child" },
        おぼえる: { 読み方: ['覚える'], form: '一段動詞、他動詞', 意味: "to remember" },
        だいじ: { 読み方: ['大事（な）'], form: 'ナ形容詞', 意味: "important" },
        // Chapter 3
        たのむ: { 読み方: ['頼む'], form: '五段動詞、他動詞', 意味: "to request; to rely on; please (colloquially)" },
        わすれる: { 読み方: ['忘れる'], form: '一段動詞、他動詞', 意味: "to foreget" },
        さんまい: { 読み方: ['三枚'], form: '名詞', 意味: "three flat objects (sheets of paper, pieces of clothes, etc.)" },
        うける: { 読み方: ['受ける'], form: '一段動詞、他動詞', 意味: "to receive; to take (an exam)" },
        もうしこむ: { 読み方: ['申し込む'], form: '五段動詞、他動詞', 意味: "to apply" },
        きって: { 読み方: ['切手'], form: '名詞', 意味: "postage stamp" },
        ぶしつ: { 読み方: ['部室'], form: '名詞', 意味: "clubroom" },
        いたい: { 読み方: ['痛い'], form: 'イ形容詞', 意味: "painful; sore; cringy (colloquially)" },
        わるい: { 読み方: ['悪い'], form: 'イ形容詞', 意味: "bad; sorry; (my) bad" },
        おもな: { 読み方: ['主な'], form: 'ナ形容詞', 意味: "main" },
        りよう: { 読み方: ['利用'], form: '名詞、スル動詞', 意味: "to make use of; use" },
        いちばん: { 読み方: ['一番'], form: '名詞、ノ形容詞、副詞', 意味: "best; number one" },
        べんり: { 読み方: ['便利'], form: 'ナ形容詞', 意味: "convenient" },
        はらう: { 読み方: ['払う'], form: '五段動詞、他動詞', 意味: "to pay (money, bill)" },
        ちがう: { 読み方: ['違う'], form: '五段動詞、自動詞', 意味: "to differ (from); to not match the correct answer" },
        おこなう: { 読み方: ['行う'], form: '五段動詞、他動詞', 意味: "to carry out; to conduct [usually used in written language]" },
        もくてき: { 読み方: ['目的'], form: '名詞', 意味: "purpose; goal" },
        いがい: { 読み方: ['意外'], form: '名詞、副詞', 意味: "other than; with the exception of" },
        たすける: { 読み方: ['助ける'], form: '一段動詞、他動詞', 意味: "to help; to save" },
        にゅうがく: { 読み方: ['入学'], form: '名詞、スル動詞', 意味: "entry to school or university" },
        ぜんぶ: { 読み方: ['全部'], form: '名詞、ノ形容詞、副詞', 意味: "all; entire; whole" },
        おわる: { 読み方: ['終わる'], form: '五段動詞、自動詞', 意味: "be finished; be over" },
        きこく: { 読み方: ['帰国'], form: '名詞、スル動詞', 意味: "return to one's country" },
        かならずしも: { 読み方: ['必ずしも～ない'], form: '副詞', 意味: "not necessarily" },
        おんがく: { 読み方: ['音楽'], form: '名詞', 意味: "music" },
        ともだち: { 読み方: ['友達'], form: '名詞', 意味: "friend" },
        かいわ: { 読み方: ['会話'], form: '名詞、スル動詞', 意味: "conversation" },
        もの: { 読み方: ['者'], form: '名詞', 意味: "person [＝人]" },
        とくに: { 読み方: ['特に'], form: '副詞', 意味: "particularly; in particular" },
        // Chapter 4
        しゃしん: { 読み方: ['写真'], form: '名詞', 意味: "picture; photograph" },
        アメリカし: { 読み方: ['アメリカ史'], form: '名詞', 意味: "American history" },
        べつに: { 読み方: ['別に～ない'], form: '副詞', 意味: "(not) particularly; (not) especially" },
        おにいちゃん: { 読み方: ['お兄ちゃん'], form: '名詞', 意味: "(someone else's) older brother" },
        いもうと: { 読み方: ['妹'], form: '名詞', 意味: "little sister" },
        あに: { 読み方: ['兄'], form: '名詞', 意味: "(one's own) older brother" },
        にている: { 読み方: ['（～に）似ている'], form: '一段動詞、自動詞', 意味: "to resembele (~); to be similar" },
        しゅう: { 読み方: ['州'], form: '名詞、接尾語', 意味: "state" },
        じんこう: { 読み方: ['人口'], form: '名詞', 意味: "population" },
        まちがえる: { 読み方: ['間違える'], form: '一段動詞、他動詞', 意味: "to make a mistake" },
        ゆうめい: { 読み方: ['有名'], form: 'ナ形容詞', 意味: "famous" },
        みずうみ: { 読み方: ['湖'], form: '名詞', 意味: "lake" },
        はる: { 読み方: ['春'], form: '名詞', 意味: "spring" },
        あき: { 読み方: ['秋'], form: '名詞', 意味: "fall" },
        えき: { 読み方: ['駅'], form: '名詞', 意味: "train station" },
        とおい: { 読み方: ['遠い'], form: 'ィ形容詞', 意味: "far" },
        じてんしゃ: { 読み方: ['自転車'], form: '名詞', 意味: "bicycle" },
        かりる: { 読み方: ['借りる'], form: '一段動詞、他動詞', 意味: "to borrow; to rent" },
        つれる: { 読み方: ['連れる'], form: '一段動詞、他動詞', 意味: "to take (someone) with; to bring along" },
        ふゆ: { 読み方: ['冬'], form: '名詞', 意味: "winter" },
        ゆうしょく: { 読み方: ['夕食'], form: '名詞', 意味: "dinner [lit., evening meal]" },
        ひさしぶり: { 読み方: ['久しぶり'], form: 'ナ形容詞、ノ形容詞、名詞', 意味: "for the first time in a long time; a long time (since the last time)" },
        ほんとうに: { 読み方: ['本当に'], form: '副詞', 意味: "really; truly" },
        すえ: { 読み方: ['末'], form: '名詞', 意味: "end" },
        なつ: { 読み方: ['夏'], form: '名詞', 意味: "summer" },
        あつい: { 読み方: ['暑い'], form: 'ィ形容詞', 意味: "hot [with reference to weather]" },
        ながい: { 読み方: ['長い'], form: 'ィ形容詞', 意味: "long" },
        はやい: { 読み方: ['速い'], form: 'ィ形容詞', 意味: "fast; quick" },
        こんがっき: { 読み方: ['今学期'], form: '名詞', 意味: "this semester" },
        せいかつ: { 読み方: ['生活'], form: '名詞', 意味: "living; life (one's daily existence)" },
        やくにたつ: { 読み方: ['役に立つ'], form: '表現、五段動詞', 意味: "to be useful; to be helpful" },
        でんしゃ: { 読み方: ['電車'], form: '名詞', 意味: "train" },
        のる: { 読み方: ['（～に）乗る'], form: '五段動詞、自動詞', 意味: "to ride (in/on~)" },
        からだ: { 読み方: ['体'], form: '名詞', 意味: "body; health" },
        かわる: { 読み方: ['変わる'], form: '五段動詞、自動詞', 意味: "to change" },
        ぶっきょう: { 読み方: ['仏教'], form: '名詞', 意味: "Buddhism" },
        しんぶんきじ: { 読み方: ['新聞記事'], form: '名詞', 意味: "newspaper article" },
        かんじ: { 読み方: ['漢字'], form: '名詞', 意味: "kanji; Chinese character" },
        いっかい: { 読み方: ['一回'], form: '名詞、副詞', 意味: "once; one time; per occasion" },
        こんばん: { 読み方: ['今晩'], form: '名詞', 意味: "this evening" },
        // Chapter 5
        しつもん: { 読み方: ['質問'], form: '名詞、スル動詞', 意味: "question; inquiry" },
        べっか: { 読み方: ['別科'], form: '名詞', 意味: "special course; another course" },
        うかがう: { 読み方: ['伺う'], form: '五段動詞、他動詞、謙譲語', 意味: "[humble form of 聞く (to ask)]" },
        あたらしい: { 読み方: ['新しい'], form: 'ィ形容詞', 意味: "new" },
        ごうしつ: { 読み方: ['～号室'], form: '名詞', 意味: "room number ~" },
        けんきゅうしつ: { 読み方: ['研究室'], form: '名詞', 意味: "professor's office; laboratory" },
        うつる: { 読み方: ['（～に）移る'], form: '五段動詞、自動詞', 意味: "to move (to~); to transfer (department)" },
        いっぽ: { 読み方: ['一歩'], form: '名詞、副詞', 意味: "a step; one step" },
        もういっぽ: { 読み方: ['もう一歩'], form: '表現', 意味: "to need just a little more improvement [lit., just one more step]" },
        せいせき: { 読み方: ['成績'], form: '名詞', 意味: "grades; results" },
        よしゅう: { 読み方: ['予習'], form: '名詞、スル動詞', 意味: "preparation for a lession (class)" },
        しゅくだい: { 読み方: ['宿題'], form: '名詞', 意味: "homework" },
        げんだいし: { 読み方: ['現代詩'], form: '名詞', 意味: "contemporary history" },
        ぶいん: { 読み方: ['部員'], form: '名詞', 意味: "staff; member (club, society, etc.)" },
        しま: { 読み方: ['島'], form: '名詞', 意味: "island" },
        にゅうがくしけん: { 読み方: ['入学試験'], form: '名詞', 意味: "entrance examination" },
        いっしょうけんめい: { 読み方: ['一生懸命'], form: 'ナ形容詞、副詞、名詞', 意味: "very hard; with utmost effort; with all one's might" },
        せいと: { 読み方: ['生徒'], form: '名詞', 意味: "student; pupil" },
        そつぎょう: { 読み方: ['卒業'], form: '名詞、スル動詞', 意味: "graduation; movinig on (from); outgrowing (somethingG)" },
        つぎのとし: { 読み方: ['次の年'], form: '名詞', 意味: "the following year" },
        たいせつ: { 読み方: ['大切'], form: 'ナ形容詞', 意味: "important" },
        りゆう: { 読み方: ['理由'], form: '名詞', 意味: "reason; motive" },
        かず: { 読み方: ['数'], form: '名詞', 意味: "number; amount" },
        すくない: { 読み方: ['少ない'], form: 'ィ形容詞', 意味: "few; a little; scarce" },
        つよい: { 読み方: ['強い'], form: 'ィ形容詞', 意味: "strong" },
        いっぱんてき: { 読み方: ['一般的'], form: 'ナ形容詞', 意味: "general; common; typical" },
        らく: { 読み方: ['楽'], form: 'ナ形容詞', 意味: "easy; comfortable; leading an easy life" },
        いいてん: { 読み方: ['いい点'], form: '名詞', 意味: "good mark; score; grade; point" },
        じゅうよう: { 読み方: ['重要'], form: 'ナ形容詞、名詞', 意味: "important; essential" },
        だいいち: { 読み方: ['～第一'], form: 'ノ形容詞、名詞', 意味: "~first" },
        つきあい: { 読み方: ['付き合い'], form: '名詞', 意味: "socialization; friendship; association" },
        // Chapter 6
        ちゅうもん: { 読み方: ['注文'], form: '名詞、スル動詞', 意味: "to order (something)" },
        つとめる: { 読み方: ['（～に）勤める'], form: '一段動詞、他動詞', 意味: "to work (for); to be employed (at)" },
        みせ: { 読み方: ['店'], form: '名詞', 意味: "shop; store" },
        ごはん: { 読み方: ['ご飯'], form: '名詞', 意味: "cooked rice" },
        おやこ: { 読み方: ['親子'], form: '名詞', 意味: "parent and child" },
        じつぶつ: { 読み方: ['実物'], form: '名詞、野形容詞', 意味: "actual thing; real thing" },
        てんいん: { 読み方: ['店員'], form: '名詞', 意味: "store clerk; shop-employee" },
        とり: { 読み方: ['鳥'], form: '名詞', 意味: "bird" },
        おもしろい: { 読み方: ['面白い'], form: 'イ形容詞', 意味: "interesting; amusing; entertaining" },
        ちゅうしょく: { 読み方: ['昼食'], form: '名詞', 意味: "lunch" },
        いまい: { 読み方: ['今井'], form: '名字', 意味: "now + well/town" },
        さま: { 読み方: ['様'], form: '接尾語', 意味: "[polite form of さん]" },
        おちゃ: { 読み方: ['お茶'], form: '名詞', 意味: "(green) tea" },
        せき: { 読み方: ['席'], form: '名詞', 意味: "seat" },
        うる: { 読み方: ['売る'], form: '五段動詞、他動詞', 意味: "to sell" },
        かぎる: { 読み方: ['～とは限らない'], form: '', 意味: "not necessarily ~ [限る = to limit]" },
        しゅうかん: { 読み方: ['習慣'], form: '名詞', 意味: "habit; (social) custom; practice" },
        りょこう: { 読み方: ['旅行'], form: '名詞、スル動詞', 意味: "travel; trip" },
        かんじる: { 読み方: ['～と感じる'], form: '一段動詞', 意味: "to feel that ~" },
        くうこう: { 読み方: ['空港'], form: '名詞', 意味: "airport" },
        わたす: { 読み方: ['渡す'], form: '五段動詞、他動詞', 意味: "to hand (something) to; to " },
        よびとめる: { 読み方: ['呼び止める'], form: '一段動詞、他動詞', 意味: "to call (someone) to stop; to hail (e.g. a taxi)" },
        りょかん: { 読み方: ['旅館'], form: '名詞', 意味: "Japanese-style inn" },
        しゅくはくりょう: { 読み方: ['宿泊料'], form: '名詞', 意味: "hotel charges" },
        こうきゅう: { 読み方: ['高級'], form: 'ナ形容詞、野形容詞、名詞', 意味: "high class; first-rate" },
        りょうりや: { 読み方: ['料理屋'], form: '名詞', 意味: "high class Japanese style restaurant" },
        ひつよう: { 読み方: ['必要'], form: 'ナ形容詞', 意味: "necessary" },
        しんぱい: { 読み方: ['心配'], form: '名詞、スル動詞、ナ形容詞', 意味: "to worry; concern" },
        なれる: { 読み方: ['慣れる'], form: '一段動詞、自動詞', 意味: "to get used to; to grow accustomed to; to become familar with" },
        ぶっか: { 読み方: ['物価'], form: '名詞', 意味: "cost-of-living; (commodity) prices" },
        くらべる: { 読み方: ['（～と）比べる'], form: '', 意味: "compared with" },
        // Chapter 7
        こばやし: { 読み方: ['小林'], form: '名字', 意味: "small + grove" },
        しあい: { 読み方: ['試合'], form: '名詞、スル動詞', 意味: "match" },
        おいわい: { 読み方: ['お祝い'], form: '名詞、スル動詞', 意味: "celebration" },
        かちょう: { 読み方: ['課長'], form: '名詞', 意味: "section chief" },
        おと: { 読み方: ['音'], form: '名詞', 意味: "sound" },
        ぶひん: { 読み方: ['部品'], form: '名詞', 意味: "parts" },
        くみたてる: { 読み方: ['組み立てる'], form: '一段動詞、他動詞', 意味: "to assemble; to put together" },
        ほしい: { 読み方: ['欲しい'], form: 'イ形容詞', 意味: "to want" },
        てにいれる: { 読み方: ['手に入れる'], form: '表現、一段動詞、他動詞', 意味: "to obtain" },
        わかい: { 読み方: ['若い'], form: 'イ形容詞', 意味: "young" },
        むかし: { 読み方: ['昔'], form: 'ノ形容詞、名詞', 意味: "the past; the old days" },
        ようじ: { 読み方: ['用事'], form: '名詞', 意味: "errands; things to do" },
        でぐち: { 読み方: ['出口'], form: '名詞', 意味: "exit" },
        ちゅうおう: { 読み方: ['中央'], form: '名詞、ノ形容詞', 意味: "central; center" },
        たのしみ: { 読み方: ['（～を）楽しみにしています'], form: '表現', 意味: "to be looking forward (to~)" },
        えいが: { 読み方: ['映画'], form: '名詞', 意味: "movie" },
        あした: { 読み方: ['明日'], form: '名詞、副詞', 意味: "tomorrow" },
        さむらい: { 読み方: ['侍'], form: '名詞', 意味: "samurai" },
        ならぶ: { 読み方: ['並ぶ'], form: '五段動詞、自動詞', 意味: "to stand in line" },
        さかん: { 読み方: ['盛ん'], form: 'ナ形容詞', 意味: "thriving; flourishing" },
        はじめる: { 読み方: ['（～を）始める'], form: '一段動詞、他動詞', 意味: "to start; to begin" },
        そのた: { 読み方: ['その他'], form: '名詞、ノ形容詞', 意味: "and others" },
        ほうもん: { 読み方: ['訪問'], form: '名詞、スル動詞、ノ形容詞', 意味: "call; visit" },
        あつめる: { 読み方: ['集める'], form: '一段動詞、他動詞', 意味: "to collect; to assemble; to gather" },
        たたかう: { 読み方: ['戦う'], form: '五段動詞、自動詞', 意味: "to fight (with)" },
        まける: { 読み方: ['負ける'], form: '一段動詞、自動詞', 意味: "to lose" },
        たいへいよう: { 読み方: ['太平洋'], form: '名詞', 意味: "Pacific Ocean" },
        せんそう: { 読み方: ['戦争'], form: '名詞、スル動詞', 意味: "war" },
        せんし: { 読み方: ['戦死'], form: '名詞、スル動詞', 意味: "death in battle" },
        きんねん: { 読み方: ['近年'], form: '名詞、副詞', 意味: "recent years" },
        ふえる: { 読み方: ['増える'], form: '一段動詞、自動詞', 意味: "to increase" },
        けん: { 読み方: ['県'], form: '名詞、接尾詞', 意味: "prefecture" },
        ほうえい: { 読み方: ['放映'], form: '名詞、スル動詞', 意味: "televising; broadcasting" },
        おうべい: { 読み方: ['欧米'], form: '名詞', 意味: "Europe and America; the West" },
        かんしん: { 読み方: ['関心を集める'], form: '表現', 意味: "to gain interest" },
        でんとうてき: { 読み方: ['伝統的'], form: 'ナ形容詞', 意味: "traditional" },
        さいきん: { 読み方: ['最近'], form: '名詞、ノ形容詞、副詞', 意味: "recently" },
        しゅっしん: { 読み方: ['主審'], form: '名詞、ノ形容詞', 意味: "one's home" },
        // Chapter 8
        さがす: { 読み方: ['探す'], form: '五段動詞、他動詞', 意味: "to search for; to look for" },
        きょうし: { 読み方: ['教師'], form: '名詞', 意味: "teacher" },
        かかりのもの: { 読み方: ['係の者'], form: '名詞', 意味: "person who handles a particular business matter [者 is generally a humble expression for 人]" },
        しゅにん: { 読み方: ['主任'], form: '名詞', 意味: "a person in charge" },
        なんせい: { 読み方: ['南西'], form: '名詞', 意味: "southwest" },
        けいけん: { 読み方: ['経験'], form: '名詞', 意味: "experience" },
        ぜんぜん: { 読み方: ['全然'], form: '副詞', 意味: "(not) at all; totally" },
        こじん: { 読み方: ['個人'], form: '名詞、ノ形容詞', 意味: "personal; private" },
        たりる: { 読み方: ['足りる'], form: '一段動詞、自動詞', 意味: "to be sufficient; to be enough" },
        とくぎ: { 読み方: ['特技'], form: '名詞', 意味: "special talent; skill" },
        さっそく: { 読み方: ['早速'], form: '副詞', 意味: "to lose no time in ~ing; immediately; without delay" },
        かんどう: { 読み方: ['感動'], form: '名詞、スル動詞', 意味: "being deeply moved emotionally" },
        はくじん: { 読み方: ['白人'], form: '名詞', 意味: "Caucasian" },
        ゆるす: { 読み方: ['許す'], form: '五段動詞、他動詞', 意味: "to allow; to forgive" },
        むかえる: { 読み方: ['迎える'], form: '一段動詞、他動詞', 意味: "to welcome; to go out to meet; to greet" },
        けっしん: { 読み方: ['（～と）決心'], form: '名詞、スル動詞', 意味: "determination; to be determed to~" },
        にほんきんかい: { 読み方: ['日本近海'], form: '名詞', 意味: "Japanese waters; off the coast of Japan" },
        ほうほう: { 読み方: ['方法'], form: '名詞', 意味: "method" },
        さいわい: { 読み方: ['幸い'], form: 'イ形容詞', 意味: "fortunately; luckily" },
        むかう: { 読み方: ['（～へ）向かう'], form: '五段動詞、自動詞', 意味: "to head toward~" },
        ほっかいどう: { 読み方: ['北海道'], form: '県', 意味: "[日本の一番北の大きい島]" },
        けってい: { 読み方: ['（～に）決定する'], form: '名詞、スル動詞', 意味: "to decide[=～に決める]" },
        かれ: { 読み方: ['彼'], form: '代名詞', 意味: "he; him" },
        あらわれる: { 読み方: ['現れる'], form: '一段動詞、自動詞', 意味: "to appear" },
        つうやく: { 読み方: ['通訳'], form: '名詞、スル動詞', 意味: "interpreter; interpretation" },
        ふべん: { 読み方: ['不便'], form: '名詞、ナ形容詞', 意味: "inconvenience" },
        まなぶ: { 読み方: ['学ぶ'], form: '五段動詞', 意味: "to learn; to study" },
        かえす: { 読み方: ['返す'], form: '五段動詞、他動詞', 意味: "to return (something)" },
        びょうし: { 読み方: ['病死'], form: '名詞、スル動詞', 意味: "death from disease" },
        てんさい: { 読み方: ['天才'], form: '名詞', 意味: "genius" },
        えど: { 読み方: ['江戸'], form: '名詞', 意味: "Edo" },
        // Chapter 9

        // : { 読み方: [''], form: '', 意味: "" },

        // Chapter 12
        びょうじょう: { 読み方: ['病状'], form: '名詞', 意味: "the condition of a disease or illness; patient's condition" },
        かおいろ: { 読み方: ['顔色'], form: '名詞', 意味: "complexion; one's color" },
        いしゃ: { 読み方: ['医者'], form: '名詞', 意味: "(medical) doctor" },
        ちず: { 読み方: ['地図'], form: '名詞', 意味: "map" },
        ねつ: { 読み方: ['熱'], form: '名詞', 意味: "fever" },
        さむけ: { 読み方: ['寒気がする'], form: '名詞', 意味: "chill; the shivers" },
        しょくよく: { 読み方: ['食欲'], form: '名詞', 意味: "appetite" },
        くすり: { 読み方: ['薬'], form: '名詞', 意味: "medicine" },
        なおる: { 読み方: ['治る'], form: '五段動詞、自動詞', 意味: "to get better; to recover from illness" },
        おきる: { 読み方: ['起きる'], form: '一段動詞、自動詞', 意味: "to get up" },
        しかめっつら: { 読み方: ['しかめっ面'], form: '名詞、ノ形容詞', 意味: "grimace; frown" },
        けさ: { 読み方: ['今朝'], form: '名詞', 意味: "this morning" },
        あく: { 読み方: ['空く'], form: '五段動詞、自動詞', 意味: "to become vacant" },
        うんがいい: { 読み方: ['運がいい'], form: '表現、イ形容詞', 意味: "lucky" },
        せいこう: { 読み方: ['成功'], form: '名詞、スル動詞', 意味: "success" },
        ぐあい: { 読み方: ['具合'], form: '名詞', 意味: "condition; state" },
        しょうじょう: { 読み方: ['症状'], form: '名詞', 意味: "symptoms" },
        げんざい: { 読み方: ['現在'], form: '名詞、副詞', 意味: "now; present time; [＝今]" },
        い: { 読み方: ['胃'], form: '名詞', 意味: "stomach" },
        おもっくるしい: { 読み方: ['重っ苦しい'], form: 'イ形容詞', 意味: "heavy; dull; leaden" },
        あびせる: { 読み方: ['浴びせる'], form: '一段動詞、他動詞', 意味: "to shower (someone) with (something); to pour on" },
        はらをたてる: { 読み方: ['腹を立てる'], form: '表現、一段動詞', 意味: "to get angry[＝おこる]; to take offense; " },
        むちゃ: { 読み方: ['無茶'], form: 'ナ形容詞', 意味: "unreasonable" },
        しゅちょう: { 読み方: ['主張する'], form: 'スル動詞', 意味: "to assert; to insist" },

        // : { 読み方: [''], form: '', 意味: "" },
    },

    yomerebaii: {
        // Chapter 1
        紹介:{ 読み方: ['しょうかい'], form: '名詞、スル動詞、ノ形容詞', 意味: "introduction" },
        宿題:{ 読み方: ['しゅくだい'], form: '名詞', 意味: "homework" },
        池田:{ 読み方: ['いけだ'], form: '名字', 意味: "pond + rice field" },
        友達:{ 読み方: ['ともだち'], form: '名詞', 意味: "friend" },
        趣味:{ 読み方: ['しゅみ'], form: '名詞', 意味: "hobby; pastime" },
        隣:{ 読み方: ['となり'], form: 'ノ形容詞、名詞', 意味: "next to; next door" },
        家族:{ 読み方: ['かぞく'], form: '名詞', 意味: "family; members of a family" },
        遊ぶ:{ 読み方: ['あそぶ'], form: '五段動詞、自動詞', 意味: "to play; to hang out" },
        知識:{ 読み方: ['ちしき'], form: '名詞', 意味: "knowledge; information" },
        豊富:{ 読み方: ['ほうふ'], form: 'ナ形容詞、名詞', 意味: "abundant; plentiful" },
        飛行機:{ 読み方: ['ひこうき'], form: '名詞', 意味: "airplane" },
        座る:{ 読み方: ['（～に）すわる'], form: '五段動詞、自動詞', 意味: "to sit（in/on～）" },
        卒業:{ 読み方: ['（～を）そつぎょう'], form: '名詞、スル動詞', 意味: "graduation; moving on (from)" },
        勤める:{ 読み方: ['（～に）つとめる'], form: '一段動詞、他動詞', 意味: "to work （for～）; to be employed （at～）" },
        休暇:{ 読み方: ['きゅうか'], form: '名詞', 意味: "vacation; absence (from work)" },
        京都:{ 読み方: ['きょうと'], form: '都市', 意味: "Kyoto (city, prefecture)\n京都市\n京都府" },
        育つ:{ 読み方: ['（～で）そだつ'], form: '五段動詞、自動詞', 意味: "to grow up（in～）" },
        一晩:{ 読み方: ['ひとばん'], form: '名詞、副詞', 意味: "one night; overnight" },
        両親:{ 読み方: ['りょうしん'], form: '名詞', 意味: "parents; both parents" },
        名刺:{ 読み方: ['めいし'], form: '名詞', 意味: "business card" },
        番号:{ 読み方: ['ばんごう'], form: '名刺', 意味: "number" },
        十数時間:{ 読み方: ['じゅうすうじかん'], form: '', 意味: "ten plus a few hours" },
        空港:{ 読み方: ['くうこう'], form: '名詞', 意味: "airport" },
        迎える:{ 読み方: ['むかえる'], form: '一段動詞、他動詞', 意味: "to welcome; to go out to meet; to greet" },
        呼ぶ:{ 読み方: ['（～を…で）よぶ'], form: '五段動詞、他動詞', 意味: "to call ～ by…" },
        時差ぼけ:{ 読み方: ['時差ボケ'], form: '名詞', 意味: "jet lag" },
        眠る:{ 読み方: ['ねむる'], form: '五段動詞、自動詞', 意味: "to sleep" },
        連れて:{ 読み方: ['つれて行く、つれてくる'], form: '', 意味: "to take someone to, to bring someone along" },
        結局:{ 読み方: ['けっきょく'], form: '副詞', 意味: "finally; in the end" },
        適当:{ 読み方: ['てきとう'], form: 'ナ形容詞', 意味: "appropriate; suitable" },
        引っ越す:{ 読み方: ['ひっこす'], form: '五段動詞、自動詞', 意味: "to move to a new place of residence" },
        若い:{ 読み方: ['わかい'], form: 'イ形容詞', 意味: "young" },
        お互い:{ 読み方: ['おたがい'], form: '名詞、ノ形容詞、副詞', 意味: "each other; one another" },
        娘:{ 読み方: ['むすめ'], form: '名詞', 意味: "daughter" },
        違う:{ 読み方: ['ちがう'], form: '五段動詞、自動詞', 意味: "to differ; to be different" },
        興味:{ 読み方: ['きょうみ'], form: '名詞', 意味: "interest (in something); curiosity (about something)" },
        // Chapter 2
        言葉:{ 読み方: ['ことば'], form: '名詞', 意味: "word(s); expression(s)" },
        会釈:{ 読み方: ['えしゃく'], form: 'スル動詞、名詞', 意味: "to greet by bowing slightly" },
        頭:{ 読み方: ['あたま'], form: '名詞', 意味: "head" },
        鳴る:{ 読み方: ['なる'], form: '五段動詞、自動詞', 意味: "to sound; to ring" },
        寮:{ 読み方: ['りょう'], form: '名詞', 意味: "dormitory" },
        部屋:{ 読み方: ['へや'], form: '名詞', 意味: "room" },
        同室:{ 読み方: ['どうしつ'], form: '名詞', 意味: "same room; sharing a room" },
        寝る:{ 読み方: ['ねる'], form: '一段動詞、自動詞', 意味: "to sleep; to go to bed" },
        終わる:{ 読み方: ['おわる'], form: '五段動詞、自動詞', 意味: "be finished; be over" },
        授業:{ 読み方: ['じゅぎょう'], form: '名詞', 意味: "class" },
        遅れる:{ 読み方: ['おくれる'], form: '一段動詞、自動詞', 意味: "to be late" },
        一郎:{ 読み方: ['いちろう'], form: '男性の名前', 意味: "often given to the oldest son;\none + son" },
        同級生:{ 読み方: ['どうきゅうせい'], form: '名詞', 意味: "classmate" },
        質問:{ 読み方: ['しつもん'], form: '名詞、スル動詞', 意味: "question" },
        病気:{ 読み方: ['びょうき'], form: '名詞、ノ形容詞', 意味: "sickness; illness" },
        非常:{ 読み方: ['ひじょう（に）'], form: '', 意味: "emergency; (very; extremely)" },
        寒い:{ 読み方: ['さむい'], form: 'イ形容詞', 意味: "cold" },
        別れる:{ 読み方: ['（～と）わかれる'], form: '一段動詞、自動詞', 意味: "to part（from～）;\nto say farewell（to～）" },
        顔:{ 読み方: ['かお'], form: '名詞', 意味: "face" },
        一般的:{ 読み方: ['いっぱんてき'], form: 'ナ形容詞', 意味: "general" },
        // Chapter 3
        研究室:{ 読み方: ['けんきゅうしつ'], form: '名詞', 意味: "professor's office" },
        期末試験:{ 読み方: ['きまつしけん'], form: '名詞', 意味: "final exam; semester-end exam" },
        推薦状:{ 読み方: ['すいせんじょう'], form: '名詞', 意味: "letter of recommendation" },
        奨学金:{ 読み方: ['しょうがくきん'], form: '名詞', 意味: "scholarship" },
        用紙:{ 読み方: ['ようし'], form: '名詞', 意味: "form; blank form; sheet(s) of paper" },
        紙:{ 読み方: ['かみ'], form: '名詞', 意味: "ppaer" },
        締め切り:{ 読み方: ['しめきり'], form: '名詞', 意味: "deadline" },
        貸す:{ 読み方: ['かす'], form: '五段動詞、他動詞', 意味: "to lend; to loan" },
        熱:{ 読み方: ['ねつ'], form: '名詞', 意味: "fever" },
        寄る:{ 読み方: ['よる'], form: '五段動詞、自動詞', 意味: "to stop by" },
        情報:{ 読み方: ['じょうほう'], form: '名詞', 意味: "information" },
        交換:{ 読み方: ['こうかん'], form: '名詞、スル動詞', 意味: "exchange; switching" },
        場合:{ 読み方: ['ばあい'], form: '副詞、名詞', 意味: "case" },
        授業料:{ 読み方: ['じゅぎょうりょう'], form: '名詞', 意味: "tuition fee; course fee" },
        数:{ 読み方: ['かず'], form: '名詞', 意味: "number" },
        普通:{ 読み方: ['ふつう'], form: 'ノ形容詞、ナ形容詞', 意味: "common; usual; normal" },
        選ぶ:{ 読み方: ['えらぶ'], form: '五段動詞、他動詞', 意味: "to choose; to select" },
        書類選考:{ 読み方: ['しょるいせんこう'], form: '名詞、スル動詞', 意味: "screening by application forms; narrowing down a field of applicants based on resumes" },
        面接:{ 読み方: ['めんせつ'], form: '名詞、スル動詞', 意味: "interview" },
        成績:{ 読み方: ['せいせき'], form: '名詞', 意味: "grade; academic record" },
        性格:{ 読み方: ['せいかく'], form: '名詞', 意味: "character; personality" },
        態度:{ 読み方: ['たいど'], form: '名詞', 意味: "attitude; manner; behaviour" },
        優先:{ 読み方: ['ゆうせん'], form: '名詞、スル動詞、ノ形容詞', 意味: "preference; priority" },
        単位:{ 読み方: ['たんい'], form: '名詞', 意味: "credit (in school)" },
        認める:{ 読み方: ['みとめる'], form: '一段動詞、他動詞', 意味: "to recognize; to approve" },
        交渉:{ 読み方: ['こうしょう'], form: '名詞、スル動詞', 意味: "negotiation" },
        別科:{ 読み方: ['べっか'], form: '名詞', 意味: "special course" },
        国際学部:{ 読み方: ['こくさいがくぶ'], form: '名詞', 意味: "international division" },
        歴史:{ 読み方: ['れきし'], form: '名詞', 意味: "history" },
        経済:{ 読み方: ['けいざい'], form: '名詞', 意味: "economy; economics" },
        政治:{ 読み方: ['せいじ'], form: '名詞', 意味: "politics; government" },
        宗教:{ 読み方: ['しゅうきょう'], form: '名詞', 意味: "religion" },
        活動:{ 読み方: ['かつどう'], form: '名詞、スル動詞', 意味: "activity; action" },
        家庭:{ 読み方: ['かてい'], form: '名詞', 意味: "family; home" },
        希望者:{ 読み方: ['きぼうしゃ'], form: '名詞', 意味: "applicant; person interested in doing something" },
        住宅事情:{ 読み方: ['じゅうたくじじょう'], form: '名詞', 意味: "housing conditions/situation" },
        // Chapter 4
        許可:{ 読み方: ['きょか'], form: '名詞', 意味: "permission" },
        財布:{ 読み方: ['さいふ'], form: '名詞', 意味: "wallet" },
        背:{ 読み方: ['せ'], form: '名詞', 意味: "one's height" },
        弁護士:{ 読み方: ['べんごし'], form: '名詞', 意味: "lawyer" },
        珍しい:{ 読み方: ['めずらしい'], form: 'イ形容詞', 意味: "rare; unusual" },
        全然:{ 読み方: ['ぜんぜん（～ない）'], form: '副詞', 意味: "(not) at all" },
        州都:{ 読み方: ['しゅうと'], form: '名詞', 意味: "state capital" },
        知事:{ 読み方: ['ちじ'], form: '名詞', 意味: "governor" },
        皆さん:{ 読み方: ['みなさん'], form: '名詞', 意味: "all of you; everyone" },
        求める:{ 読み方: ['もとめる'], form: '一段動詞、他動詞', 意味: "to request; to ask for" },
        偶然:{ 読み方: ['ぐうぜん'], form: 'ナ形容詞、ノ形容詞、副詞', 意味: "chance; coincidence; by chance" },
        暖かい:{ 読み方: ['あたたかい'], form: 'イ形容詞', 意味: "pleasantly warm [with reference to weather]" },
        紅葉:{ 読み方: ['こうよう'], form: '名詞、スル動詞', 意味: "fall colors (of leaves)" },
        面白い:{ 読み方: ['おもしろい'], form: 'イ形容詞', 意味: "interesting, amusing" },
        経験:{ 読み方: ['けいけん'], form: '名詞、する動詞', 意味: "experience" },
        済む:{ 読み方: ['（～ないで）すむ'], form: '五段動詞、自動詞', 意味: "to get by without ~ing" },
        携帯:{ 読み方: ['けいたい'], form: '名詞', 意味: "cellular (phone)" },
        熱心:{ 読み方: ['ねっしん（に）'], form: 'ナ形容詞', 意味: "eager(ly); ardent(ly; enthusiastic(ly)" },
        打つ:{ 読み方: ['うつ'], form: '五段動詞、他動詞', 意味: "to type (messages)" },
        料理:{ 読み方: ['りょうり'], form: '名詞、スル動詞', 意味: "cooking; cuisine" },
        物:{ 読み方: ['もの'], form: '名詞', 意味: "thing" },
        体重:{ 読み方: ['たいじゅう'], form: '名詞', 意味: "body weight" },
        足りる:{ 読み方: ['たりる'], form: '一段動詞、自動詞', 意味: "to be sufficient; to be enough" },
        伝える:{ 読み方: ['つたえる'], form: '一段動詞、他動詞', 意味: "to convey; to report; to communicate" },
        // Chapter 5
        事務員: { 読み方: ['じむいん'], form: '名詞', 意味: "office clerk; office staff" },
        建物: { 読み方: ['たてもの'], form: '名詞', 意味: "building" },
        玄関: { 読み方: ['げんかん'], form: '名詞', 意味: "entrance (to a house or a building)" },
        貼り紙: { 読み方: ['はりがみ'], form: '名詞', 意味: "paper posted (on a board, a well, etc.)" },
        発表: { 読み方: ['はっぴょう'], form: 'スル動詞、名詞', 意味: "to announce; announcement; expressing (one's opinion)" },
        場所: { 読み方: ['ばしょ'], form: '名詞', 意味: "place" },
        佐藤: { 読み方: ['さとう'], form: '名字', 意味: "assist + wisteria" },
        相談: { 読み方: ['そうだん'], form: 'スル動詞、名詞', 意味: "to consult (someone) about (something); asking (somebody) for advice; consultation" },
        調子: { 読み方: ['ちょうし'], form: '名詞', 意味: "condition; state of health" },
        心配: { 読み方: ['しんぱい'], form: '名詞、スル動詞、ナ形容詞', 意味: "worry; concern" },
        様子: { 読み方: ['ようすを見る'], form: '名詞', 意味: "state of affairs; appearance; see how it goes" },
        勧誘: { 読み方: ['かんゆう'], form: '名詞、スル動詞', 意味: "inviting someone to join (a club)" },
        無人島: { 読み方: ['むじんとう'], form: '名詞', 意味: "uninhabited island" },
        居酒屋: { 読み方: ['いざかや'], form: '名詞', 意味: "Japanese style pub; Japanese bar that also serves various dishes and snacks" },
        将来: { 読み方: ['しょうらい'], form: '名詞', 意味: "future (usually near)" },
        未来: { 読み方: ['みらい'], form: '名詞、ノ形容詞', 意味: "future (usually distant)" },
        一流: { 読み方: ['いちりゅう'], form: 'ノ形容詞、名詞', 意味: "first-class; first-rate" },
        就職: { 読み方: ['しゅうしょく'], form: '名詞、スル動詞', 意味: "finding employment; getting a job" },
        増える: { 読み方: ['ふえる'], form: '一段動詞、自動詞', 意味: "to increase" },
        塾: { 読み方: ['じゅく'], form: '名詞', 意味: "after-school school; cram school" },
        予備校: { 読み方: ['よびこう'], form: '名詞', 意味: "prepatory school (for college entrance exams)" },
        落ちる: { 読み方: ['おちる'], form: '一段動詞、自動詞', 意味: "to fall; (試験に落ちる　to fail an exam)" },
        浪人: { 読み方: ['ろうにん'], form: '名詞', 意味: "unemployed samurai; a high school graduate student who is spending a year studying for a college entrance exam" },
        傾向: { 読み方: ['けいこう'], form: '名詞、スル動詞', 意味: "tendency; trend" },
        最近: { 読み方: ['さいきん'], form: '名詞、ノ形容詞、副詞', 意味: "recently" },
        確かに: { 読み方: ['たしかに'], form: '副詞', 意味: "surely; certainly" },
        調査: { 読み方: ['ちょうさ'], form: '名詞、スル動詞', 意味: "investigation; examination; survey" },
        好く: { 読み方: ['すく'], form: '五段動詞、他動詞', 意味: "to like; to be fond of" },
        少子化: { 読み方: ['しょうしか'], form: '名詞、スル動詞', 意味: "declining birth rates" },
        関して: { 読み方: ['～にかんして'], form: '表現', 意味: "concerning; in relation to; as far as ... is concerned" },
        講義: { 読み方: ['こうぎ'], form: '名詞、スル動詞', 意味: "lecture" },
        年々: { 読み方: ['ねんねん'], form: '名詞、副詞', 意味: "year by year; every year" },
        減る: { 読み方: ['へる'], form: '五段動詞、自動詞', 意味: "to decrease (in number or size)" },
        // Chapter 6
        引用: { 読み方: ['いんよう'], form: '名詞、スル動詞、ノ形容詞', 意味: "to quote; quotation" },
        同僚: { 読み方: ['どうりょう'], form: '名詞', 意味: "colleague; co-worker" },
        高橋: { 読み方: ['たかはし'], form: '名字', 意味: "tall + bridge" },
        丼物: { 読み方: ['どんぶりもの'], form: '名詞', 意味: "[name of dish; bowl of rice topped with things]" },
        卵: { 読み方: ['たまご'], form: '名詞', 意味: "egg" },
        腰: { 読み方: ['こし'], form: '名詞', 意味: "lower back; waist; [腰をかける = 椅子に座る]" },
        握る: { 読み方: ['にぎる'], form: '五段動詞、他動詞', 意味: "to make sushi by hand" },
        並: { 読み方: ['なみ'], form: 'ノ形容詞、名詞', 意味: "(sushi serving of) medium quality/price" },
        召し上がる: { 読み方: ['召し上がる'], form: '五段動詞、他動詞、尊敬語', 意味: "[honorific form of 食べる・飲む]" },
        参る: { 読み方: ['まいる'], form: '五段動詞、自動詞、謙譲語', 意味: "[humble form of 行く・来る]" },
        請求書: { 読み方: ['せいきゅうしょ'], form: '名詞', 意味: "bill; invoice" },
        健一: { 読み方: ['けんいち'], form: '男の名前', 意味: "health + one" },
        辺り: { 読み方: ['あたり'], form: '名詞、接尾詞', 意味: "vicinity; nearby" },
        腹: { 読み方: ['はら'], form: '名詞', 意味: "stomach" },
        面倒: { 読み方: ['めんどう'], form: '名詞、ナ形容詞', 意味: "troublesome" },
        降りる: { 読み方: ['（～を）おりる'], form: '一段動詞、自動詞', 意味: "to get off~; to get out of (a vehicle)" },
        運転手: { 読み方: ['うんてんしゅ'], form: '名詞', 意味: "driver [by occupation]" },
        荷物: { 読み方: ['にもつ'], form: '名詞', 意味: "luggage" },
        運ぶ: { 読み方: ['はこぶ'], form: '五段動詞、他動詞', 意味: "to carry" },
        片付ける: { 読み方: ['かたづける'], form: '一段動詞、他動詞', 意味: "to clean; to tidy up" },
        食堂: { 読み方: ['しょくどう'], form: '名詞', 意味: "dining room" },
        簡単: { 読み方: ['かんたん'], form: 'ナ形容詞', 意味: "simple; easy" },
        含まれる: { 読み方: ['（～に）ふくまれる'], form: '受身形', 意味: "to be included (in~) [passive form of 含む]" },
        計算: { 読み方: ['けいさん'], form: '名詞、スル動詞', 意味: "calculation" },
        床屋: { 読み方: ['とこや'], form: '名詞', 意味: "barbershop" },
        美容院: { 読み方: ['びよういん'], form: '名詞', 意味: "beauty salon" },
        宣伝: { 読み方: ['せんでん'], form: '名詞、スル動詞', 意味: "advertisement" },
        // Chapter 7
        誘う: { 読み方: ['さそう'], form: '五段動詞、他動詞', 意味: "to invite (someone to do something with the speaker)" },
        野球: { 読み方: ['やきゅう'], form: '名詞', 意味: "baseball" },
        一緒: { 読み方: ['いっしょ'], form: '副詞、名詞、ノ形容詞', 意味: "together; same" },
        喜んで: { 読み方: ['喜んで'], form: '副詞', 意味: "with pleasure" },
        歳: { 読み方: ['～さい'], form: '接尾詞', 意味: "~years-old" },
        残念: { 読み方: ['ざんねん'], form: 'ナ形容詞、名詞', 意味: "regrettable; dissapointing" },
        秋葉原: { 読み方: ['あきはばら'], form: '東京の地方', 意味: "district of Tokyo, Japan." },
        電気街: { 読み方: ['でんきまち'], form: '名詞', 意味: "electronic store district" },
        山手線: { 読み方: ['やまのてせん'], form: '名詞', 意味: "[name of a train line]" },
        京浜東北線: { 読み方: ['けいひんとうほくせん'], form: '名詞', 意味: "[name of a train line]" },
        快速: { 読み方: ['かいそく'], form: '名詞', 意味: "rapid train or bus" },
        改札口: { 読み方: ['かいさつぐち'], form: '名詞', 意味: "ticket barrier; ticket gate" },
        黒沢: { 読み方: ['くろさわ'], form: '名字', 意味: "black + brilliance" },
        監督: { 読み方: ['かんとく'], form: '名詞', 意味: "movie director" },
        徹夜: { 読み方: ['てつや'], form: '名詞、スル動詞、ノ形容詞', 意味: "staying up all night" },
        選手: { 読み方: ['せんしゅ'], form: '名詞', 意味: "player (sports); athlete" },
        投げる: { 読み方: ['なげる'], form: '一段動詞、他動詞', 意味: "to throw" },
        三振: { 読み方: ['さんしん'], form: '名詞、スル動詞', 意味: "strikeout" },
        活躍する: { 読み方: ['かつやくする'], form: '名詞、スル動詞', 意味: "to play an active part in" },
        地域: { 読み方: ['ちいき'], form: '名詞', 意味: "area; region" },
        優勝: { 読み方: ['ゆうしょう'], form: '名詞、スル動詞', 意味: "overall victory; championship" },
        野球場: { 読み方: ['やきゅうじょう'], form: '名詞', 意味: "baseball stadium" },
        応援: { 読み方: ['おうえん'], form: '名詞、スル動詞', 意味: "cheering; rooting (for); support" },
        出場: { 読み方: ['しゅつじょう'], form: '名詞、スル動詞', 意味: "participation (in an event); to compete in" },
        名誉: { 読み方: ['めいよ'], form: 'ナ形容詞、名詞', 意味: "honor; honorable" },
        大相撲: { 読み方: ['おおずもう'], form: '名詞', 意味: "the professional sumo" },
        力士: { 読み方: ['りきし'], form: '名詞', 意味: "sumo wrestler" },
        // Chapter 8
        対象: { 読み方: ['たいしょう'], form: '名詞、ノ形容詞', 意味: "target; object (of worship, study, etc.)" },
        詳しい: { 読み方: ['くわしい'], form: 'イ形容詞', 意味: "detailed" },
        主婦: { 読み方: ['しゅふ'], form: '名詞', 意味: "housewife" },
        親類: { 読み方: ['しんるい'], form: '名詞', 意味: "relative(s)" },
        翻訳: { 読み方: ['ほんやく'], form: '名詞、スル動詞', 意味: "translation" },
        掲示板: { 読み方: ['けいじばん'], form: '名詞', 意味: "bulletin board" },
        編集: { 読み方: ['へんしゅう'], form: '名詞、スル動詞', 意味: "editing" },
        雇う: { 読み方: ['やとう'], form: '五段動詞、他動詞', 意味: "to hire" },
        森山: { 読み方: ['もりやま'], form: '苗字', 意味: "forest + mountain" },
        大陸: { 読み方: ['大陸'], form: '名詞', 意味: "continent" },
        漂流者: { 読み方: ['ひょうりゅうしゃ'], form: '名詞', 意味: "person adrift on the sea; castaway (on an island)" },
        流れ着く: { 読み方: ['（～に）ながれつく'], form: '五段動詞', 意味: "to drift ashore" },
        祖先: { 読み方: ['そせん'], form: '名詞', 意味: "ancestor(s)" },
        憧れ: { 読み方: ['あこがれ'], form: '名詞、ノ形容詞', 意味: "longing; yearning" },
        雑誌: { 読み方: ['ざっし'], form: '名詞', 意味: "magazine" },
        抱く: { 読み方: ['いだく'], form: '五段動詞、他動詞', 意味: "to hold [written expression]" },
        鎖国: { 読み方: ['さこく'], form: '名詞、スル動詞', 意味: "national isolation" },
        温かい: { 読み方: ['あたたかい'], form: 'イ形容詞', 意味: "warm (for objects' temperature)" },
        船員: { 読み方: ['せんいん'], form: '名詞', 意味: "sailor" },
        陸地: { 読み方: ['りくち'], form: '名詞', 意味: "land" },
        幕府: { 読み方: ['ばくふ'], form: '名詞', 意味: "the Shogunate" },
        驚く: { 読み方: ['おどろく'], form: '五段動詞、自動詞', 意味: "to be surprised" },
        長崎: { 読み方: ['ながさき'], form: '都市、県', 意味: "Nagasaki (city, prefecture)" },
        難破: { 読み方: ['なんぱ'], form: '名詞、スル動詞', 意味: "shipwreck" },
        翌: { 読み方: ['よく'], form: '接頭辞', 意味: "the next (day/year/etc.) [＝次の]" },
        姪: { 読み方: ['めい'], form: '名詞', 意味: "niece" },
        開国: { 読み方: ['かいこく'], form: '名詞、スル動詞', 意味: "to open up the country (to foreigners) [＝国を開くこと]" },
        湾: { 読み方: ['わん'], form: '名詞', 意味: "bay" },
        戻る: { 読み方: ['もどる'], form: '五段動詞、自動詞', 意味: "to return" },
        条約: { 読み方: ['じょうやく'], form: '名詞', 意味: "treaty" },
        立派: { 読み方: ['りっぱ'], form: 'ナ形容詞', 意味: "splendid" },
        // Chapter 9
        // : { 読み方: [''], form: '', 意味: "" },

        // Chapter 12
        訴える: { 読み方: ['うったえる'], form: '一段動詞、他動詞', 意味: "to complain of" },
        吐く: { 読み方: ['はく'], form: '五段動詞、他動詞', 意味: "to throw up" },
        診る: { 読み方: ['みる'], form: '一段動詞、他動詞', 意味: "to examine (medical); to examine (a patient)" },
        下痢: { 読み方: ['げり'], form: '名詞、スル動詞', 意味: "diarrhea" },
        服用: { 読み方: ['ふくよう'], form: '名詞、スル動詞', 意味: "taking medicine [＝薬を飲む]" },
        軟らかい: { 読み方: ['やわらかい'], form: 'イ形容詞', 意味: "soft" },
        歯: { 読み方: ['は'], form: '名詞', 意味: "tooth" },
        歯科: { 読み方: ['しか'], form: '名詞', 意味: "dental clinic; dentistry" },
        突然: { 読み方: ['とつぜん'], form: 'ノ形容詞、ナ形容詞、副詞', 意味: "suddenly; abrupt; unexpected" },
        患者: { 読み方: ['かんじゃ'], form: '名詞', 意味: "patient" },
        問診: { 読み方: ['もんしん'], form: '名詞、スル動詞', 意味: "interview (with a doctor)" },
        診察: { 読み方: ['しんさつ'], form: '名詞、スル動詞', 意味: "medical examination of a patient" },
        手順: { 読み方: ['てじゅん'], form: '名詞', 意味: "procedure; process" },
        雰囲気: { 読み方: ['ふんいき'], form: '名詞', 意味: "atmosphere; mood; aura" },
        導入: { 読み方: ['どうにゅう'], form: '名詞、スル動詞', 意味: "introduction; bringing in" },
        脱線: { 読み方: ['だっせん'], form: 'スル動詞', 意味: "to derail; to digress; to ramble" },
        素人: { 読み方: ['しろうと'], form: '名詞', 意味: "amateur; ordinary person; novice" },

        // : { 読み方: [''], form: '', 意味: "" },
    }
}

export default kanji;